import {M3_ORT_ASSETS} from './m3-ort-assets.js';import {fetchM3Asset} from './m3-asset.js';import {RESEARCH_POST_WASM} from './research-post-assets.js';import {RESEARCH_PREPARE_WASM} from './research-prepare-assets.js';
self.onmessage=async({data:job})=>{
 let encoder,decoder,prepare,post;const tensors=[];
 try{
  const {default:createPost}=await import('../vendor/research-post/post.js');post=await createPost({wasmBinary:await fetchM3Asset(new URL('../vendor/research-post/post.wasm',import.meta.url),RESEARCH_POST_WASM),wasmMemory:new WebAssembly.Memory({initial:256,maximum:job.postHeapBytes/65536})});
  const alloc=(m,n)=>{const p=m._malloc(Math.max(n,8));if(!p)throw Error('SAFIRE memory allocation failed');return p;},put=(m,a)=>{const p=alloc(m,a.byteLength);m.HEAPU8.set(new Uint8Array(a.buffer,a.byteOffset,a.byteLength),p);return p;};
  if(job.task==='compose'){
   const {proposals:p,params}=job,n=p.confidence.length,fp=put(post,p.features),lp=alloc(post,n*4);let iterations;
   if(params.kind==='kmeans')iterations=post._safire_kmeans(fp,n,params.binary?2:params.groups,lp);else iterations=post._safire_dbscan(fp,n,params.eps,params.minimum,lp);
   if(params.kind==='kmeans'&&!iterations)throw Error('SAFIRE clustering failed');const assignments=post.HEAP32.slice(lp/4,lp/4+n),best=new Map();for(let i=0;i<n;i++)if(assignments[i]>=0&&(!best.has(assignments[i])||p.confidence[i]>p.confidence[best.get(assignments[i])]))best.set(assignments[i],i);
   const chosen=[...best.values()].sort((a,b)=>a-b);if(!chosen.length)throw Error('SAFIRE clustering produced no supported source region. Adjust grouping settings.');if(chosen.length>64)throw Error('More than 64 source groups. Increase DBSCAN distance or use k-means.');
   post._free(fp);post._free(lp);const masks=alloc(post,chosen.length*65536*4),areas=alloc(post,chosen.length*4);chosen.forEach((id,i)=>{post.HEAPF32.set(p.lowMasks.subarray(id*65536,(id+1)*65536),masks/4+i*65536);post.HEAPU32[areas/4+i]=p.areas[id];});
   const size=1024*1024,prob=alloc(post,chosen.length*size*4),map=alloc(post,size*4),labels=alloc(post,size);if(!post._safire_maps(masks,areas,chosen.length,+params.binary,prob,map,labels))throw Error('SAFIRE map reconstruction failed');
   const result={map:post.HEAPF32.slice(map/4,map/4+size),source_probabilities:post.HEAPF32.slice(prob/4,prob/4+chosen.length*size),source_labels:post.HEAPU8.slice(labels,labels+size),prompt_clusters:assignments,chosen,metadata:{clusteringIterations:params.kind==='kmeans'?iterations:null,postHeapBytes:post.HEAPU8.byteLength}};postMessage(result,[result.map.buffer,result.source_probabilities.buffer,result.source_labels.buffer,assignments.buffer]);return;
  }
  const {image,side,model,provider,maximumHeapBytes}=job;let pixels=job.prepared;
  if(!pixels){const {default:createPrepare}=await import('../vendor/research-prepare/prepare.js');prepare=await createPrepare({wasmBinary:await fetchM3Asset(new URL('../vendor/research-prepare/prepare.wasm',import.meta.url),RESEARCH_PREPARE_WASM),wasmMemory:new WebAssembly.Memory({initial:256,maximum:job.prepareHeapBytes/65536})});
   const ip=put(prepare,image.data),op=alloc(prepare,1024*1024*12);if(prepare._research_prepare(ip,image.width,image.height,op,0)!==1)throw Error('SAFIRE image preparation failed');pixels=prepare.HEAPF32.slice(op/4,op/4+1024*1024*3);prepare._free(ip);prepare._free(op);}
  globalThis.__m3MaximumWasmPages=maximumHeapBytes/65536;const gpu=provider==='webgpu',ort=await import(gpu?'../vendor/m3-ort/ort.webgpu.min.mjs':'../vendor/m3-ort/ort.wasm.min.mjs'),identity=M3_ORT_ASSETS[gpu?'gpu':'cpu'],factoryUrl=new URL(gpu?'../vendor/m3-ort/factory.asyncify.mjs':'../vendor/m3-ort/factory.mjs',import.meta.url).href;
  ort.env.wasm.wasmBinary=await fetchM3Asset(new URL(identity.path,import.meta.url),identity);ort.env.wasm.wasmPaths={mjs:factoryUrl,wasm:new URL(identity.path,import.meta.url).href};ort.env.wasm.numThreads=self.crossOriginIsolated?job.threads:1;ort.env.wasm.proxy=false;
  encoder=await ort.InferenceSession.create(model.encoder,{executionProviders:[provider],graphOptimizationLevel:'all'});const input=new ort.Tensor('float32',pixels,[1,3,1024,1024]);let encoded;try{encoded=await encoder.run({image:input});}finally{input.dispose();}tensors.push(...Object.values(encoded));const features=encoded.features,fp=put(post,features.data);await encoder.release();encoder=null;postMessage({progress:{phase:'safire-encoder',fraction:1/(side*side+1)}});
  decoder=await ort.InferenceSession.create(model.decoder,{executionProviders:[provider],graphOptimizationLevel:'all'});const count=side*side,allMasks=new Float32Array(count*65536),means=new Float32Array(count*256),confidence=new Float32Array(count),areas=new Uint32Array(count),points=new Float32Array(count*2),validIds=new Int32Array(count),mp=alloc(post,65536*4),mean=alloc(post,256*4),area=alloc(post,4);let valid=0;
  for(let lo=0;lo<count;lo+=job.promptBatch){
   const batch=Math.min(job.promptBatch,count-lo),coords=new Float32Array(batch*2);for(let i=0;i<batch;i++){const id=lo+i;coords[i*2]=(1/(2*side)+(id%side)*(1-1/side)/(side-1))*1024;coords[i*2+1]=(1/(2*side)+Math.floor(id/side)*(1-1/side)/(side-1))*1024;}const input=new ort.Tensor('float32',coords,[batch,1,2]);let output;
   try{output=await decoder.run({features,points:input});const masks=output.lowMasks.data,ious=output.confidence.data;for(let i=0;i<batch;i++){post.HEAPF32.set(masks.subarray(i*65536,(i+1)*65536),mp/4);const selected=post._safire_proposal(fp,mp,mean,area);if(selected<0)throw Error('SAFIRE proposal failed');if(!selected)continue;allMasks.set(masks.subarray(i*65536,(i+1)*65536),valid*65536);means.set(post.HEAPF32.subarray(mean/4,mean/4+256),valid*256);confidence[valid]=ious[i];areas[valid]=post.HEAPU32[area/4];points.set(coords.subarray(i*2,i*2+2),valid*2);validIds[valid]=lo+i;valid++;}}finally{input.dispose();for(const t of Object.values(output??{}))t.dispose();}
   postMessage({progress:{phase:'safire-proposals',fraction:(lo+batch+1)/(count+1),completed:lo+batch,total:count}});
  }
  if(!valid)throw Error('SAFIRE produced no nonempty region. Try a denser point grid.');const {heapBytes}=await import(factoryUrl),actualHeapBytes=heapBytes();if(actualHeapBytes>maximumHeapBytes)throw Error('ORT exceeded admitted memory');
  const result={lowMasks:valid===count?allMasks:allMasks.slice(0,valid*65536),features:means.slice(0,valid*256),confidence:confidence.slice(0,valid),areas:areas.slice(0,valid),points:points.slice(0,valid*2),validIds:validIds.slice(0,valid),metadata:{provider,actualHeapBytes,maximumHeapBytes,promptBatch:job.promptBatch,prepareHeapBytes:prepare?.HEAPU8.byteLength??0,postHeapBytes:post.HEAPU8.byteLength,threads:ort.env.wasm.numThreads,preflightExecutions:0}};postMessage(result,Object.values(result).filter(ArrayBuffer.isView).map(v=>v.buffer));
 }catch(error){postMessage({error:/memory|alloc|OOM|maximum|out of bounds/i.test(String(error))?'MEMORY_LIMIT':'SAFIRE_FAILED',message:String(error?.message??error)});}
 finally{for(const t of tensors)t.dispose();await encoder?.release();await decoder?.release();}
};
