import "../../runtime-context.js?v=0.14.5";
import {deserializeWorkerError} from './errors.js';
import {createReusableBuffer} from './reusable-buffer.js';
import {getSiftPreparationGate} from './sift-preparation-gate.js';
import {SiftPagedResources,siftResourceError} from './sift-paged-resources.js';
import {getExecutionScheduler} from './execution-scheduler.js';
import {SIFT_PAGED_WASM} from './sift-paged-assets.js';
import {fetchM3Asset} from './m3-asset.js';
import {createSegmentedBytes} from './segmented-bytes.js';
import {SiftPointPages,createSiftCheckpoint,runSiftCheckpointStage} from './sift-checkpoint.js';
import {groupSiftContinuations,packSiftContinuationStates,createSiftContinuationRound,acceptSiftContinuationBatch} from './sift-continuations.js';
import {researchRows} from './m3-research-rows.js';
import {validateRgbRows} from './rgb-row-source.js';
import {gray,roundEven} from './pixel-utils.js';
import {siftRegionPlan} from './sift-regions.js';
import {remapReflectedSiftPoints} from './sift-g2nn.js';
import {EngineError,requireValue,checkAbort,controlCheckpoint,deserializeEngineError,resourceAllocationKind} from './errors.js';
import {runWithResourceRecovery,reclaimForResourceRecovery} from './resource-recovery.js';
import {installWorkerMessageProtocol} from './worker-message-protocol.js';
const MiB=1024**2,f=Math.fround,byteView=a=>new Uint8Array(a.buffer,a.byteOffset,a.byteLength),roundHeap=n=>Math.min(2048*MiB,Math.ceil(n/(64*MiB))*64*MiB);
export class SiftPool{
 constructor(owner,options){Object.assign(this,options);this.owner=owner;this.records=[];this.scheduler=getExecutionScheduler(this.budget,{maxWorkers:owner.profile.maxWorkers});this.metrics={executions:0,retries:0,peakHeapBytes:0,workers:0,pyramidBuilds:0,pyramidCacheHits:0,failures:[]};this.resourceOwner??='sift';this.preparationGate=getSiftPreparationGate(this.budget,owner.profile.maxWorkers);}
 async open(count,heap=this.heap,provider=this.provider){
  // Slots are potential parallelism. Only useful admitted work creates a heap.
  for(let i=0;i<count;i++){const rec={heap,provider,worker:null,reject:null,busy:false};this.records.push(rec);this.owner.workers.add(rec);}
  requireValue(this.records.length>0,'No SIFT worker slots.');
  this.unregister=this.budget.registerAsyncReclaimer?.(async()=>{let freed=0;for(const rec of this.records)if(!rec.busy&&rec.worker){freed+=rec.heapBytes??0;this.stopRecord(rec);}return freed;},{allocationKind:'wasm',owner:this.resourceOwner,priority:30});
 }
 finishTask(rec){rec.releasePreparation?.();rec.releasePreparation=null;rec.resources?.close();rec.resources=null;rec.releaseWorkspace?.();rec.releaseWorkspace=null;rec.releaseInput?.();rec.releaseInput=null;rec.busy=false;rec.reusableInputData=null;if(!rec.inputInFlight)rec.inputWindow?.park();rec.heapBacking?.setReclaimable(true);}
 stopRecord(rec,error){rec.worker?.terminate();rec.worker=null;rec.reject?.(error??new EngineError('CANCELLED','SIFT work stopped'));rec.reject=null;this.finishTask(rec);if(rec.inputInFlight){rec.inputWindow?.retire();rec.inputInFlight=false;}rec.heapBacking?.();rec.heapBacking=null;rec.release?.();rec.release=null;if(rec.heapBytes)this.budget.notifyBackingRelease?.('wasm',rec.heapBytes);rec.heapBytes=0;}
 close(){this.unregister?.();this.unregister=null;for(const rec of this.records){this.stopRecord(rec);rec.inputWindow?.dispose();rec.inputWindow=null;this.owner.workers.delete(rec);}this.records=[];}
 rpc(rec,message,transfer=[]){return new Promise((resolve,reject)=>{
  let settled=false,protocol,abort;const finish=(error,value)=>{if(settled)return;settled=true;rec.reject=null;this.signal?.removeEventListener('abort',abort);protocol?.dispose();error?reject(error):resolve(value);};rec.reject=error=>finish(error);
  protocol=installWorkerMessageProtocol(rec.worker,async data=>{
   if(data.resourceEvent){const event=data.resourceEvent;if(event.action==='heap'){requireValue(Number.isSafeInteger(event.bytes)&&event.bytes<=rec.heap,'Invalid SIFT heap report.');rec.heapBytes=event.bytes;rec.heapBacking?.materialize(event.bytes);}else await rec.resources.message(event);return;}
   if(data.resourceRequest){const request=data.resourceRequest;try{await rec.resources.message(request);protocol.post({resourceReply:{id:request.id}});}catch(error){protocol.post({resourceReply:{id:request.id,error:siftResourceError(error)}});}return;}
   if(data.returnedInput){const returned=data.returnedInput;if(!message.reusableInput||returned.id!==message.reusableInput.id||!rec.inputInFlight)throw new EngineError('WORKER_MESSAGE_FAILED','Unexpected SIFT input ownership return.');try{rec.inputWindow.takeBack(returned.buffer);}catch(cause){throw new EngineError('WORKER_MESSAGE_FAILED','Invalid SIFT input ownership return.',{cause,details:{transport:{event:'message',reason:'invalid-input-acknowledgement',label:'sift-'+message.kind}}});}returned.buffer=null;delete data.returnedInput;rec.inputInFlight=false;}
   if(message.reusableInput&&rec.inputInFlight)throw new EngineError('WORKER_MESSAGE_FAILED','SIFT response did not return its input window.');
   if(data.error){finish(typeof data.error==='string'?deserializeWorkerError(data.error,data.message):deserializeEngineError(data.error));return;}
   const expected={init:'ready',scale:'gray',prepare:'base',detect:'points',refine:'status','refine-batch':'statuses',describe:'descriptors',select:'points'}[message.kind];
   if(!expected||!Object.hasOwn(data,expected))throw new EngineError('WORKER_MESSAGE_FAILED','Unexpected SIFT response.',{details:{transport:{event:'message',reason:'unexpected-response',label:'sift-'+message.kind}}});
   if(message.kind!=='init')this.attachResultOwner(rec,data);finish(null,data);
  },{label:'sift-'+message.kind,onFailure:error=>{this.stopRecord(rec,error);finish(error);}});
  rec.worker.onerror=event=>protocol.fail(new EngineError('WORKER_FAILED',event.message||'SIFT worker failed.',{cause:event.error}));
  abort=()=>this.stopRecord(rec,new EngineError('CANCELLED','SIFT worker request cancelled.'));this.signal?.addEventListener('abort',abort,{once:true});if(this.signal?.aborted){abort();return;}if(message.reusableInput)rec.inputInFlight=true;protocol.post(message,transfer);
 });}
 attachResultOwner(rec,result){
  const fields=new Map();for(const [key,value] of Object.entries(result))if(ArrayBuffer.isView(value))fields.set(key,{bytes:value.byteLength,id:result.resourceOutputs?.[key],refs:0,release:null});
  Object.defineProperty(result,'retainOwnership',{value:(...names)=>{const entries=(names.length?names:[...fields.keys()]).map(key=>fields.get(key)).filter(Boolean);for(const entry of entries){if(!entry.refs){const memory=entry.bytes?rec.resources.retainMemory(entry.bytes):null,backing=rec.resources.adoptBacking(entry.id);entry.release=()=>{backing?.();memory?.();};}entry.refs++;}let closed=false;return()=>{if(closed)return;closed=true;for(const entry of entries)if(--entry.refs===0){entry.release?.();entry.release=null;}};}});
 }
 async execute(rec,make){
  const ownsOperation=!rec.operation,operation=rec.operation??this.budget.beginOperation?.({owner:this.resourceOwner,id:'sift-native-tile'});rec.operation=operation;let stage='prepare';
  const progress=event=>{if(event.phase==='resource-recovery'){this.metrics.retries++;this.metrics.failures.push({provider:rec.provider,code:event.error.code,message:event.error.message});}this.onProgress?.(event);};
  try{return await runWithResourceRecovery(async()=>{for(;;){
   checkAbort(this.signal);this.finishTask(rec);rec.busy=true;rec.heapBacking?.setReclaimable(false);operation?.setState('io');stage='prepare';
   const reservationScope=this.budget.beginReservationScope(),track=release=>reservationScope.track(release);if(rec.release)rec.release=track(rec.release);
   try{
    const workspace=Math.max(0,this.cost(rec.heap,rec.provider)-rec.heap),inputAllowance=Math.min(workspace,this.inputBytes??Math.floor(workspace/4));
    if(rec.inputWindow?.byteLength)rec.inputWindow.hold();
    const missingInput=Math.max(0,inputAllowance-(rec.inputWindow?.byteLength??0));
    if(missingInput){const admission=await this.scheduler.acquire({cpu:0,bytes:missingInput,domains:{'array-buffer':missingInput},signal:this.signal,operation,resourceOwner:this.resourceOwner,label:'sift-input'});rec.releaseInput=track(admission.retainMemory(missingInput));admission.release();operation?.setState('io');}
    const allocateInput=(Type,length)=>{
     requireValue(!rec.reusableInputData,'A SIFT task may borrow only one input window.');
     rec.inputWindow??=createReusableBuffer({budget:this.budget,owner:this.resourceOwner,label:'sift-input-window'});
     const reserve=bytes=>{const parts=[];try{const fromAdmission=Math.min(bytes,rec.releaseInput?.bytes??0);if(fromAdmission)parts.push(rec.releaseInput.split(fromAdmission));if(bytes>fromAdmission)parts.push(track(this.budget.reserve(bytes-fromAdmission)));return()=>{for(const part of parts)part();parts.length=0;};}catch(error){error=reservationScope.capture(error);for(const part of parts)part();throw error;}};
     return rec.reusableInputData=rec.inputWindow.checkout(Type,length,{reserve,operation});
    };
    const message=await make({allocateInput});checkAbort(this.signal);stage='admission';
    if(rec.reusableInputData){requireValue(message.input===rec.reusableInputData,'SIFT borrowed window must be the submitted input.');message.reusableInput={id:rec.inputSerial=(rec.inputSerial??0)+1,capacityBytes:rec.inputWindow.byteLength};}
    const needsGpu=rec.provider==='webgpu'&&['prepare','detect','refine','refine-batch','describe'].includes(message.kind);if(needsGpu)rec.releasePreparation=await this.preparationGate.acquire({signal:this.signal,operation});
    const newHeap=rec.release?0:rec.heap,lease=await this.scheduler.acquire({cpu:1,gpu:0,bytes:newHeap+workspace-inputAllowance,domains:{wasm:newHeap,...(needsGpu?{gpu:workspace}:{})},signal:this.signal,operation,resourceOwner:this.resourceOwner,label:'sift-'+message.kind});
    if(newHeap){rec.release=track(lease.retainMemory(newHeap));rec.heapBacking=this.budget.registerBacking?.('wasm',rec.heap,{state:'reserved',owner:this.resourceOwner,label:'sift-worker-heap',operation,identity:rec});}
    if(workspace>inputAllowance)rec.releaseWorkspace=track(lease.retainMemory(workspace-inputAllowance));
    rec.resources=new SiftPagedResources({budget:this.budget,scheduler:this.scheduler,operation,owner:this.resourceOwner,signal:this.signal,onProgress:progress,heapBytes:rec.heap,workspaceBytes:workspace-inputAllowance+(rec.releaseInput?.bytes??0),memoryReservations:[rec.releaseWorkspace,rec.releaseInput],reservationScope,lease,preparationGate:needsGpu?this.preparationGate:null,onGpuAdmitted:()=>{rec.releasePreparation?.();rec.releasePreparation=null;}});
    const inputBytes=Object.values(message).filter(value=>ArrayBuffer.isView(value)&&value!==rec.reusableInputData).reduce((sum,value)=>sum+value.byteLength,0);if(inputBytes)await rec.resources.message({action:'backing',backingId:-1,kind:'array-buffer',bytes:inputBytes,label:'sift-tile-input'});
    if(!rec.worker){stage='init';rec.worker=new Worker(new URL('./sift-paged-worker.js',import.meta.url),{type:'module'});this.metrics.workers=Math.max(this.metrics.workers,this.records.filter(r=>r.worker).length);await this.rpc(rec,{kind:'init',wasm:this.wasm,maximumHeapBytes:rec.heap,provider:rec.provider,layers:this.layers,contrast:this.contrast});}
    stage='compute';this.metrics.executions++;const transfer=message.kind==='select'?[]:[...new Set(Object.values(message).filter(ArrayBuffer.isView).map(a=>a.buffer))],result=await this.rpc(rec,message,transfer);checkAbort(this.signal);rec.resources.lease?.release();rec.resources.lease=null;this.metrics.peakHeapBytes=Math.max(this.metrics.peakHeapBytes,result.heapBytes??0);this.metrics.gaussianProvider=rec.provider;this.metrics.pyramidBuilds+=result.pyramidBuilds??0;this.metrics.pyramidCacheHits+=result.pyramidCacheHits??0;return result;
   }catch(error){
    // A transport refusal can detach this input; retained published tiles are
    // outside the worker and are never replayed by this local retry.
    error=reservationScope.capture(error);
    // Before dispatch, no native state has changed. Keep an admitted worker's
    // pyramid and an attached scratch window; reclaim may still retire them idle.
    if(['prepare','admission'].includes(stage)&&!this.signal?.aborted){
     const keepWindow=stage==='admission'&&error.code==='MEMORY_LIMIT'&&!!rec.reusableInputData;this.finishTask(rec);
     // This window is a prerequisite of the refused admission. Evicting it
     // would make the same credit appear sufficient, then spend it again on
     // re-reading the input. Keep that extent (and an existing native heap)
     // pinned while waiting for the genuinely missing phase credit.
     if(keepWindow){rec.inputWindow.hold();rec.busy=true;rec.heapBacking?.setReclaimable(false);}
    }else this.stopRecord(rec,error);
    if(rec.provider==='webgpu'&&this.backend==='auto'&&(['GPU_UNAVAILABLE','GPU_DEVICE_LOST'].includes(error.code)||/^WebGPU (?:unavailable|device lost:)/.test(error.message??''))){this.stopRecord(rec,error);rec.provider='cpu';this.metrics.retries++;this.metrics.failures.push({provider:'webgpu',code:error.code,message:error.message});continue;}
    if(resourceAllocationKind(error)==='wasm'&&rec.heap<2048*MiB)rec.heap=Math.min(2048*MiB,rec.heap*2);
    throw error;
   }finally{reservationScope.close();}
  }},{budget:this.budget,signal:this.signal,owner:this.resourceOwner,resourceOperation:operation,operation:'sift-native-tile',phase:()=>stage,onRecovery:progress,onReclaim:progress,onWait:progress,reclaim:event=>reclaimForResourceRecovery(this.budget,event.error,{signal:this.signal,owner:this.resourceOwner,resourceOperation:operation,onReclaim:event.recordReclamation})});}
  finally{if(ownsOperation){rec.operation=null;operation?.release();}}
 }
 async run(jobs,make,accept){
  let cursor=0,failed=false;
  const work=await Promise.allSettled(this.records.map(async rec=>{while(cursor<jobs.length&&!failed){const i=cursor++,operation=this.budget.beginOperation?.({owner:this.resourceOwner,id:'sift-tile'});rec.operation=operation;
   try{const result=await this.execute(rec,hooks=>make(jobs[i],hooks));operation?.setState('io');await runWithResourceRecovery(()=>accept(result,jobs[i]),{budget:this.budget,signal:this.signal,owner:this.resourceOwner,resourceOperation:operation,operation:'sift-publish-tile',onRecovery:this.onProgress,onReclaim:this.onProgress,onWait:this.onProgress});operation?.commit();}
   catch(error){failed=true;throw error;}finally{this.finishTask(rec);rec.operation=null;operation?.release();}
  }}));
  const error=work.find(result=>result.status==='rejected')?.reason;if(error)throw error;checkAbort(this.signal);
 }
}
export class PagedSiftFeatureEngine{
 constructor(budget,profile){this.budget=budget;this.profile=profile;this.workers=new Set();this.controller=null;this.checkpoints=new Map();this.sourceIds=new WeakMap();this.sourceSequence=0;}
 stop(){this.controller?.abort();for(const r of this.workers){r.worker?.terminate();r.worker=null;r.reject?.(new EngineError('CANCELLED','Paged SIFT stopped'));r.reject=null;}}
 async retireCheckpoint(id,entry){if(entry.retiring)return entry.retiring;entry.controller.abort();entry.stop?.();entry.retiring=(async()=>{await entry.active;for(const state of entry.jobs.values())await state.dispose();for(const result of entry.results)result?.release();entry.results=[];if(this.checkpoints.get(id)===entry)this.checkpoints.delete(id);})();return entry.retiring;}
 async clearCheckpoint(key){await Promise.all([...this.checkpoints].filter(([,entry])=>key===undefined||entry.key===key).map(([id,entry])=>this.retireCheckpoint(id,entry)));}
 async dispose(){this.stop();await this.pending;await this.clearCheckpoint();}
 async extract(image,options={}){
  const {family='SIFT',regions=[],excluded=[],independent=true,reflected=false}=options,releases=[],admit=n=>{const free=this.budget.reserve(n);releases.push(free);return free;},perRegion=family==='SIFT-G2NN'&&independent;
  try{const plan=siftRegionPlan(image.width,image.height,perRegion?regions:[],excluded,{reflected,reserveMemory:admit});if(!perRegion){siftRegionPlan(image.width,image.height,regions,[],{reflected,reserveMemory:admit});plan.jobs[0].regions=regions.map(p=>p.map(([x,y])=>[reflected?image.width-1-x:x,y]));}return await this.extractPlan(image,plan,Math.max(1,regions.length),options);}finally{releases.forEach(f=>f());}
 }
 async extractPlan(image,plan,zoneCount,{family='SIFT',limit=6000,independent=true,reflected=false,backend='auto',signal,onProgress,storageContext,storage='auto',checkpointKey}={}){
  requireValue(!this.controller&&['SIFT','SIFT-G2NN','SIFT-LightGlue','Forgeryscope-SIFT'].includes(family),'Invalid or busy paged SIFT family');const controller=new AbortController(),combined=signal?AbortSignal.any([signal,controller.signal]):controller.signal;this.controller=controller;const abort=()=>this.stop();combined.addEventListener('abort',abort,{once:true});const budget=this.budget;let entry,identity;
  if(checkpointKey!==undefined){let sourceId=this.sourceIds.get(image);if(!sourceId){sourceId=++this.sourceSequence;this.sourceIds.set(image,sourceId);}const recipe=JSON.stringify([sourceId,zoneCount,family,limit,independent,backend,storage]);identity=JSON.stringify([checkpointKey,recipe,reflected,plan]);for(const [id,old] of this.checkpoints)if(id!==identity&&old.key===checkpointKey&&(old.reflected===reflected||old.recipe!==recipe))await this.retireCheckpoint(id,old);entry=this.checkpoints.get(identity);if(!entry){entry={key:checkpointKey,recipe,reflected,results:[],jobs:new Map(),controller:new AbortController()};this.checkpoints.set(identity,entry);}}
  let finish;const pending=new Promise(resolve=>{finish=resolve;});this.pending=pending;const abortEntry=()=>controller.abort();if(entry){entry.active=pending;entry.stop=abortEntry;entry.controller.signal.addEventListener('abort',abortEntry,{once:true});}const results=entry?.results??[];let completed=false,releaseFinal;
  try{
   const freeAsset=budget.reserve(SIFT_PAGED_WASM.bytes*3+64*MiB);let wasm;
   try{wasm=await fetchM3Asset(new URL('../vendor/sift-paged/sift-paged.wasm',import.meta.url),SIFT_PAGED_WASM,combined);
    for(let i=0;i<plan.jobs.length;i++){if(results[i])continue;let state=entry?.jobs.get(i);if(entry&&!state){state=createSiftCheckpoint();entry.jobs.set(i,state);}const result=await this.extractJob(image,plan.jobs[i],zoneCount,{family,limit,independent,backend,signal:combined,storageSignal:entry?.controller.signal??combined,wasm,storageContext,storage,state,onProgress:e=>onProgress?.(e.phase?.startsWith('resource-')?e:{...e,fraction:(i+e.fraction)/plan.jobs.length})});const r=plan.jobs[i].rectangle;for(let j=0;j<result.points.length;j+=7){result.points[j]+=r.x;result.points[j+1]+=r.y;}if(reflected)result.points=remapReflectedSiftPoints(result.points,image.width);results[i]=result;}
   }finally{freeAsset();}
   const count=results.reduce((s,r)=>s+r.points.length/7,0);releaseFinal=budget.reserve(count*(56+512+zoneCount)+4096);const points=new Float64Array(count*7),descriptors=new Float32Array(count*128),members=new Uint8Array(count*zoneCount);let at=0,totalFeatures=0;
   for(const r of results){points.set(r.points,at*7);descriptors.set(r.descriptors,at*128);members.set(r.members,at*zoneCount);at+=r.points.length/7;totalFeatures+=r.totalFeatures;}checkAbort(combined);const finalBytes=points.byteLength+descriptors.byteLength+members.byteLength,finalBacking=budget.registerBacking?.('array-buffer',finalBytes,{owner:family==='Forgeryscope-SIFT'?'forgeryscope':'sift',label:'sift-result'}),finalReservation=releaseFinal;let finalReleased=false,backingTransferred=false,backingReleased=false;const releaseBacking=()=>{if(backingReleased)return;backingReleased=true;finalBacking?.();budget.notifyBackingRelease?.('array-buffer',finalBytes);},transferBacking=()=>{requireValue(!backingTransferred&&!finalReleased,'SIFT output backing already released or transferred.');backingTransferred=true;return releaseBacking;};releaseFinal=()=>{if(finalReleased)return;finalReleased=true;if(!backingTransferred)releaseBacking();finalReservation();};completed=true;return {points,descriptors,members,transferBacking,reservedBytes:count*(56+512+zoneCount)+4096,descriptorSize:128,zoneCount,totalFeatures,release:releaseFinal,metadata:{provider:results.some(r=>r.metadata.stages.some(s=>s.gaussianProvider==='webgpu'))?'webgpu':'cpu',family,opencv:'4.11.0',inputLayout:'global-octave-bases',featurePolicy:family==='SIFT-G2NN'&&independent?'independent_roi_v2':'global',reflectedPixels:reflected,preflightExecutions:0,jobs:results.map(r=>r.metadata),workers:Math.max(0,...results.map(r=>r.metadata.workers)),peakWorkerHeapBytes:Math.max(0,...results.map(r=>r.metadata.peakHeapBytes)),executions:results.reduce((s,r)=>s+r.metadata.executions,0),continuationSeeds:results.reduce((s,r)=>s+r.metadata.continuationSeeds,0),continuationWindows:results.reduce((s,r)=>s+r.metadata.continuationWindows,0),pyramidBuilds:results.reduce((s,r)=>s+r.metadata.pyramidBuilds,0),pyramidCacheHits:results.reduce((s,r)=>s+r.metadata.pyramidCacheHits,0),retries:results.reduce((s,r)=>s+r.metadata.retries,0),qualification:family==='Forgeryscope-SIFT'?'qualified against dense native-profile port; cross-platform residuals documented':'qualified native arithmetic with global paged dependencies'}};
  }catch(error){checkAbort(combined);throw error;}
  finally{try{combined.removeEventListener('abort',abort);if(completed||!entry){for(const r of results)r?.release();if(entry){this.checkpoints.delete(identity);entry.results=[];for(const state of entry.jobs.values())await state.dispose();entry.controller.abort();}}if(!completed)releaseFinal?.();}finally{this.stop();this.controller=null;if(entry){entry.controller.signal.removeEventListener('abort',abortEntry);entry.stop=null;}if(this.pending===pending)this.pending=null;finish();}}
 }
 async extractJob(image,job,zoneCount,options){
  const {family,limit,independent,backend,signal,wasm,onProgress,storageContext,storage,storageSignal=signal}=options,budget=this.budget,source=researchRows(image),rectangle=job.rectangle,width=rectangle.width,height=rectangle.height,scale=family==='SIFT-G2NN'?job.scale:1,layers=['SIFT-LightGlue','Forgeryscope-SIFT'].includes(family)?4:3,contrast=family==='SIFT-G2NN'?.001:['SIFT-LightGlue','Forgeryscope-SIFT'].includes(family)?.0066667:.04,sw=width*scale,sh=height*scale,core=1024,halo=128,maximumPixels=Math.min(sw*2,core+2*halo)*Math.min(sh*2,core+2*halo),provider=backend==='cpu'?'cpu':backend==='webgpu'||globalThis.navigator?.gpu?'webgpu':'cpu';
  const state=options.state??createSiftCheckpoint(),frees=state.frees,bases=state.bases??=[],account=n=>{const free=budget.reserve(n);frees.push(free);return free;},makeStore=async(key,n)=>{let store=state.stores.get(key);if(store)return store;store=await createSegmentedBytes(n,{budget,owner:family==='Forgeryscope-SIFT'?'forgeryscope':'sift',label:'sift-'+key,storage:storage==='auto'&&n>Math.min(budget.limit/12,(budget.limit-budget.total())/4)?'temporary':storage,temporarySession:storageContext?.temporarySession??image.temporarySession,getTemporarySession:storageContext?.getTemporarySession??image.getTemporarySession,signal:storageSignal});state.stores.set(key,store);return store;},heap=roundHeap(128*MiB+maximumPixels*(2*layers+8)*4),cost=(heap,provider)=>heap+64*MiB+maximumPixels*(provider==='webgpu'?256:128),metrics=state.metrics??={sourceRows:height,sourceReads:0,globalCandidates:0,continuationSeeds:0,continuationWindows:0,octaveBases:[],preflightExecutions:0,grayScale:scale,coreSize:core,supportHalo:halo};
  let pool,postPool,grayStore,returned=false,freeResult,pages;const completedMetrics=state.completedMetrics??=[];const run=(p,label,jobs,make,accept)=>runSiftCheckpointStage(state,p,label,jobs,make,accept);
  const newPool=()=>new SiftPool(this,{budget,resourceOwner:family==='Forgeryscope-SIFT'?'forgeryscope':'sift',wasm,backend,provider,heap,cost,layers,contrast,signal,onProgress,inputBytes:maximumPixels*8});
  account.backing=(array,label)=>{const release=budget.registerBacking?.('array-buffer',array.byteLength,{owner:family==='Forgeryscope-SIFT'?'forgeryscope':'sift',label}),bytes=array.byteLength;let refs=0;const retain=()=>{refs++;let closed=false;const free=()=>{if(closed)return;closed=true;if(--refs===0){release?.();budget.notifyBackingRelease?.('array-buffer',bytes);}};free.retain=retain;return free;};const free=retain();frees.push(free);return free;};
  const recordPool=p=>{if(p)completedMetrics.push({...p.metrics});};
  async function readRect(store,w,x,y,cw,ch,Type,{allocateInput}){const output=allocateInput(Type,cw*ch);for(let r=0;r<ch;r++){if(r%64===0)checkAbort(signal);await store.readInto(byteView(output.subarray(r*cw,(r+1)*cw)),((y+r)*w+x)*Type.BYTES_PER_ELEMENT,{signal});}return output;}
  async function writeRect(store,w,rect,data){const [x,y,cw,ch]=rect;for(let r=0;r<ch;r++)await store.write(byteView(data.subarray(r*cw,(r+1)*cw)),((y+r)*w+x)*data.BYTES_PER_ELEMENT,{signal});}
  const grid=(w,h,step)=>{const jobs=[];for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step)jobs.push({x,y,cw:Math.min(step,w-x),ch:Math.min(step,h-y)});return jobs;};
  try{
   if(!state.overhead){account(32*MiB+image.width*64*8);state.overhead=true;}pool=newPool();await pool.open(Math.min(this.profile.maxWorkers,grid(sw*2,sh*2,core).length));grayStore=await makeStore('gray',width*height);let low=state.low??255,high=state.high??0;
   for(let y=state.grayRows??0;y<height;y+=64){await controlCheckpoint(signal);const rows=Math.min(64,height-y),lease=await source.readRows(rectangle.y+y,rows,{signal});metrics.sourceReads++;try{const rgb=validateRgbRows(lease,image.width,rows),output=new Uint8Array(width*rows);for(let yy=0;yy<rows;yy++)for(let x=0;x<width;x++){const sx=job.reflected?image.width-1-rectangle.x-x:rectangle.x+x,at=(yy*image.width+sx)*3,value=['SIFT-LightGlue','Forgeryscope-SIFT'].includes(family)?f(f(f(f(f(rgb[at]/255)*f(.299))+f(f(rgb[at+1]/255)*f(.587)))+f(f(rgb[at+2]/255)*f(.114)))*255):gray(rgb[at],rgb[at+1],rgb[at+2]);output[yy*width+x]=value;low=Math.min(low,output[yy*width+x]);high=Math.max(high,output[yy*width+x]);}await grayStore.write(output,y*width,{signal});state.grayRows=y+rows;state.low=low;state.high=high;}finally{lease.release();}onProgress?.({phase:'sift-gray',fraction:.04*(y+rows)/height});}
   if(scale===4){const target=await makeStore('scaled-gray',sw*sh);await run(pool,'scale',[0],async(_,{allocateInput})=>({kind:'scale',input:await readRect(grayStore,width,0,0,width,height,Uint8Array,{allocateInput}),width,height,low,high}),async r=>target.write(r.gray,0));grayStore=target;}
   let w=sw*2,h=sh*2,base=await makeStore('base:0',w*h*4),prepared=state.prepared??0;const initialJobs=grid(sw,sh,core/2);
   await run(pool,'prepare',initialJobs,async(t,{allocateInput})=>{const x0=Math.max(0,t.x-16),y0=Math.max(0,t.y-16),x1=Math.min(sw,t.x+t.cw+16),y1=Math.min(sh,t.y+t.ch+16);return {kind:'prepare',input:await readRect(grayStore,sw,x0,y0,x1-x0,y1-y0,Uint8Array,{allocateInput}),width:x1-x0,height:y1-y0,core:[(t.x-x0)*2,(t.y-y0)*2,t.cw*2,t.ch*2],normalize:family==='SIFT-G2NN'&&scale===1,low,high};},async(r,t)=>{await writeRect(base,w,[t.x*2,t.y*2,t.cw*2,t.ch*2],r.base);state.prepared=++prepared;onProgress?.({phase:'sift-initial',fraction:.04+.12*prepared/initialJobs.length});});grayStore=null;
   pages=state.pages??=new SiftPointPages(Float32Array,7,account);const octaves=roundEven(Math.log(Math.min(w,h))/Math.log(2)-2)+1;
   for(let octave=0;octave<octaves;octave++){
    base.markCold?.();const record={store:base,w,h};bases[octave]=record;metrics.octaveBases[octave]={width:w,height:h,bytes:w*h*4,storage:base.storage};const nw=Math.floor(w/2),nh=Math.floor(h/2),next=octave+1<octaves?await makeStore('base:'+(octave+1),nw*nh*4):null,tasks=grid(w,h,core);let octaveState=state.values.get('octave:'+octave);if(!octaveState){octaveState={escapes:[],detected:0,rounds:[]};state.values.set('octave:'+octave,octaveState);}const escapes=octaveState.escapes;let detected=octaveState.detected;
    await run(pool,'detect:'+octave,tasks,async(t,{allocateInput})=>{const x0=Math.max(0,t.x-halo),y0=Math.max(0,t.y-halo),x1=Math.min(w,t.x+t.cw+halo),y1=Math.min(h,t.y+t.ch+halo);return {kind:'detect',cacheKey:[state.id,octave,x0,y0,x1,y1].join(':'),input:await readRect(base,w,x0,y0,x1-x0,y1-y0,Float32Array,{allocateInput}),width:x1-x0,height:y1-y0,x0,y0,globalWidth:w,globalHeight:h,core:[t.x,t.y,t.cw,t.ch],octave};},async(r,t)=>{if(next)await writeRect(next,nw,r.nextRect,r.next);let releaseEscape;try{if(r.escapes.length)releaseEscape=r.retainOwnership('escapes');pages.append(r.points);}catch(error){releaseEscape?.();throw error;}if(r.escapes.length){frees.push(releaseEscape);escapes.push(r.escapes);}octaveState.detected=++detected;onProgress?.({phase:'sift-octave',fraction:.16+.54*(octave+detected/tasks.length)/octaves,octave,completed:detected,total:tasks.length});});
    let pending=[];for(const data of escapes)for(let i=0;i<data.length;i+=6)pending.push({state:[data[i],data[i+1],data[i+2],0]});if(!octaveState.seedsCounted){metrics.continuationSeeds+=pending.length;octaveState.seedsCounted=true;}let round=0;
    while(pending.length){
     const publication=octaveState.rounds[round]??=createSiftContinuationRound(pending.length),groups=groupSiftContinuations(pending,w,h,{canonical:true}).map((group,index)=>({...group,index}));
     await run(pool,'refine-batch:'+octave+':'+round,groups,async(group,{allocateInput})=>{const {x0,y0,x1,y1}=group;metrics.continuationWindows++;return {kind:'refine-batch',cacheKey:[state.id,octave,x0,y0,x1,y1].join(':'),input:await readRect(base,w,x0,y0,x1-x0,y1-y0,Float32Array,{allocateInput}),width:x1-x0,height:y1-y0,x0,y0,globalWidth:w,globalHeight:h,states:packSiftContinuationStates(group),octave};},async(result,group)=>acceptSiftContinuationBatch(publication,group.index,group,result,pages,frees));
     pending=publication.again;round++;
    }
    base=next;w=nw;h=nh;
   }
   metrics.globalCandidates=pages.length;const raw=state.raw??=pages.finish();recordPool(pool);pool.close();pool=null;const selectionHeap=roundHeap(raw.byteLength*5+width*height*2+128*MiB);postPool=new SiftPool(this,{budget,resourceOwner:family==='Forgeryscope-SIFT'?'forgeryscope':'sift',wasm,backend:'cpu',provider:'cpu',heap:selectionHeap,cost:heap=>heap+raw.byteLength*3+limit*(600+zoneCount)+64*MiB,layers,contrast,signal,onProgress,inputBytes:raw.byteLength});await postPool.open(1);let selected;
   await run(postPool,'select',[0],async()=>({kind:'select',points:raw,width,height,regions:job.regions,excluded:job.excluded,limit,family,scale,zoneCount,independentZone:family==='SIFT-G2NN'&&independent?job.zone:null}),async r=>{frees.push(r.retainOwnership('points','descriptorPoints','members'));state.selected=selected=r;});selected=state.selected;recordPool(postPool);postPool.close();postPool=null;onProgress?.({phase:'sift-global-ranking',fraction:.73});
   const count=selected.points.length/7;freeResult=state.freeResult??=budget.reserve(count*512+4096);const descriptors=state.descriptors??=new Float32Array(count*128),byWindow=new Map();
   if(!state.descriptorBacking)state.descriptorBacking=account.backing(descriptors,'sift-descriptors');
   for(let i=0;i<count;i++){const p=selected.descriptorPoints.subarray(i*7,i*7+7),low=p[5]&255,octave=(low<128?low:low-256)+1,scale=2**(1-octave),x=Math.floor(p[0]*scale/core)*core,y=Math.floor(p[1]*scale/core)*core,key=octave+':'+x+':'+y;let t=byWindow.get(key);if(!t){t={octave,x,y,ids:[]};byWindow.set(key,t);}t.ids.push(i);}
   const descriptionJobs=[...byWindow.values()];if(descriptionJobs.length){pool=newPool();await pool.open(Math.min(this.profile.maxWorkers,descriptionJobs.length));let described=0;
    await run(pool,'describe',descriptionJobs,async(t,{allocateInput})=>{const {store,w,h}=bases[t.octave],x0=Math.max(0,t.x-halo),y0=Math.max(0,t.y-halo),x1=Math.min(w,t.x+core+halo),y1=Math.min(h,t.y+core+halo),points=new Float32Array(t.ids.length*7);t.ids.forEach((id,i)=>points.set(selected.descriptorPoints.subarray(id*7,id*7+7),i*7));return {kind:'describe',cacheKey:[state.id,t.octave,x0,y0,x1,y1].join(':'),input:await readRect(store,w,x0,y0,x1-x0,y1-y0,Float32Array,{allocateInput}),width:x1-x0,height:y1-y0,x0,y0,points};},async(r,t)=>{t.ids.forEach((id,i)=>descriptors.set(r.descriptors.subarray(i*128,(i+1)*128),id*128));described++;onProgress?.({phase:'sift-descriptors',fraction:.73+.26*described/descriptionJobs.length});});recordPool(pool);pool.close();pool=null;
   }
   if(family==='SIFT-LightGlue'){const epsilon=f(1e-6),lanes=new Float32Array(4);for(let i=state.normalizedCount??0;i<count;i++){if(i%128===0)await controlCheckpoint(signal);let sum=0;for(let j=0;j<128;j++)sum=f(sum+descriptors[i*128+j]);sum=Math.max(sum,epsilon);lanes.fill(0);for(let j=0;j<128;j++){const d=f(Math.sqrt(Math.max(f(descriptors[i*128+j]/sum),epsilon)));descriptors[i*128+j]=d;lanes[j%4]=f(lanes[j%4]+f(d*d));}const norm=Math.max(f(Math.sqrt(f(f(f(lanes[0]+lanes[1])+lanes[2])+lanes[3]))),epsilon);for(let j=0;j<128;j++)descriptors[i*128+j]=f(descriptors[i*128+j]/norm);state.normalizedCount=i+1;}}
   checkAbort(signal);const releaseSelected=selected.retainOwnership('points','members'),releaseDescriptors=state.descriptorBacking.retain(),releasePolicy=freeResult;let released=false;const releaseResult=()=>{if(released)return;released=true;releaseSelected();releaseDescriptors();releasePolicy();};returned=true;state.freeResult=null;return {points:selected.points,descriptors,members:selected.members,totalFeatures:selected.totalFeatures,release:releaseResult,metadata:{...metrics,workers:Math.max(0,...completedMetrics.map(r=>r.workers)),peakHeapBytes:Math.max(0,...completedMetrics.map(r=>r.peakHeapBytes)),executions:completedMetrics.reduce((s,r)=>s+r.executions,0),pyramidBuilds:completedMetrics.reduce((s,r)=>s+r.pyramidBuilds,0),pyramidCacheHits:completedMetrics.reduce((s,r)=>s+r.pyramidCacheHits,0),retries:completedMetrics.reduce((s,r)=>s+r.retries,0),stages:completedMetrics}};
  }finally{pool?.close();postPool?.close();if(returned||!options.state)await state.dispose();else for(const store of state.stores.values())store.markCold?.();}
 }
}
