# Attribution and runtime dependencies

SHERLOQ browser engine: ports of the SHERLOQ native ELA, histogram, pixel rank,
bit-plane, extrema and isolated-pixel algorithms, plus new browser integration code. SHERLOQ by Guido Bartoli, GPL-3.0 (see LICENSE and upstream
https://github.com/GuidoBartoli/sherloq). Existing native improvements remain
attributed in the contribution history prepared separately. No author endorsement
is implied. This directory contains no native model checkpoint or user image.

This software is based in part on the work of the Independent JPEG Group.
libjpeg-turbo 3.0.3: https://github.com/libjpeg-turbo/libjpeg-turbo/tree/3.0.3 .
Unmodified library compiled to WebAssembly with Emscripten 4.0.15; wrapper source
is native/jpeg.c. Library license and IJG README are retained under vendor/libjpeg/.
Rebuild instructions: scripts/build-jpeg.sh. The compiler/SDK are build-only and
are not shipped. The JavaScript loader and WASM binary are generated artifacts.

Rejected evaluation codecs (MozJPEG and third-party fast-DCT wrapper) are absent
from the runtime manifest. No npm dependency is needed at runtime. Playwright is
a development test dependency, retained in package-lock.json; no browser profile
or credentials are shipped.


OpenCV and opencv_contrib 4.11.0: https://github.com/opencv/opencv/tree/4.11.0
and https://github.com/opencv/opencv_contrib/tree/4.11.0 . Apache-2.0 licenses are
retained under vendor/opencv/. Portable wrapper and numerical-reference rules
are in native/opencv.cpp; pinned build/link scripts are provided. Included codec
licenses (JPEG, PNG, TIFF, zlib) are retained beside the generated WASM module.
The compiler configuration diagnostic string has been replaced to exclude host
paths. Build options and source archive checksums remain in the build script.
Carotene reciprocal-reference constants derive from OpenCV's BSD-licensed
Carotene code; its license is retained separately. The browser executes portable
constants/arithmetic and does not load the native ARM implementation.

hash-wasm 4.12.0: https://github.com/Daninet/hash-wasm . MIT license retained in
vendor/hash-wasm/LICENSE. Its selected MD5/SHA-1/SHA-2/SHA-3 implementations are
bundled locally by esbuild 0.28.2. package-lock.json pins source package integrity.
ES module embeds its WASM payloads; it does not contact a CDN. esbuild and
Playwright remain build/test tools and are excluded from delivered runtime files.

PyWavelets 1.5.0: https://github.com/PyWavelets/pywt/tree/v1.5.0 . The unmodified
portable C common/convolution/wavelets/wt sources and filter coefficients are
compiled into vendor/pywt/pywt.wasm. MIT license retained in vendor/pywt/LICENSE.
The pinned archive SHA256 and rebuild are in scripts/build-pywt.sh; the wrapper
in native/wavelets.cpp implements the native float64 2D composition, symmetric
extension, threshold arithmetic and block medians. No Python runtime is shipped.

Frequency reference arithmetic is in native/frequency.h and native/sqrt-tables.h.
The DFT build uses the pinned OpenCV source with explicit portable FMA calls;
scripts/build-dft-reference.py records this transformation. Reciprocal/square-root
estimate tables reproduce the BSD-licensed Carotene algorithm, with its retained
license. scripts/sqrt-reference-tables.c is optional native reference generation;
shipped tables and runtime arithmetic are independent of host architecture.

The double-JPEG histogram smoothing port reproduces the symmetric correlate1d
algorithm of SciPy 1.17.1, under its BSD-3-Clause license, retained as
vendor/libjpeg/SCIPY-LICENSE.txt. The finite float64 Gaussian coefficients are
generated using pinned SciPy 1.17.1 / NumPy 1.26.4; they are numerical constants,
not model weights. The wrapper preserves the native unfused eight-pair prefix
and fused scalar tail. Runtime DCT extraction uses original JPEG coefficients
through libjpeg-turbo; jpeglib and SciPy themselves are native test oracles only.

Ghost map display uses the 256 scalar-to-RGB gray and viridis lookups from
Matplotlib 3.8.4, generated by scripts/generate-ghost-palettes.py. Matplotlib's
license is retained at vendor/libjpeg/MATPLOTLIB-LICENSE.txt. No Python or
Matplotlib runtime is shipped; native plot composition is not emulated.

ZERO (IPOL 2021/390), copyright 2018–2021 Tina Nikoukhah, Jérémy Anger and
Rafael Grompone von Gioi, is licensed **AGPL-3.0-or-later**, retained in
vendor/zero/LICENSE with original zero.c, zero.h and README. The corresponding
portable adaptation is native/zero-fast.c, its cosine constants, src/zero.js and
worker integration; build-zero.sh creates the separate zero.wasm module. ZERO
sources and rebuild instructions are included in the matching source archive.
This component's license is distinct from the GPL-3.0 framework; preserve its
license and corresponding source when integrating/distributing the module. No
claim of author endorsement or conversion of a native macOS binary is made.
ZERO's palette uses the same retained Matplotlib license and native legend colors.

Contrast port: native/contrast.h and contrast-window.h retain the native float32
histogram taper and NumPy reduction order. The stereogram implementation uses
OpenCV 4.11.0 optflowgf.cpp with generated explicit fused arithmetic and pinned
Gaussian/resize adapters; rebuild transformation is in build-farneback-reference.py.
Its original Intel/Willow Garage BSD notice is preserved in
vendor/opencv/FARNEBACK-LICENSE.txt. The portable adapters and arithmetic
shortcuts are in native/stereo.h and native/stereo-fma.h. No native binary is
loaded or redistributed as a browser module.

PRNU: pocketfft at SciPy 1.17.1's pinned submodule commit is retained under
vendor/pocketfft with Martin Reinecke's BSD-3-Clause license. The portable build
preserves native binary64 fused operations and pins image-independent sin/cos
seeds generated by scripts/generate-prnu-twiddles.py. These are numerical constants,
not camera fingerprints or learned weights. Native sources remain unchanged;
the build-only header adaptation is recorded in scripts/build-prnu-fft.py.

PRNU HDF5 import/export uses h5wasm 0.10.3 from the National Institute of
Standards and Technology (NIST), acknowledged as the source of this software.
Its unmodified ESM module, embedded HDF5 2.0.0 WASM and full NIST/HDF5 notices
are retained in vendor/h5wasm. PINNED.json records npm integrity and file hashes;
upstream CMake/Makefile and source files accompany the matching source archive.
The adapter uses a temporary in-memory filesystem; no filesystem backend, CDN
or remote service is enabled by the adapter.

Comparison metrics: Sewar's actual native 0.4.8 source (including the native
small-scale and zero-mean fixes) is retained under vendor/comparison with its
MIT license. The portable float64 2-D convolution/uniform-filter adapters follow
SciPy 1.17.1; its BSD notices are retained there. The 525 Gaussian coefficients
are deterministic numerical constants, not learned weights. Source hashes pin
the oracle instead of assuming that a package version identifies local fixes.

Butteraugli sources (Google, 2016) and SSIMULACRA sources (Cloudinary, 2017,
with the retained Rabah Mehdi / Philipp Klaus Krause notices) are included under
vendor/comparison. Apache-2.0 and embedded permissive notices are preserved.
The build adapts grayscale in-memory inputs and keeps the helper's printed-score
precision. Original helper binaries are test oracles only and are not included
or executed in the browser. Native OpenCV/Carotene reciprocal, Gaussian,
float32 mean and area-resize ordering are explicit portable adapters.

Noisesniffer: the corrected SHERLOQ CPU contract follows IPOL 2024/462.
Original functions and Apache-2.0 license are retained in vendor/noisesniffer.
DCT-II uses the same pinned pocketfft source and a separately generated seed
header for lengths 3, 5, 7, 8 and four times those lengths. NumPy 1.26.4 unstable
indirect introsort/heapsort is adapted in src/numpy-argsort.js; the upstream
sources and BSD-3-Clause license are retained in vendor/numpy-sort, including
Charles R. Harris's attribution. Binomial survival uses Boost.Math at SciPy
1.17.1's submodule commit 5e088ffe2ed0e237b9069e3a7352865283d8f196; its Boost
Software License and source headers are retained in vendor/boost-math. Their
PINNED.json files record provenance and file hashes. No model weights are used.

Median-filter features use the same pinned OpenCV4.11.0 core/imgproc libraries in
a separate bounded WASM module. Its Apache-2.0 license is copied to vendor/median.
Native feature definitions and historical display geometry follow SHERLOQ's
core/median.py. The restricted saved-model reader independently implements the
documented XGBoost numeric tree format and float32 predictor arithmetic; official
source references and native version are recorded in docs/MEDIAN.md. No XGBoost
runtime, trained checkpoint or executable serialized object is redistributed.
fixtures/median/toy-model.json is a hand-authored one-tree API test, not a detector.

JPEG-quality normalization uses Emscripten4.0.15's musl C99 fma implementation.
The upstream source and full MIT/musl copyright notice are retained under
vendor/quality. The fixed128KiB module reproduces the declared native binary64
normalization before the quality model's float32 input conversion. The shared
numeric tree reader also supports the qualified100-feature regression family;
no quality checkpoint, executable pickle or learned weights are redistributed.

Resampling Fourier uses the original NumPy1.26.4 C pocketfft source with only
Python glue removed during generation, separate from the SciPy C++ FFT adapter.
NumPy/pocketfft BSD notices, OpenCV Apache notice and musl copyright are retained
under vendor/numpy-fft and vendor/resampling. The portable float64 pyrUp follows
the qualified OpenCV arithmetic order. Its gray byte LUT is generated from
Matplotlib3.8.4, using the retained Matplotlib license; no Matplotlib runtime is
shipped. These functions do not implement the native probability EM detector.


Historical ORB copy/move uses OpenCV4.11.0 features2d/core/imgproc with the original
ORB embedded copyright/patent notice, retained in vendor/cloning/ORB-LICENSE.txt.
The build-generated ORB unit restores the qualified native angle polynomial and
makes its101 FMA call sites explicit (102 symbol references include the declaration).
Upstream source files remain unchanged. Pinned
LLVM libc++15.0.7 sorting helpers preserve the native equal-distance order; their
Apache-2.0 with LLVM exceptions license is included in vendor/cloning and their
original headers/PINNED.json in vendor/llvm-sort15. The musl fma copyright is
retained as vendor/cloning/MUSL-LICENSE.txt. The ORB module uses no trained model.

Offline BRISK gray8 INTER_AREA adaptation in experiments/cloning/brisk-area.cpp
derives from OpenCV4.11.0 resize.cpp; its full original BSD notice is retained
in the source. It is not linked into the runtime. No Apple Libm code or
coefficients are included in this distribution; see docs/BRISK-STUDY.md.

The AKAZE variant uses OpenCV4.11.0's default nonlinear diffusion and MLDB
descriptor implementation. Its original authors' notices are retained in
vendor/cloning/AKAZE-AUTHORS.txt. Gaussian/Scharr/separable-filter and float32
INTER_AREA adaptations retain the original OpenCV BSD notices in their sources
and vendor/cloning/AKAZE-FILTERS-LICENSE.txt and AKAZE-AREA-LICENSE.txt. Angle
polynomials use OpenCV's licensed implementation. No model weights are needed.
