import {createServer} from 'node:http';import {createReadStream} from 'node:fs';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {chromium,firefox,webkit} from 'playwright';
const browserKind=process.env.BROWSER??'chrome',isolated=process.env.NO_ISOLATION!=='1';
const root=fileURLToPath(new URL('../',import.meta.url)),out=path.join(root,'.build/media-browser'+(browserKind==='chrome'&&isolated?'':'-'+browserKind+(isolated?'':'-nonisolated')));await fs.mkdir(out,{recursive:true});
const server=createServer(async(req,res)=>{try{res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; worker-src 'self'; connect-src 'self'; img-src 'self' blob: data:; object-src 'none'");if(isolated){res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');}const u=new URL(req.url,'http://localhost');if(u.pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Media codec qualification</title>');return;}const file=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!file.startsWith(root))throw Error('path');const stat=await fs.stat(file);res.setHeader('Content-Length',stat.size);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.wasm')?'application/wasm':'application/octet-stream');createReadStream(file).pipe(res);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await (browserKind==='firefox'?firefox:browserKind==='webkit'?webkit:chromium).launch({...(browserKind==='chrome'?{channel:'chrome'}:{}),headless:true});const page=await browser.newPage();page.on('pageerror',e=>console.error(e.message));page.on('console',m=>{console.error(m.type()+': '+m.text());});
await page.exposeFunction('save',async(name,data)=>fs.writeFile(path.join(out,name),Buffer.from(data)));await page.exposeFunction('record',r=>console.log(JSON.stringify(r)));
await page.goto(`http://127.0.0.1:${server.address().port}/`);const proof=await page.evaluate(async()=>{
 const {mediaCodecJob}=await import('/src/media-codec-client.js'),width=257,height=193,source=new Uint8Array(width*height*3);for(let y=0;y<height;y++)for(let x=0;x<width;x++){let at=(y*width+x)*3;source[at]=Math.round(255*x/(width-1));source[at+1]=Math.round(255*y/(height-1));source[at+2]=(Math.floor(x/16)+Math.floor(y/16))%2?192:32;}
 const cases=[];
 for(const [format,chroma,lossless,threads] of [['avif','444',true,1],['avif','422',false,1],['avif','422',false,4],['avif','444',false,4],['avif','420',false,4],['webp','422',false,1],['webp','444',true,1],['heic','422',false,1],['heic','444',false,1]]){
  if(format==='heic'&&!crossOriginIsolated){let failed=false;try{await mediaCodecJob('encode',{width,height,format,quality:90,chroma,nativeBytes:256*1024**2});}catch(error){if(error.code!=='ISOLATION_REQUIRED')throw error;failed=true;}if(!failed)throw Error('HEIC must require isolation');cases.push({format,expectedError:'ISOLATION_REQUIRED'});continue;}
  await window.record({starting:format});const parts=[];let info;const started=performance.now();
  const descriptor=await mediaCodecJob('encode',{width,height,format,quality:90,chroma,lossless,threads,nativeBytes:256*1024**2},{signal:AbortSignal.timeout(60000),onProgress:e=>window.record({format,progress:e}),onRequest:(action,payload)=>{
   if(action==='source-band')return{bytes:source.slice(payload.y*width*3,(payload.y+payload.rows)*width*3)};
   if(action==='output-start'){info=payload;return {};}
   if(action==='output-chunk'){parts.push(payload.bytes);return {};}
   throw Error(action);
  }});const blob=new Blob(parts,{type:descriptor.mime});if(blob.size!==info.byteLength)throw Error('Truncated export');await window.save('fixture.'+format,Array.from(new Uint8Array(await blob.arrayBuffer())));
  await window.record({encoded:format,bytes:blob.size});const decoded=new Uint8Array(source.length);let header;const roundtrip=await mediaCodecJob('decode',{blob,name:'fixture.'+format},{signal:AbortSignal.timeout(60000),onRequest:(action,payload)=>{
   if(action==='decode-header'){header=payload;return{nativeBytes:256*1024**2};}if(action==='decoded-band'){decoded.set(payload.bytes,payload.y*width*3);return{};}throw Error(action);
  }});if(format!=='webp'&&header.chroma!==chroma)throw Error('Incorrect chroma '+format);if(header.width!==width||header.height!==height)throw Error('Dimensions changed');let error=0,max=0;for(let i=0;i<decoded.length;i++){const d=Math.abs(decoded[i]-source[i]);error+=d;max=Math.max(max,d);}const result={...descriptor,bytes:blob.size,decoded:roundtrip.provenance,meanAbsoluteError:error/decoded.length,maximumError:max,totalMs:performance.now()-started};if(lossless&&max!==0)throw Error('Lossless export changed pixels');if(result.meanAbsoluteError>8)throw Error('Unexpected colour error');cases.push(result);await window.record(result);
 }
 return{isolated:crossOriginIsolated,cases};
});proof.browser=browser.version();await fs.writeFile(path.join(out,'proof.json'),JSON.stringify(proof,null,2)+'\n');}finally{await browser?.close();await new Promise(r=>server.close(r));}
