import {copyTypedArray,wasmAllocationFailure} from './allocation.js';
import {wasmRange,closeMemoryRanges} from './memory-range.js';
import {EngineError,checkAbort,controlCheckpoint,requireValue} from './errors.js';
import {createSegmentedBytes} from './segmented-bytes.js';
export function pagedSewarPlan(width,height){const workspace=32*1024**2+width*Math.min(64,height)*8*20+width*8*40;requireValue(Number.isSafeInteger(width)&&Number.isSafeInteger(height)&&width>0&&height>0&&width*height<=0x7fffffff,'Invalid Sewar dimensions.');if(workspace>480*1024**2)throw new EngineError('MEMORY_LIMIT','Sewar complete row stencils exceed module capacity.');return {workspace};}
export async function comparisonPagedSewar(images,{budget,signal,onProgress,original=false,arithmetic='separated',temporarySession,getTemporarySession,storage='temporary'}={}){
 requireValue(['native','separated'].includes(arithmetic),'Invalid Sewar arithmetic.');const {width,height}=images[0].surface.descriptor;requireValue(images.length===2&&images.every(v=>v.surface.descriptor.width===width&&v.surface.descriptor.height===height),'Invalid Sewar pair.');const {workspace}=pagedSewarPlan(width,height),release=budget.reserve(workspace),stores=new Map(),metrics={workspace,workers:1,paged:true,reads:0,writes:0,readBytes:0,writeBytes:0,temporaryPeakBytes:0,heapBytes:0,arithmetic:original?'reference':arithmetic,preflightExecutions:0};let m,error,next=0,temporaryBytes=0;
 try{const session=temporarySession??images[0].session,getSession=getTemporarySession??images[0].ensureTemporarySession;
 const {default:create}=await import('../vendor/comparison-sewar-paged/comparison-sewar-paged.js');m=await create();let last=performance.now();
 m.checkpoint=async(phase,completed,total)=>{checkAbort(signal);if(performance.now()-last<20)return;onProgress?.({phase:'comparison-sewar-'+phase,completed,total,...metrics});await controlCheckpoint(signal);last=performance.now();};
 m.allocate=async bytes=>{checkAbort(signal);const id=next++,store=await createSegmentedBytes(bytes,{budget,storage,temporarySession:session,getTemporarySession:getSession,signal});stores.set(id,store);temporaryBytes+=bytes;metrics.temporaryPeakBytes=Math.max(metrics.temporaryPeakBytes,temporaryBytes);return id;};
 m.drop=async id=>{const store=stores.get(id);if(!store)return;temporaryBytes-=store.byteLength;await store.dispose();stores.delete(id);};
 m.transfer=async(id,offset,length,pointer,write)=>{checkAbort(signal);const bytes=wasmRange(m,pointer,length);if(write){await stores.get(id).write(bytes,offset);metrics.writes++;metrics.writeBytes+=length;}else{await stores.get(id).readInto(bytes,offset);metrics.reads++;metrics.readBytes+=length;}};
 m.source=async(side,row,pointer)=>{const part=await images[side].surface.readWindow({x:0,y:row,width,height:1},{signal});try{m.HEAPU8.set(part.pixels.data,pointer);}finally{part.release();}};
 error=m._malloc(1024);if(!error)throw wasmAllocationFailure(m,'Sewar error buffer allocation failed.',1024);const code=await m.ccall('comparison_sewar_paged','number',['number','number','number','number'],[width,height,original?1:arithmetic==='separated'?2:0,error],{async:true});if(m.ioError)throw m.ioError;if(code)throw new EngineError('NUMERIC_RANGE',m.UTF8ToString(error));checkAbort(signal);const values=copyTypedArray(m.HEAPF64.subarray(m._comparison_sewar_values()/8,m._comparison_sewar_values()/8+5),{label:'comparison-paged-sewar-output'});metrics.heapBytes=m.HEAPU8.byteLength;return {values,metrics};
 }finally{if(m){closeMemoryRanges(m);if(error)m._free(error);for(const key of ['checkpoint','allocate','drop','transfer','source'])m[key]=null;}await Promise.allSettled([...stores.values()].map(v=>v.dispose()));release();}
}
