import "../../runtime-context.js?v=0.14.5";
import {Budget} from './cache.js';
import {createReusableRgbWindow} from './reusable-rgb-window.js';
import {allocateTypedArray} from './allocation.js';
import {installWorkerMessageProtocol,workerMessageFailure} from './worker-message-protocol.js';
import {runWithWorkerTransportRecovery,QualityTransportQueue} from './worker-transport-recovery.js';
import {ElasticQualityWorkers} from './elastic-quality-workers.js';
import {scheduledWorkerCall,cancelScheduledWorkerCalls} from './scheduled-worker-call.js';
import {EngineError,checkAbort,controlCheckpoint,deserializeEngineError,serializeEngineError,isRecoverableTransportError} from './errors.js';import {rgbRecompressionPlan} from './jpeg-rgb-stream.js';import {rolledRgbSurface} from './rolled-rgb-surface.js';import {createSegmentedBytes} from './segmented-bytes.js';
export function ghostPoolShape(image,{mode='ghost',block=32}={}){const plan=rgbRecompressionPlan(image.surface),cells=Math.floor(plan.width/16)*Math.floor(plan.height/16);const cellCount=Math.floor(plan.width/block)*Math.floor(plan.height/block),descriptorBytes=mode==='cells'?64*1024**2+plan.width*Math.min(plan.height,block+16)*6+cellCount*57:0;return {...plan,cells,descriptorBytes,workerBytes:descriptorBytes+plan.workingBytes+2*plan.rowBytes*plan.rows+cells*8+256*1024};}
export async function parallelGhostPlanes(image,qualities,count,{budget,maxWorkers=count,signal,phaseX=0,phaseY=0,onPlane,onProgress,mode='ghost',block=32,workerFactory=()=>new Worker(new URL('./ghost-stream-worker.js',import.meta.url),{type:'module'})}={}){
 const admission={budget,maximum:maxWorkers,resourceOwner:'ela'};
 const shape=ghostPoolShape(image,{mode,block}),surface=rolledRgbSurface(image.surface,phaseX,phaseY,budget),states=[],ioTasks=new Set();let sourceWindow,stopped=false,maximumHeap=0,encodedPeak=0,sourcePasses=0,completed=0;const encodedStorage=new Set();const metrics=()=>({workers:lanes.snapshot().peakWorkers,elastic:lanes.snapshot(),kernel:mode==='cells'?'global-rgb-jpeg-ela-cell-worker-pool':'global-rgb-jpeg-ghost-worker-pool',recompressions:completed,transportRecoveries:jobs.recoveries,qualityPlanesComputed:completed,codecHeapCapacityBytes:maximumHeap,codecHeapMaximumBytes:shape.heapMaximumBytes,totalCodecHeapMaximumBytes:lanes.snapshot().peakWorkers*shape.heapMaximumBytes,maxSourceWindowBytes:shape.rows*shape.rowBytes,sourcePasses,encodedStorage:encodedStorage.size>1?'mixed':[...encodedStorage][0]??null,maximumEncodedBytes:encodedPeak});
 function rejectState(state,error){state.pending?.reject(error);state.pending=null;}
 function stop(){if(stopped)return;stopped=true;cancelScheduledWorkerCalls(admission);for(const state of states){state.protocol?.dispose();state.worker.onmessage=null;state.worker.terminate();rejectState(state,new EngineError('CANCELLED','Ghost quality workers stopped.'));}}
 const rpc=(state,data)=>scheduledWorkerCall(admission,()=>new Promise((resolve,reject)=>{state.pending={resolve,reject,action:data.action};try{checkAbort(signal);if(stopped)throw new EngineError('CANCELLED','Ghost quality workers stopped.');if(state.protocol.failed)throw state.protocol.error;state.protocol.post(data);}catch(error){state.pending=null;reject(error);}}),{signal,label:'ghost-stream-pool',domains:data.action==='init'?{wasm:shape.heapMaximumBytes+(mode==='cells'?64*1024**2:0)}:data.bytes?{'array-buffer':data.bytes.byteLength}:{}});
 async function handleIo(state,data){
  // The lane already owns this bounded storage allowance in workingBytes.
  // Keep it valid across live decreases of the global admission budget.
  const reserve=bytes=>(state.ioBudget??=new Budget(8*1024**2)).reserve(bytes);
  try{checkAbort(signal);let bytes;if(data.io==='write'){if(state.written+data.bytes.length>shape.encodedCapacityBytes)throw new EngineError('MEMORY_LIMIT','Ghost JPEG exceeded its conservative capacity.');await state.store.write(data.bytes,state.written,{reserve});state.written+=data.bytes.length;}
   else{const length=Math.min(data.length,state.written-state.readOffset);bytes=allocateTypedArray(Uint8Array,length,{label:'ghost-jpeg-read',operation});await state.store.readInto(bytes,state.readOffset,{reserve});state.readOffset+=length;}
   if(!stopped&&!state.protocol.failed)state.protocol.post({ioReply:true,id:data.id,bytes},bytes?[bytes.buffer]:[]);
  }catch(error){if(!stopped&&!state.protocol.failed)try{state.protocol.post({ioReply:true,id:data.id,error:serializeEngineError(error,'WORKER_FAILED')});}catch(failure){state.protocol.fail(failure);}}
 }
 const create=(state={pending:null,store:null,written:0,readOffset:0,ioTasks:new Set()})=>{state.worker=workerFactory();state.protocol=installWorkerMessageProtocol(state.worker,data=>{
    if(data.io){if(!Number.isSafeInteger(data.id)||!(['write','read'].includes(data.io))||(data.io==='read'?!Number.isSafeInteger(data.length)||data.length<0:!(data.bytes instanceof Uint8Array)))throw workerMessageFailure('ghost-stream-parent','message','invalid-io-envelope');const task=handleIo(state,data);ioTasks.add(task);state.ioTasks.add(task);const done=()=>{ioTasks.delete(task);state.ioTasks.delete(task);};task.then(done,done);return;}
    const pending=state.pending;if(!pending)return;if(data.error){state.pending=null;pending.reject(deserializeEngineError(data.error));}else{if(!data.result||typeof data.result!=='object'||!Number.isSafeInteger(data.result.heapBytes)||data.result.heapBytes<=0||(mode==='ghost'&&pending.action==='blocks'&&!(data.result.blocks instanceof Float64Array)))throw workerMessageFailure('ghost-stream-parent','message','invalid-result-envelope');if(state.heapBacking){if(data.result.heapBytes<state.nativeBytes)budget.notifyBackingRelease?.('wasm',state.nativeBytes-data.result.heapBytes);state.nativeBytes=data.result.heapBytes;state.heapBacking.materialize(state.nativeBytes);}maximumHeap=Math.max(maximumHeap,data.result.heapBytes);state.pending=null;pending.resolve(data.result);}
   },{label:'ghost-stream-parent',onFailure:error=>{state.worker.terminate();rejectState(state,error);}});state.worker.onerror=event=>state.protocol.fail(new EngineError('WORKER_FAILED',event.message??'Ghost quality worker failed.'));return state;};
 const initialize=state=>{const releaseHeap=state.releaseHeap;state.nativeBytes=0;state.heapBacking=budget.registerBacking?.('wasm',shape.heapMaximumBytes+(mode==='cells'?64*1024**2:0),{owner:'ela',label:'jpeg-quality-worker',state:'reserved'});state.releaseHeap=()=>{state.heapBacking?.();state.heapBacking=null;if(state.nativeBytes)budget.notifyBackingRelease?.('wasm',state.nativeBytes);state.nativeBytes=0;releaseHeap();};return runWithWorkerTransportRecovery(async({attempt})=>{if(attempt>1)create(state);try{return await rpc(state,{action:'init',width:shape.width,height:shape.height,heapBytes:shape.heapMaximumBytes,mode,block,descriptorBytes:shape.descriptorBytes});}catch(error){if(isRecoverableTransportError(error)){state.worker.terminate();state.protocol.dispose();}throw error;}},{budget,signal,owner:'ela',operation:'ghost-stream-init'});};
 const lanes=new ElasticQualityWorkers({budget,maxWorkers,workerBytes:shape.workerBytes,windowBytes:0,states,create,initialize,signal});
 const jobs=new QualityTransportQueue(qualities,{budget,signal,label:'ghost-quality',discard:async state=>{state.worker.terminate();state.protocol.dispose();await Promise.allSettled([...state.ioTasks]);lanes.retire(state);await state.store?.dispose();state.store=null;},onRecovery:onProgress});
 const operation=budget.beginOperation?.({owner:'ela',id:'ghost-stream-pool'});admission.resourceOperation=operation;
 signal?.addEventListener('abort',stop,{once:true});
 try{
  checkAbort(signal);sourceWindow=await createReusableRgbWindow(surface,{budget,rows:shape.rows,bytes:shape.windowAllowance,signal,operation});
  while(jobs.pending.length){
   const first=completed,active=await lanes.take(jobs.pending.length,{operation}),batch=jobs.assign(active),planes=new Map((mode==='ghost'?active:[]).map(state=>{if(!state.plane){state.plane=allocateTypedArray(Float64Array,shape.cells,{label:'ghost-worker-quality-plane',operation});const unregister=budget.registerBacking?.('array-buffer',state.plane.byteLength,{owner:'ela',label:'ghost-worker-quality-plane',operation}),free=state.releaseHeap;state.releaseHeap=()=>{state.plane=null;unregister?.();free();budget.notifyBackingRelease?.('array-buffer',shape.cells*8);};}return [state,state.plane];}));
   for(const state of active){const fits=shape.encodedCapacityBytes+shape.windowAllowance<=budget.limit-budget.retained-budget.active;state.store=await createSegmentedBytes(shape.encodedCapacityBytes,{budget,storage:fits?'memory':'temporary',temporarySession:image.session,getTemporarySession:image.ensureTemporarySession,signal});state.written=0;state.readOffset=0;encodedStorage.add(state.store.storage);}
   await jobs.call(active,s=>rpc(s,{action:'open',quality:s.qualityJob.quality}));
   for(let pass=0;pass<2&&active.length;pass++){
    if(pass)await jobs.call(active,s=>rpc(s,{action:'begin-read'}));sourcePasses++;
    for(let y=0;y<shape.height&&active.length;y+=shape.rows){operation?.setState('io');await controlCheckpoint(signal);const rows=Math.min(shape.rows,shape.height-y),part=await sourceWindow.read({x:0,y,width:shape.width,height:rows});try{const outputs=await jobs.call(active,s=>rpc(s,{action:pass?'blocks':'write',bytes:part.pixels.data,y}));if(pass&&mode==='ghost')for(const state of active)planes.get(state).set(outputs.get(state).blocks,(y/16)*Math.floor(shape.width/16));}finally{part.release();}checkAbort(signal);onProgress?.({phase:pass?'ghost-workers-render':'ghost-workers-encode',fraction:(first+batch.length*(pass+(y+rows)/shape.height)/2)/qualities.length,qualities:batch});}
   }
   let closingFailure;for(const state of active)state.qualityClosed=false;try{await jobs.call(active,async state=>{const result=await rpc(state,{action:'close'});state.cellResult=result.cell;state.qualityClosed=true;return result;});}catch(error){closingFailure=error;}checkAbort(signal);
   for(const state of active)if(state.qualityClosed){await state.store.flush();await image.rgbRecompression.retainEncoded(state.qualityJob.quality,{store:state.store,byteLength:state.written},{phaseX,phaseY});state.store=null;encodedPeak=Math.max(encodedPeak,state.written);await onPlane?.(state.qualityJob.quality,mode==='cells'?state.cellResult:planes.get(state));state.cellResult=null;completed++;operation?.commit();checkAbort(signal);}
   if(closingFailure)throw closingFailure;
   lanes.finish(active);
  }
  return metrics();
 }catch(error){error.ghostPoolMetrics=metrics();throw error;
 }finally{signal?.removeEventListener('abort',stop);stop();await Promise.allSettled([...ioTasks]);try{await Promise.all(states.map(s=>s.store?.dispose()));}finally{lanes.dispose();sourceWindow?.dispose();operation?.release();}}
}
