import "../../runtime-context.js?v=0.14.5";
// Generated by scripts/generate-prnu-twiddles.py.
export const PRNU_TWIDDLES={"bytes": 5916728, "sha256": "6ea04149284b8570d089557529464dabb14f5e99f071aac6d339fa3eeaa4db18", "maximumLength": 2097152};
