import {AKAZE_PAGED_WASM,AKAZE_PAGED_REFERENCE_WASM} from './akaze-paged-assets.js';
import {AkazePagedPool} from './akaze-paged-pool.js';
import {fetchM3Asset} from './m3-asset.js';
import {createAkazeField} from './akaze-paged-store.js';
import {TypedPages} from './m3-typed-pages.js';
import {researchRows} from './m3-research-rows.js';
import {validateRgbRows} from './rgb-row-source.js';
import {gray} from './pixel-utils.js';
import {EngineError,requireValue,checkAbort,controlCheckpoint} from './errors.js';
const MiB=1024**2,bytes=a=>new Uint8Array(a.buffer,a.byteOffset,a.byteLength),heapBound=n=>Math.min(2*1024**3,Math.ceil(n/(64*MiB))*64*MiB);

export class PagedAkazeFeatureEngine{
 constructor(budget,profile){this.budget=budget;this.resourceOwner='sift';this.profile=profile;this.workers=new Set();this.controller=null;}
 stop(){this.controller?.abort();for(const r of this.workers){r.worker?.terminate();r.worker=null;r.reject?.(new EngineError('CANCELLED','Paged AKAZE stopped'));r.reject=null;}}
 dispose(){this.stop();}
 async extract(image,{limit=6000,regions=[],excluded=[],historical=false,mask=null,signal,onProgress,storageContext,storage='auto',coreSize=1024,stripRows=128,reference=false}={}){
  requireValue(!this.controller&&Number.isInteger(coreSize)&&coreSize>=32&&Number.isInteger(stripRows)&&stripRows>0,'Invalid or busy paged AKAZE request');
  const controller=new AbortController(),combined=signal?AbortSignal.any([signal,controller.signal]):controller.signal;this.controller=controller;const abort=()=>this.stop();combined.addEventListener('abort',abort,{once:true});
  const budget=this.budget,width=image.width,height=image.height,zoneCount=Math.max(1,regions.length),stores=new Set(),frees=[],levels=[],account=n=>{const free=budget.reserve(n);frees.push(free);return free;},makeStore=async(w,h,Type)=>{const store=await createAkazeField(w,h,Type,{coreSize,budget,storage,temporarySession:storageContext?.temporarySession??image.temporarySession,getTemporarySession:storageContext?.getTemporarySession??image.getTemporarySession,signal:combined});stores.add(store);return store;},discard=async store=>{if(stores.delete(store))await store.dispose();},metrics={family:'AKAZE',provider:'cpu',inputLayout:'global-paged-diffusion',preflightExecutions:0,globalCandidates:0,sourceReads:0,coreSize,stripRows,levels:[],stages:[],spills:[]};
  let pool,pages,releaseResult,returned=false;const heap=256*MiB,maxPixels=Math.min(width,coreSize+256)*Math.min(height,coreSize+256),cost=h=>h+64*MiB+maxPixels*48;
  const grid=(w,h)=>{const jobs=[];for(let y=0;y<h;y+=coreSize)for(let x=0;x<w;x+=coreSize)jobs.push({x,y,cw:Math.min(coreSize,w-x),ch:Math.min(coreSize,h-y)});return jobs;};
  const read=async(store,w,x,y,cw,ch,Type)=>store.readWindow(x,y,cw,ch);
  const write=async(store,w,x,y,cw,ch,data)=>store.writeWindow(x,y,cw,ch,data);
  const window=async(store,w,h,t,halo,Type)=>{const x0=Math.max(0,t.x-halo),y0=Math.max(0,t.y-halo),x1=Math.min(w,t.x+t.cw+halo),y1=Math.min(h,t.y+t.ch+halo);return {input:await read(store,w,x0,y0,x1-x0,y1-y0,Type),width:x1-x0,height:y1-y0,originX:x0,originY:y0,core:[t.x-x0,t.y-y0,t.cw,t.ch]};};
  const makeRoom=async n=>{for(;;){try{budget.room(n);return;}catch(error){if(error.code!=='MEMORY_LIMIT')throw error;const candidate=[...stores].filter(s=>s.storage==='memory').sort((a,b)=>b.byteLength-a.byteLength)[0];if(!candidate)throw error;const start=performance.now();await candidate.spill();metrics.spills.push({bytes:candidate.byteLength,milliseconds:performance.now()-start,reason:'useful-stage-admission'});}}};
  const report=(phase,fraction,extra={})=>onProgress?.({phase,fraction,...extra});
  try{
   // Controller scratch includes the bounded 4 MiB RAM-to-OPFS transfer.
   account(AKAZE_PAGED_WASM.bytes*3+64*MiB+width*(stripRows+256)*24);let wasm=await fetchM3Asset(new URL('../vendor/akaze-paged/akaze-paged.wasm',import.meta.url),AKAZE_PAGED_WASM,combined);reference=reference||!WebAssembly.validate(wasm);if(reference)wasm=await fetchM3Asset(new URL('../vendor/akaze-paged/reference.wasm',import.meta.url),AKAZE_PAGED_REFERENCE_WASM,combined);metrics.arithmetic=reference?'scalar-reference':'relaxed-simd-fma';const newPool=h=>new AkazePagedPool(this,{budget,wasm,reference,width,height,signal:combined,heap:h,cost});
   pool=newPool(heap);await pool.open(Math.min(this.profile.maxWorkers,grid(width,height).length));const config=await pool.initialize(pool.records[0]);
   for(let i=0;i<config.length;i+=10)levels.push({level:i/10,w:config[i],h:config[i+1],radius:config[i+6],ratio:config[i+7],halo:Math.max(128,config[i+9]+4*config[i+6]+8)});
   const grayStore=await makeStore(width,height,Uint8Array),source=image.grayscale?null:researchRows(image);
   for(let y=0;y<height;y+=64){await controlCheckpoint(combined);const count=Math.min(64,height-y);if(image.grayscale){await grayStore.write(image.data.subarray(y*width,(y+count)*width),y*width);}else{const lease=await source.readRows(y,count,{signal:combined});try{const rgb=validateRgbRows(lease,width,count),out=new Uint8Array(width*count);for(let i=0;i<out.length;i++)out[i]=gray(rgb[i*3],rgb[i*3+1],rgb[i*3+2]);await grayStore.write(out,y*width);}finally{lease.release();}}metrics.sourceReads++;report('akaze-gray',.03*(y+count)/height);}
   let base=await makeStore(width,height,Float32Array);const magnitude=await makeStore(width,height,Float32Array),initialJobs=grid(width,height);let completed=0,maximum=0;
   await pool.run(initialJobs,async t=>({kind:'prepare',...await window(grayStore,width,height,t,8,Uint8Array)}),async(r,t)=>{await write(base,width,t.x,t.y,t.cw,t.ch,r.base);await write(magnitude,width,t.x,t.y,t.cw,t.ch,r.magnitude);for(let yy=0;yy<t.ch;yy++)if(t.y+yy>0&&t.y+yy<height-1)for(let x=0;x<t.cw;x++)if(t.x+x>0&&t.x+x<width-1)maximum=Math.max(maximum,r.magnitude[yy*t.cw+x]);report('akaze-initial',.03+.07*++completed/initialJobs.length);});await discard(grayStore);
   let contrast=.03;const histogram=new Int32Array(300),histJobs=[];for(let y=1;y<height-1;y+=128)histJobs.push({y,rows:Math.min(128,height-1-y)});
   if(maximum>0&&levels.length>1){completed=0;await pool.run(histJobs,async t=>({kind:'histogram',input:await read(magnitude,width,1,t.y,width-2,t.rows,Float32Array),maximum}),async r=>{for(let i=0;i<300;i++)histogram[i]+=r.histogram[i];report('akaze-contrast',.1+.02*++completed/histJobs.length);});contrast=(await pool.execute(pool.records[0],()=>({kind:'contrast',histogram:histogram.slice(),count:(width-2)*(height-2),maximum}))).contrast;}await discard(magnitude);
   for(const level of levels){
    const previous=levels[level.level-1];let resized=false;
    if(previous&&previous.w!==level.w){base=await makeStore(level.w,level.h,Float32Array);const jobs=[];for(let y=0;y<level.h;y+=stripRows)jobs.push({y,count:Math.min(stripRows,level.h-y)});
     await pool.run(jobs,async t=>{const sy=1/(level.h/previous.h),y0=Math.max(0,Math.floor(t.y*sy)-1),y1=Math.min(previous.h,Math.ceil((t.y+t.count)*sy)+1);return {kind:'resize',input:await read(previous.lt,previous.w,0,y0,previous.w,y1-y0,Float32Array),width:previous.w,rows:y1-y0,fullHeight:previous.h,sourceY:y0,targetWidth:level.w,targetHeight:level.h,targetY:t.y,count:t.count};},async(r,t)=>base.write(bytes(r.base),t.y*level.w*4));contrast=Math.fround(contrast*.75);resized=true;
    }else if(previous)base=previous.lt;
    level.lt=level.level?await makeStore(level.w,level.h,Float32Array):base;level.smooth=level.level?await makeStore(level.w,level.h,Float32Array):base;level.det=await makeStore(level.w,level.h,Float32Array);const jobs=grid(level.w,level.h);completed=0;
    await pool.run(jobs,async t=>({kind:'evolve',...await window(base,level.w,level.h,t,level.halo,Float32Array),level:level.level,contrast}),async(r,t)=>{if(level.level){await write(level.lt,level.w,t.x,t.y,t.cw,t.ch,r.lt);await write(level.smooth,level.w,t.x,t.y,t.cw,t.ch,r.smooth);}await write(level.det,level.w,t.x,t.y,t.cw,t.ch,r.det);report('akaze-evolution',.12+.46*(level.level+ ++completed/jobs.length)/levels.length,{level:level.level});});if(resized)await discard(base);
    metrics.levels.push({width:level.w,height:level.h,contrast,halo:level.halo,ltStorage:level.lt.storage,smoothStorage:level.smooth.storage,detStorage:level.det.storage});
   }
   // Native suppression depends on prior rows and prior levels. Persist each
   // mutation before its next dependent read; no independent-window NMS.
   for(const l of levels){l.mask=await makeStore(l.w,l.h,Uint8Array);for(let y=0;y<l.h;y+=stripRows){const count=Math.min(stripRows,l.h-y),y0=Math.max(0,y-l.radius-1),y1=Math.min(l.h,y+count+l.radius+1),r=await pool.execute(pool.records[0],async()=>({kind:'same',det:await read(l.det,l.w,0,y0,l.w,y1-y0,Float32Array),mask:await read(l.mask,l.w,0,y0,l.w,y1-y0,Uint8Array),width:l.w,rows:y1-y0,originY:y0,fullHeight:l.h,level:l.level,startY:y,count}));await l.mask.write(r.mask,y0*l.w);}report('akaze-same-scale',.58+.06*(l.level+1)/levels.length);}
   for(const direction of [-1,1]){const indices=direction<0?Array.from({length:levels.length-1},(_,i)=>i+1):Array.from({length:levels.length-1},(_,i)=>levels.length-2-i);let completed=0;
    for(const index of indices){const l=levels[index],target=levels[index+direction],ratio=direction<0?l.ratio/target.ratio:target.ratio/l.ratio,radius=direction<0?l.radius*ratio:target.radius;
     for(let y=0;y<l.h;y+=stripRows){const count=Math.min(stripRows,l.h-y),y0=Math.max(0,(direction<0?y*ratio:Math.floor(y/ratio))-radius),y1=Math.min(target.h,(direction<0?(y+count-1)*ratio:Math.floor((y+count-1)/ratio))+radius+1),r=await pool.execute(pool.records[0],async()=>({kind:'cross',det:await read(l.det,l.w,0,y,l.w,count,Float32Array),mask:await read(l.mask,l.w,0,y,l.w,count,Uint8Array),width:l.w,rows:count,originY:y,targetDet:await read(target.det,target.w,0,y0,target.w,y1-y0,Float32Array),targetMask:await read(target.mask,target.w,0,y0,target.w,y1-y0,Uint8Array),targetWidth:target.w,targetRows:y1-y0,targetY:y0,level:index,direction,startY:y,count}));await target.mask.write(r.mask,y0*target.w);}
     report('akaze-cross-scale',.64+(direction<0?0:.05)+.05*++completed/indices.length);
    }
   }
   pages=new TypedPages(Float32Array,7,account);for(const l of levels){for(let y=0;y<l.h;y+=stripRows){const count=Math.min(stripRows,l.h-y),y0=Math.max(0,y-1),y1=Math.min(l.h,y+count+1),r=await pool.execute(pool.records[0],async()=>({kind:'refine',det:await read(l.det,l.w,0,y0,l.w,y1-y0,Float32Array),mask:await read(l.mask,l.w,0,y0,l.w,y1-y0,Uint8Array),width:l.w,rows:y1-y0,originY:y0,level:l.level,startY:y,count}));await makeRoom(r.points.byteLength+2*MiB);pages.append(r.points);}await discard(l.det);await discard(l.mask);report('akaze-refinement',.74+.05*(l.level+1)/levels.length);}
   await makeRoom(pages.length*28);const raw=pages.finish();metrics.globalCandidates=raw.length/7;metrics.stages.push({...pool.metrics});pool.close();const selectionHeap=heapBound(raw.byteLength*5+width*height+64*MiB);await makeRoom(cost(selectionHeap));pool=newPool(selectionHeap);await pool.open(1);
   const selected=await pool.execute(pool.records[0],()=>({kind:'select',points:raw.slice(),mask:mask?.slice(),width,height,regions,excluded,zoneCount,limit,historical}));account(selected.points.byteLength+selected.members.byteLength);metrics.stages.push({...pool.metrics});pool.close();pool=null;
   const count=selected.points.length/7;await makeRoom(count*(56+61+zoneCount)+4096+cost(heap)*Math.min(this.profile.maxWorkers,Math.max(1,count)));releaseResult=budget.reserve(count*(56+61+zoneCount)+4096);const points=new Float64Array(count*7),descriptors=new Uint8Array(count*61),members=selected.members.slice();report('akaze-global-selection',.8);
   pool=newPool(heap);await pool.open(Math.min(this.profile.maxWorkers,Math.max(1,count)));let described=0;
   for(const l of levels){const jobs=new Map();for(let i=0;i<count;i++)if(selected.points[i*7+6]===l.level){const x=Math.floor(selected.points[i*7]/l.ratio/coreSize)*coreSize,y=Math.floor(selected.points[i*7+1]/l.ratio/coreSize)*coreSize,key=x+':'+y;if(!jobs.has(key))jobs.set(key,{x,y,cw:Math.min(coreSize,l.w-x),ch:Math.min(coreSize,l.h-y),ids:[]});jobs.get(key).ids.push(i);}
    await pool.run([...jobs.values()],async t=>{const view=await window(l.smooth,l.w,l.h,t,128,Float32Array),points=new Float32Array(t.ids.length*7);t.ids.forEach((id,i)=>points.set(selected.points.subarray(id*7,id*7+7),i*7));return {kind:'describe',smooth:view.input,lt:await read(l.lt,l.w,view.originX,view.originY,view.width,view.height,Float32Array),width:view.width,height:view.height,originX:view.originX,originY:view.originY,level:l.level,points};},async(r,t)=>{t.ids.forEach((id,i)=>{points.set(r.points.subarray(i*7,i*7+7),id*7);descriptors.set(r.descriptors.subarray(i*61,(i+1)*61),id*61);});described+=t.ids.length;report('akaze-descriptors',.8+.2*described/Math.max(1,count));});await discard(l.lt);await discard(l.smooth);
   }
   metrics.stages.push({...pool.metrics});metrics.workers=Math.max(...metrics.stages.map(s=>s.workers));metrics.peakWorkerHeapBytes=Math.max(...metrics.stages.map(s=>s.peakWorkerHeapBytes));metrics.executions=metrics.stages.reduce((n,s)=>n+s.executions,0);metrics.retries=metrics.stages.reduce((n,s)=>n+s.retries,0);checkAbort(combined);report('akaze-complete',1);returned=true;return {points,descriptors,members,descriptorSize:61,zoneCount,totalFeatures:selected.totalFeatures,metadata:metrics,release:releaseResult};
  }catch(error){checkAbort(combined);throw error;}
  finally{combined.removeEventListener('abort',abort);pool?.close();pages?.dispose();try{for(const store of stores)await store.dispose();}finally{for(const free of frees)free();if(!returned)releaseResult?.();this.stop();this.controller=null;}}
 }
}
