import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs/promises';
import {Budget} from '../src/cache.js';import {samplePixels,sampleSurface,displayGeometry} from '../src/display-sampling.js';import {EngineError,requireValue,checkAbort,serializeEngineError} from '../src/errors.js';
const code=(await fs.readFile(new URL('../src/m2-worker-host.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace('export function createM2WorkerHost','function createM2WorkerHost');
for(const segmented of [false,true])test('M2 sampled display has one reply, bounded reads and deterministic result ownership: '+segmented,async()=>{
 let windows=0,renders=0,released=0,fail=false;const pixels={width:37,height:29,format:'rgb8',data:Uint8Array.from({length:37*29*3},(_,i)=>i%251)},messages=[];
 const api={analyze:async()=>({data:{width:37,height:29,segmented},release(){released++;}}),render:async()=>{renders++;return {...pixels,data:pixels.data.slice(),release(){}};},renderWindow:async(_im,_result,_view,rect)=>{windows++;if(fail)throw Error('render fault');const data=new Uint8Array(rect.width*rect.height*3);for(let y=0;y<rect.height;y++)data.set(pixels.data.subarray(((rect.y+y)*37+rect.x)*3,((rect.y+y)*37+rect.x+rect.width)*3),y*rect.width*3);return {width:rect.width,height:rect.height,data,release(){}};},clearCache(){},dispose(){}};
 const context=vm.createContext({Budget,samplePixels,sampleSurface,displayGeometry,EngineError,requireValue,checkAbort,serializeEngineError,AbortController,Uint8Array,Float32Array,Float64Array,ArrayBuffer,TextEncoder,structuredClone,Blob,resolveComputeProfile:()=>({}),createCatnetAnalyzer:()=>api,createCfaAnalyzer:()=>api,createCompositeAnalyzer:()=>api,createTruforAnalyzer:()=>api,createForgeryscopeAnalyzer:()=>api});vm.runInContext(code,context);const host=context.createM2WorkerHost({post:m=>messages.push(m)});let serial=0;const call=async(operation,args={})=>{const id=++serial;await host.handle({id,operation,args});const message=messages.find(m=>m.id===id);if(message.error)throw Object.assign(Error(message.error.message),message.error);return message.value;};
 await call('initialize',{memoryBudgetBytes:8*1024**2,methods:{catnet:{}}});const result=await call('analyze',{method:'catnet',image:pixels});const before=(await call('memory')).activeReservationBytes,tile={x:2,y:3,w:31,h:21,step:4},frame=await call('readDisplay',{resultId:result.id,view:1,tile}),expected=await samplePixels(pixels,tile);
 assert.deepEqual(frame.pixels.data,expected.pixels.data);expected.release();assert.equal(renders,segmented?0:1);assert.equal(windows,segmented?6:0);assert.equal((await call('memory')).activeReservationBytes,before);
 if(segmented){fail=true;await assert.rejects(call('readDisplay',{resultId:result.id,view:1,tile}),/render fault/);assert.equal((await call('memory')).activeReservationBytes,before);}
 await call('releaseResult',{resultId:result.id});assert.equal(released,1);assert.equal((await call('memory')).activeReservationBytes,0);await call('dispose');
});
