import "../../runtime-context.js?v=0.14.5";
import {EngineError,requireValue,controlCheckpoint,checkAbort} from './errors.js';
import {resamplingFourierParams,resamplingFourierGeometry} from './resampling-fourier.js';
import {resamplingStreamMath,resamplingStreamHeapBytes} from './resampling-stream-math.js';
import {ResamplingStripPool} from './resampling-strip-pool.js';import {segmentedResamplingFft} from './segmented-resampling-fft.js';
import {createSegmentedBytes} from './segmented-bytes.js';import {createFloatPlane} from './segmented-float-plane.js';
import {createMaskSurface,createRgbSurface} from './rgb-surface.js';import {createNoiseTable} from './noise-table.js';import {retainResult} from './retained-result.js';
import {inspectJpegBlob} from './jpeg.js';import {decodeJpegGrayRows} from './jpeg-gray-rows.js';import {shiftedComplex} from './frequency-shift.js';import {GRAY_PALETTE} from './gray-palette.js';
const semantics='Native source-region Fourier evidence on global binary64 axes. Frequency-grid values and preview are not resampling probabilities or an authenticity decision.';
const clearDisplay=async value=>{if(value)await Promise.all([value.rgb.dispose(),value.table.dispose()]);};
function result(cache,metrics){return {surface:cache.display.rgb.lease(),tableRecords:{magnitude:{surface:cache.magnitude.table.lease()},values:{surface:cache.display.table.lease()}},resamplingCache:cache,data:{minimumMagnitude:cache.magnitude.low,maximumMagnitude:cache.magnitude.high,geometry:structuredClone(cache.magnitude.geometry),grayNormalization:{...cache.normalization}},semantics:cache.semantics??semantics,metrics};}
export async function segmentedResamplingFourier(image,params,{budget,signal,onProgress,cache,blockPixels=65536,storage='auto',profile={}}={}){
 const grayCached=!!cache,p=resamplingFourierParams(params),{width:sw,height:sh}=image.surface.descriptor,g=resamplingFourierGeometry(sw,sh,p),displayKey=JSON.stringify(p);checkAbort(signal);
 if(cache?.display?.key===displayKey)return result(cache,{workers:0,preflightExecutions:0,grayCached:true,spectrumCached:true,magnitudeCached:true,displayCached:true});
 requireValue(image.source||image.floatSource,'Original encoded JPEG or qualified binary64 source is required.');requireValue(g.fftSide<=16384,'Resampling FFT exceeds the qualified axis limit.');requireValue(Number.isSafeInteger(blockPixels)&&blockPixels>0&&blockPixels<=262144,'Invalid resampling strip size.');
 const heap=Math.max(12*1024**2,resamplingStreamHeapBytes()),room=budget.limit-budget.retained-budget.active,block=Math.min(blockPixels,Math.floor((room-heap-4*1024**2)/128));if(block<g.fftSide*4)throw new EngineError('MEMORY_LIMIT','A full Fourier axis and pyrUp halo must fit.');
 const options={budget,signal,storage:storage==='auto'&&(image.session||image.ensureTemporarySession)&&sw*sh+g.fftSide*g.fftSide*80>room-heap-block*128?'temporary':storage,temporarySession:image.session,getTemporarySession:image.ensureTemporarySession,chunkBytes:Math.max(8192,block*8)},pool=new ResamplingStripPool(budget,{...profile,adaptive:image.resamplingScheduling??=new Map()}),owned=new Set(),views=[];
 const work=async fn=>{const release=budget.reserve(heap+block*128);try{return await fn();}finally{release();}},progress=(phase,completed,total)=>onProgress?.({phase,completed,total}),plane=async(w,h)=>{const v=await createFloatPlane(w,h,options);owned.add(v);return v;},drop=async v=>{if(owned.delete(v))await v.dispose();};let newCache,graySurface;
 try{
  const math=await work(()=>resamplingStreamMath());
  if(!cache&&image.floatSource){
   const source=image.floatSource;let disposed=false;cache=newCache={gray:{async readWindow({x,y,width,height},hooks){return {pixels:{data:await source.read(x,y,width,height,hooks)},release(){}};},dispose(){}},normalization:{minimum:0,maximum:1,scope:'supplied native binary64 field; no renormalization'},semantics:'Fourier evidence from a native EM probability map or its selected composite; not an authenticity decision.',async dispose(){if(disposed)return;disposed=true;await Promise.all([this.spectrum?.plane.dispose(),this.magnitude?.table.dispose(),clearDisplay(this.display)]);}};
  }
  if(!cache){
   const header=await inspectJpegBlob(image.source,{signal}),store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight,options);try{await decodeJpegGrayRows(image.source,header,store,{budget,signal,chunkBytes:Math.max(header.sourceWidth,block),onProgress:f=>progress('resampling-file-gray',f,1)});graySurface=createMaskSurface(store,{width:header.sourceWidth,height:header.sourceHeight,orientation:header.orientation,budget,range:[0,255],semantics:'Original JPEG grayscale'});}catch(error){await store.dispose();throw error;}
   requireValue(graySurface.descriptor.width===sw&&graySurface.descriptor.height===sh,'Native grayscale dimensions differ.');let low=255,high=0;
   await work(async()=>{const step=Math.max(1,Math.floor(block/sw));for(let y=0;y<sh;y+=step){await controlCheckpoint(signal);const part=await graySurface.readWindow({x:0,y,width:sw,height:Math.min(step,sh-y)},{signal});try{for(const v of part.pixels.data){low=Math.min(low,v);high=Math.max(high,v);}}finally{part.release();}progress('resampling-gray-extrema',Math.min(sh,y+step),sh);}});
   let disposed=false;cache=newCache={gray:graySurface,normalization:{minimum:low,maximum:high,scope:'whole decoded original grayscale image'},async dispose(){if(disposed)return;disposed=true;await Promise.all([this.gray.dispose(),this.spectrum?.plane.dispose(),this.magnitude?.table.dispose(),clearDisplay(this.display)]);}};graySurface=null;
  }
  const spectrumKey=JSON.stringify([g.selected,p.window,p.upsample]),spectrumCached=cache.spectrum?.key===spectrumKey;let spectrum=cache.spectrum;
  if(!spectrumCached){const side=g.spatialSide,[left,top]=g.spatialSquare,step=Math.max(1,Math.floor(block/side)),low=cache.normalization.minimum,span=cache.normalization.maximum-low;let input=await plane(side,side);
   await work(async()=>{const hann=p.window==='hanning'?Float64Array.from({length:side},(_,i)=>.5+.5*Math.cos(Math.PI*(1-side+2*i)/(side-1))):null,center=Math.floor(side/2),radius=Math.sqrt(2*center*center),root2=Math.sqrt(2);
    for(let y=0;y<side;y+=step){await controlCheckpoint(signal);const h=Math.min(step,side-y),part=await cache.gray.readWindow({x:left,y:top+y,width:side,height:h},{signal});try{const values=new Float64Array(side*h);for(let yy=0;yy<h;yy++)for(let x=0;x<side;x++){const r=hann?0:Math.sqrt((y+yy-center)**2+(x-center)**2)/radius*root2,weight=hann?hann[y+yy]*hann[x]:(r<.75?1:r<=root2?.5+.5*Math.cos(Math.PI*(r-.75)/(root2-.75)):0);values[yy*side+x]=(span?(part.pixels.data[yy*side+x]-low)/span:0)*weight;}await input.write(values,0,y,side,h,{signal});}finally{part.release();}progress('resampling-window',Math.min(side,y+step),side);}
   });
   if(p.upsample){const up=await plane(side*2,side*2),upRows=Math.max(1,Math.floor(block/(side*4))-2);await work(async()=>{let completed=0;await pool.run({count:Math.ceil(side/upRows),pixels:side*Math.min(side,upRows+2)*4,key:`resampling-pyrup/${side}/${upRows}`,signal,
    prepare:async i=>{await controlCheckpoint(signal);const y=i*upRows,h=Math.min(upRows,side-y),top=Math.max(0,y-1),bottom=Math.min(side,y+h+1);return {op:'pyrup',values:await input.read(0,top,side,bottom-top,{signal}),width:side,height:bottom-top};},local:j=>({values:math.pyrup(j.values,j.width,j.height)}),consume:async(r,i)=>{const y=i*upRows,h=Math.min(upRows,side-y),top=Math.max(0,y-1);await up.write(r.values.subarray((y-top)*4*side,(y-top+h)*4*side),0,y*2,side*2,h*2,{signal});completed+=h;progress('resampling-pyrup',completed,side);}
   });});await drop(input);input=up;}
   const fft=await segmentedResamplingFft(input,{...options,blockPixels:block,pool,onProgress});owned.add(fft);await drop(input);spectrum={key:spectrumKey,plane:fft};
  }
  const magnitudeKey=JSON.stringify([spectrumKey,p.center,p.highpass]),magnitudeCached=cache.magnitude?.key===magnitudeKey;let magnitude=cache.magnitude;
  if(!magnitudeCached){const side=g.outputSide,size=g.fftSide,offset=g.fftOffset,step=Math.max(1,Math.floor(block/side)),values=await plane(side,side),shifted=shiftedComplex(spectrum.plane),radius=Math.max(1,Math.trunc(.1*(side/2))),center=Math.floor(side/2),radialRadius=Math.sqrt(2*center*center),root2=Math.sqrt(2);let low=Infinity,high=-Infinity;
   await work(async()=>{for(let y=0;y<side;y+=step){await controlCheckpoint(signal);const h=Math.min(step,side-y),raw=await shifted.read(offset,y+offset,side,h,{signal}),v=new Float64Array(side*h);for(let yy=0;yy<h;yy++)for(let x=0;x<side;x++){const r=p.highpass==='radial'?Math.sqrt((y+yy-center)**2+(x-center)**2)/radialRadius*root2:0,weight=p.highpass==='radial'?(r<=root2?.5-.5*Math.cos(Math.PI*r/root2):0):(Math.sqrt((x-side/2)**2+(y+yy-side/2)**2)<=radius?0:1),i=yy*side+x,value=Math.hypot(raw[i*2]*weight,raw[i*2+1]*weight);requireValue(Number.isFinite(value),'Non-finite Fourier magnitude.');v[i]=value;low=Math.min(low,value);high=Math.max(high,value);}await values.write(v,0,y,side,h,{signal});progress('resampling-magnitude',Math.min(side,y+step),side);}});
   magnitude={key:magnitudeKey,plane:values,table:retainResult(createNoiseTable(values,{budget,block:1,columns:['frequency_y','frequency_x','magnitude'],coordinates:'frequency'})),low,high,geometry:g};
  }
  const side=magnitude.geometry.outputSide,step=Math.max(1,Math.floor(block/side)),values=await plane(side,side),rgb=await createSegmentedBytes(side*side*3,options);let rgbSurface;
  try{await work(async()=>{for(let y=0;y<side;y+=step){await controlCheckpoint(signal);const h=Math.min(step,side-y),v=await magnitude.plane.read(0,y,side,h,{signal}),pixels=new Uint8Array(v.length*3);for(let i=0;i<v.length;i++){v[i]=Math.pow(magnitude.high>magnitude.low?(v[i]-magnitude.low)/(magnitude.high-magnitude.low):0,p.gamma)*(p.rescale?magnitude.high:1);pixels.fill(GRAY_PALETTE[Math.max(0,Math.min(255,Math.floor(v[i]*256)))],i*3,i*3+3);}await values.write(v,0,y,side,h,{signal});await rgb.write(pixels,y*side*3);progress('resampling-view',Math.min(side,y+step),side);}});await rgb.flush();rgbSurface=createRgbSurface(rgb,{width:side,height:side,budget});views.push(rgbSurface);}catch(error){await rgb.dispose();throw error;}
  checkAbort(signal);const oldDisplay=cache.display;cache.display=null;await clearDisplay(oldDisplay);if(!magnitudeCached){const previous=cache.magnitude;cache.magnitude=null;await previous?.table.dispose();cache.magnitude=magnitude;owned.delete(magnitude.plane);}if(!spectrumCached){const previous=cache.spectrum;cache.spectrum=null;await previous?.plane.dispose();cache.spectrum=spectrum;owned.delete(spectrum.plane);}
  cache.display={key:displayKey,rgb:retainResult(rgbSurface),table:retainResult(createNoiseTable(values,{budget,block:1,columns:['frequency_y','frequency_x','value'],coordinates:'frequency'}))};owned.delete(values);views.length=0;newCache=null;
  return result(cache,{...pool.metrics(),grayCached,spectrumCached,magnitudeCached,displayCached:false});
 }catch(error){await newCache?.dispose();throw error;}finally{pool.clear();await graySurface?.dispose();await Promise.all([...owned].map(v=>v.dispose()));await Promise.all(views.map(v=>v.dispose()));}
}
