import "../../runtime-context.js?v=0.14.5";
// Generated by scripts/build-m3-ort-runtime.py.
export const M3_ORT_ASSETS=Object.freeze({"cpu":{"path":"../vendor/d2prl/ort-wasm-simd-threaded.wasm","bytes":14239897,"sha256":"3398c10d07d229bd91b364548e130e0e51a8e5704b88c7c083ebbeb78842dee2"},"gpu":{"path":"../vendor/m3-ort/ort-wasm-simd-threaded.asyncify.wasm","bytes":26781914,"sha256":"39f9f0894d478800487ed9f7dbe92618498db320cf55c8e3d89adff8dce658da"}});
