import "../../runtime-context.js?v=0.14.5";
import {requireValue,controlCheckpoint} from './errors.js';import {inspectJpegBlob} from './jpeg.js';import {decodeJpegGrayRows} from './jpeg-gray-rows.js';import {createSegmentedBytes} from './segmented-bytes.js';import {createMaskSurface} from './rgb-surface.js';
export async function createResamplingGray(image,{budget,signal,onProgress,storage='auto',decodeGray}={}){
 const {width,height}=image.surface.descriptor,options={budget,signal,storage,temporarySession:image.session,getTemporarySession:image.ensureTemporarySession,chunkBytes:262144};let store,surface;
 try{
  if(image.source){const header=await inspectJpegBlob(image.source,{signal});store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight,options);await decodeJpegGrayRows(image.source,header,store,{budget,signal,chunkBytes:Math.max(header.sourceWidth,32768),onProgress:f=>onProgress?.({phase:'em-original-gray',completed:f,total:1})});surface=createMaskSurface(store,{width:header.sourceWidth,height:header.sourceHeight,orientation:header.orientation,budget,range:[0,255],semantics:'Original native grayscale'});}
  else{requireValue(typeof decodeGray==='function'&&image.bytes,'Original grayscale decoder is required.');const release=budget.reserve(width*height*16+32*1024**2);try{const gray=await decodeGray(image.bytes,{signal});requireValue(gray.width===width&&gray.height===height,'Native grayscale dimensions differ.');store=await createSegmentedBytes(width*height,options);await store.write(gray.data);surface=createMaskSurface(store,{width,height,budget,range:[0,255],semantics:'Original native grayscale'});}finally{release();}}
  requireValue(surface.descriptor.width===width&&surface.descriptor.height===height,'Native grayscale dimensions differ.');const rows=Math.max(1,Math.floor(32768/width));let minimum=255,maximum=0;
  for(let y=0;y<height;y+=rows){await controlCheckpoint(signal);const part=await surface.readWindow({x:0,y,width,height:Math.min(rows,height-y)},{signal});try{for(const v of part.pixels.data){minimum=Math.min(minimum,v);maximum=Math.max(maximum,v);}}finally{part.release();}onProgress?.({phase:'em-gray-extrema',completed:Math.min(height,y+rows),total:height});}
  const graySurface=surface;surface=null;store=null;return {width,height,normalization:{minimum,maximum,scope:'whole decoded original grayscale image'},async read(x,y,w,h,{signal}={}){const part=await graySurface.readWindow({x,y,width:w,height:h},{signal});try{const span=maximum-minimum;return Float64Array.from(part.pixels.data,v=>span?(v-minimum)/span:0);}finally{part.release();}},dispose:()=>graySurface.dispose()};
 }catch(error){if(surface)await surface.dispose();else await store?.dispose();throw error;}
}
