import {chromium,firefox,webkit} from 'playwright';import {createServer} from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const runtimeRoot=process.argv.find(a=>a.startsWith('--runtime-root='))?.slice('--runtime-root='.length);
const localMedianModel=process.argv.find(a=>a.startsWith('--median-model='))?.slice('--median-model='.length);
const localQualityModel=process.argv.find(a=>a.startsWith('--quality-model='))?.slice('--quality-model='.length);
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.json':'application/json','.jpg':'image/jpeg'};
const server=createServer(async(req,res)=>{try{if(req.url==='/__local_quality_model__'&&localQualityModel){const data=await readFile(localQualityModel);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(data);return;}if(req.url==='/__local_median_model__'&&localMedianModel){const data=await readFile(localMedianModel);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(data);return;}const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!p.startsWith(root)){res.writeHead(403);res.end();return;}const relative=path.relative(root,p),asset=runtimeRoot&&/^(src|vendor|experiments\/d2prl)\//.test(relative)?path.resolve(runtimeRoot,relative):p;const data=await readFile(asset);res.writeHead(200,{'Content-Type':types[path.extname(p)]??'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;
let browser;try{
 const browserName=process.argv.find(a=>a.startsWith('--browser='))?.split('=')[1]??'chrome';const launcher={chrome:chromium,firefox,webkit}[browserName];if(!launcher)throw new Error('Unknown browser');browser=await launcher.launch(browserName==='chrome'?{channel:'chrome',headless:true}:{headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${port}/tests/browser.html`);await page.waitForFunction(()=>!!window.runBrowserTests);
 const result=await page.evaluate(()=>window.runBrowserTests());
 if(process.argv.includes('--auto-zones-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/auto-zones-benchmark.js')).autoZonesBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/auto-zones-chrome-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({autoZonesBenchmark:proof.cases.map(x=>({name:x.name,summary:x.summary}))}));}
 if(process.argv.includes('--auto-zones')){const proof=await page.evaluate(async()=>(await import('/tests/auto-zones-browser.js')).autoZonesBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/auto-zones-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({autoZones:{status:proof.status,cases:proof.cases,peakBytes:proof.cleanup.peakAccountedBytes}}));}
 if(process.argv.includes('--akaze-fma-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/cloning/akaze-fma-benchmark.js')).akazeFmaBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/akaze-fma-chrome-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({akazeFma:proof.cases.map(x=>({name:x.name,softwareMedianMs:x.softwareMedianMs,candidateMedianMs:x.candidateMedianMs,speedup:x.speedup}))}));}
 if(process.argv.includes('--akaze-stress')){const proof=await page.evaluate(async()=>(await import('/tests/akaze-stress-browser.js')).akazeStressBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/akaze-stress-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({akazeStress:proof}));}
 if(process.argv.includes('--akaze-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/cloning/pipeline-benchmark.js')).cloningPipelineBenchmark('AKAZE'));proof.browser=browser.version();await writeFile(path.join(root,'docs/akaze-chrome-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({akazeBenchmark:proof.cases.map(x=>({name:x.name,summary:x.summary}))}));}
 if(process.argv.includes('--akaze')||process.argv.includes('--akaze-large')){const large=process.argv.includes('--akaze-large'),cpuKernel=process.argv.includes('--akaze-single')?'single':'auto';const proof=await page.evaluate(async ({large,cpuKernel})=>(await import('/tests/cloning-browser.js')).cloningBrowserTest(large,cpuKernel,'AKAZE'),{large,cpuKernel});proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/akaze-'+(cpuKernel==='auto'?'parallel-':'')+(large?'large-':'')+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({akaze:{large,cases:proof.cases,peakBytes:Math.max(...proof.records.map(x=>x.metrics.memory.peakAccountedBytes))}}));}
 if(process.argv.includes('--cloning')||process.argv.includes('--cloning-large')){const large=process.argv.includes('--cloning-large'),cpuKernel=process.argv.includes('--cloning-parallel')?'auto':'single';const proof=await page.evaluate(async ({large,cpuKernel})=>(await import('/tests/cloning-browser.js')).cloningBrowserTest(large,cpuKernel),{large,cpuKernel});proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/cloning-'+(cpuKernel==='auto'?'parallel-':'')+(large?'large-':'')+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({cloning:{large,cases:proof.cases,peakBytes:Math.max(...proof.records.map(x=>x.metrics.memory.peakAccountedBytes))}}));}
 if(process.argv.includes('--cloning-pool')){const proof=await page.evaluate(async()=>(await import('/tests/cloning-pool-browser.js')).cloningPoolBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/cloning-pool-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({cloningPool:proof}));}
 if(process.argv.includes('--cloning-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/cloning/pipeline-benchmark.js')).cloningPipelineBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/cloning-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({cloningBenchmark:proof.cases.map(x=>({name:x.name,summary:x.summary}))}));}
 if(process.argv.includes('--cloning-kernel-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/cloning/kernel-benchmark.js')).cloningKernelBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/cloning-kernel-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({cloningKernels:{matching:proof.matching.map(x=>({name:x.name,radius:x.radius,speedup:x.speedup})),geometry:proof.geometry.map(x=>({image:x.image,matches:x.rawMatches,speedup:x.speedup}))}}));}
 if(process.argv.includes('--cloning-study')){const proof=await page.evaluate(async()=>(await import('/experiments/cloning/browser.js')).cloningStudyBrowser());proof.browser=browser.version();await writeFile(path.join(root,'docs/cloning-study-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({cloningStudy:{detectors:proof.detectorCases,selection:proof.selectionCases,matching:proof.matchingCases,pipelines:proof.pipelineCases}}));}
 if(process.argv.includes('--resampling-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/resampling-benchmark.js')).resamplingBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/resampling-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({resamplingBenchmark:proof.summary}));}
 if(process.argv.includes('--resampling-view-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/resampling-view-benchmark.js')).resamplingViewBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/resampling-view-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({resamplingViewBenchmark:proof.records.map(x=>({side:x.side,serial:x.medianSerialMs,parallel:x.medianParallelMs,speedup:x.speedup}))}));}
 if(process.argv.includes('--resampling-parallel')){const proof=await page.evaluate(async()=>(await import('/tests/resampling-large-browser.js')).resamplingLargeBrowserTest('auto'));proof.pool=await page.evaluate(async()=>(await import('/tests/resampling-pool-browser.js')).resamplingPoolBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/resampling-parallel-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({resamplingParallel:proof.cases.map(x=>({maxScaled:x.maxScaled,differingBytes:x.differingBytes,workers:x.metrics.fourierViewWorkers,rpcMs:x.rpcMs}))}));}
 if(process.argv.includes('--resampling-large')){const proof=await page.evaluate(async()=>(await import('/tests/resampling-large-browser.js')).resamplingLargeBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/resampling-large-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({resamplingLarge:proof.cases.map(x=>({maxAbsolute:x.maxAbsolute,maxScaled:x.maxScaled,differingBytes:x.differingBytes,rpcMs:x.rpcMs}))}));}
 if(process.argv.includes('--resampling')){const proof=await page.evaluate(async()=>(await import('/tests/resampling-browser.js')).resamplingBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/resampling-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({resampling:{status:proof.status,kernels:proof.kernels.summary,images:proof.images.length}}));}
 if(process.argv.includes('--quality-model-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/quality-model-benchmark.js')).qualityModelBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/quality-model-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({qualityModelBenchmark:proof.summary}));}
 if(process.argv.includes('--quality-model-test')){const proof=await page.evaluate(async()=>(await import('/tests/quality-model-browser.js')).qualityModelBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/quality-model-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({qualityModel:{status:proof.status,images:proof.images.length,normalizedSamples:proof.normalizedSamples}}));}
 if(process.argv.includes('--median-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/median-benchmark.js')).medianBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/median-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({medianBenchmark:proof.summary}));}
 if(process.argv.includes('--median')){const proof=await page.evaluate(async()=>(await import('/tests/median-browser.js')).medianBrowserTest());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/median-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({median:{status:proof.status,renders:proof.renders,maxProbabilityError:proof.maxProbabilityError,workers:proof.images.map(x=>x.first.metrics.workers)}}));}
 if(process.argv.includes('--runtime-smoke')){const proof=await page.evaluate(()=>window.runtimeSmoke());proof.browser=browser.version();proof.extractedRuntime=!!runtimeRoot;await writeFile(path.join(root,'docs/runtime-smoke-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({runtimeSmoke:proof}));}
 if(process.argv.includes('--comparison-kernel-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/comparison-kernel-benchmark.js')).comparisonKernelBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/comparison-kernel-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({comparisonKernels:proof.experiments.map(x=>({name:x.name,medianMs:x.medianMs}))}));}
 if(process.argv.includes('--comparison-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/comparison-benchmark.js')).comparisonBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/comparison-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({comparisonBenchmark:{medianRpcMs:proof.medianRpcMs,coldRpcMs:proof.cold.rpcMs}}));}
 if(process.argv.includes('--prnu-memory')){const proof=await page.evaluate(async()=>(await import('/experiments/prnu-memory.js')).prnuMemoryTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/prnu-memory-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({prnuMemory:proof}));}
 if(process.argv.includes('--prnu-kernel-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/prnu-kernel-benchmark.js')).prnuKernelBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/prnu-kernel-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({prnuKernels:proof}));}
 if(process.argv.includes('--prnu-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/prnu-benchmark.js')).prnuBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/prnu-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({prnuBenchmark:{medianRpcMs:proof.medianRpcMs,coldRpcMs:proof.cold.rpcMs}}));}
 if(process.argv.includes('--immediate-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/immediate-benchmark.js')).immediateBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/immediate-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({immediate:proof.results.map(x=>({operation:x.operation,medianFirstUsefulRpcMs:x.medianFirstUsefulRpcMs}))}));}
 if(process.argv.includes('--immediate-noisesniffer-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/noisesniffer-benchmark.js')).noisesnifferBenchmark({cpuKernel:'auto'}));proof.browser=browser.version();proof.version='0.13.0-dev';proof.firstUse='Fresh engine, no profile storage, no preflight, no separate warm-up; first complete useful RPC included';await writeFile(path.join(root,'docs/noisesniffer-immediate-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({noisesnifferImmediate:proof.results.map(x=>({block:x.block,coldRpcMs:x.cold.rpcMs,medianRpcMs:x.medianRpcMs,workers:x.cold.metrics.workers,scheduling:x.cold.metrics.scheduling}))}));}
 if(process.argv.includes('--noisesniffer-pool-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/noisesniffer-benchmark.js')).noisesnifferBenchmark({cpuKernel:'auto'}));proof.browser=browser.version();await writeFile(path.join(root,'docs/noisesniffer-pool-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({noisesnifferPool:proof.results.map(x=>({block:x.block,medianRpcMs:x.medianRpcMs,cold:x.cold.rpcMs,workers:x.samples[0].metrics.workers}))}));}
 if(process.argv.includes('--noisesniffer-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/noisesniffer-benchmark.js')).noisesnifferBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/noisesniffer-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({noisesnifferBenchmark:proof.results.map(x=>({block:x.block,medianRpcMs:x.medianRpcMs}))}));}
 if(process.argv.includes('--segmented-defects')){const proof=await page.evaluate(async()=>(await import('/tests/segmented-defects-browser.js')).segmentedDefectsBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/segmented-defects-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({segmentedDefects:proof}));}
 if(process.argv.includes('--candidate-storage')){const proof=await page.evaluate(async()=>(await import('/tests/candidate-storage-browser.js')).candidateStorageBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/candidate-storage-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({candidateStorage:proof}));}
 if(process.argv.includes('--idb-page-cache-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/idb-page-cache-benchmark.js')).idbPageCacheBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/idb-page-cache-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({idbPageCache:proof}));}
 if(process.argv.includes('--window-read-benchmark')){const proof=await page.evaluate(async()=>(await import('/experiments/window-read-benchmark.js')).windowReadBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/window-read-'+browserName+'-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({windowReads:proof}));}
 if(process.argv.includes('--source-byte-operations')){const proof=await page.evaluate(async()=>(await import('/tests/source-byte-operations-browser.js')).sourceByteOperationsBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/source-byte-operations-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({sourceByteOperations:proof}));}
 if(process.argv.includes('--lazy-result-storage')){const proof=await page.evaluate(async()=>(await import('/tests/lazy-result-storage-browser.js')).lazyResultStorageBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/lazy-result-storage-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({lazyResultStorage:proof}));}
 if(process.argv.includes('--segmented-minmax')){const proof=await page.evaluate(async()=>(await import('/tests/segmented-minmax-browser.js')).segmentedMinmaxBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/segmented-minmax-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({segmentedMinmax:proof}));}
 if(process.argv.includes('--segmented-planes')){const proof=await page.evaluate(async()=>(await import('/tests/segmented-planes-browser.js')).segmentedPlanesBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/segmented-planes-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({segmentedPlanes:proof}));}
 if(process.argv.includes('--segmented-results')){const proof=await page.evaluate(async()=>(await import('/tests/segmented-results-browser.js')).segmentedResultsBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/segmented-results-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({segmentedResults:proof}));}
 if(process.argv.includes('--source-api')){const proof=await page.evaluate(async()=>(await import('/tests/source-api-browser.js')).sourceApiBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/source-api-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({sourceApi:proof}));}
 if(process.argv.includes('--jpeg-rows')){const proof=await page.evaluate(async()=>(await import('/tests/jpeg-rows-browser.js')).jpegRowsBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/jpeg-rows-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({jpegRows:proof}));}
 if(process.argv.includes('--temporary-storage')){const proof=await page.evaluate(async()=>(await import('/tests/temporary-storage-browser.js')).temporaryStorageBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/temporary-storage-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({temporaryStorage:proof}));}
 if(process.argv.includes('--noisesniffer-large')){const proof=await page.evaluate(async()=>(await import('/tests/noisesniffer-large-browser.js')).noisesnifferLargeBrowser());proof.browser=browser.version();await writeFile(path.join(root,'docs/noisesniffer-large-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({noisesnifferLarge:proof}));}
 if(process.argv.includes('--noisesniffer')){const proof=await page.evaluate(async()=>(await import('/tests/noisesniffer-browser.js')).noisesnifferBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/noisesniffer-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({noisesniffer:proof}));}
 if(process.argv.includes('--prnu')){const proof=await page.evaluate(async()=>(await import('/tests/prnu-browser.js')).prnuBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/prnu-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({prnu:proof}));}
 if(process.argv.includes('--comparison')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/comparison-browser.js')).comparisonBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/comparison-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({comparison:proof}));}
 if(process.argv.includes('--contrast')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/contrast-browser.js')).contrastBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/contrast-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({contrast:proof}));}
 if(process.argv.includes('--stereo')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/stereogram-browser.js')).stereoBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/stereo-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({stereo:proof}));}
 if(process.argv.includes('--contrast-stereo-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/contrast-stereo-benchmark.js')).contrastStereoBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/contrast-stereo-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({benchmark:proof.results.map(r=>({operation:r.operation,medianRpcMs:r.medianRpcMs}))}));}
 if(process.argv.includes('--extended')){const proof=await page.evaluate(()=>window.runExtendedBrowserTests());proof.browser=browser.version();proof.errors=errors;await writeFile(path.join(root,'docs/extended-browser-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({extended:proof.status,counts:proof.counts}));}
 if(process.argv.includes('--quality-pool-test')){const proof=await page.evaluate(()=>window.qualityPoolBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/quality-pool-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({qualityPoolTest:proof.status,workers:proof.workers}));}
 if(process.argv.includes('--quality-pool')){const proof=await page.evaluate(()=>window.qualityPoolBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/quality-pool-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({qualityPool:proof}));}
 if(process.argv.includes('--frequency-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/frequency-benchmark.js')).frequencyBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/frequency-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({frequencyBenchmark:proof.results.map(x=>({backend:x.backend,medianRunRpcMs:x.medianRunRpcMs,medianPipelineMs:x.medianPipelineMs}))}));}
 if(process.argv.includes('--frequency-lifecycle')){const proof=await page.evaluate(async()=>(await import('/tests/frequency-gpu-lifecycle.js')).frequencyGpuLifecycle());proof.browser=browser.version();await writeFile(path.join(root,'docs/frequency-lifecycle-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({frequencyLifecycle:proof}));}
 if(process.argv.includes('--zero-memory')){const proof=await page.evaluate(async()=>(await import('/experiments/zero-memory.js')).zeroMemoryTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/zero-memory-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({zeroMemory:proof}));}
 if(process.argv.includes('--zero-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/zero-benchmark.js')).zeroBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/zero-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({zeroBenchmark:proof.large.map(x=>({cpuKernel:x.cpuKernel,medianRpcMs:x.medianRpcMs}))}));}
 if(process.argv.includes('--zero')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/zero-browser.js')).zeroBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/zero-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({zero:{status:proof.status,cases:proof.cases,views:proof.views,error:proof.maxSignificanceError,workers:proof.largeMetrics.workers}}));}
 if(process.argv.includes('--ghost-benchmark')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/ghost-benchmark.js')).ghostBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/ghost-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({ghostBenchmark:proof.results.map(x=>({cpuKernel:x.cpuKernel,samples:x.samples.map(s=>({rpcMs:s.rpcMs,workers:s.metrics.workers}))}))}));}
 if(process.argv.includes('--ghost')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/ghost-browser.js')).ghostBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/ghost-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({ghost:{status:proof.status,maps:proof.maps,previews:proof.previewPlanes,large:proof.large.length}}));}
 if(process.argv.includes('--double-jpeg')){const proof=await page.evaluate(async()=>(await import('/tests/double-jpeg-browser.js')).doubleJpegBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/double-jpeg-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({doubleJpeg:proof}));}
 if(process.argv.includes('--frequency')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/tests/frequency-browser.js')).frequencyBrowserTest());proof.browser=browser.version();await writeFile(path.join(root,'docs/frequency-'+browserName+'-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({frequency:proof}));}
 if(process.argv.includes('--frequency-gpu')){page.on('console',msg=>console.log(msg.text()));const proof=await page.evaluate(async()=>(await import('/experiments/frequency-gpu-check.js')).frequencyGpuCheck());proof.browser=browser.version();await writeFile(path.join(root,'docs/frequency-gpu-'+browserName+'-experiment.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({frequencyGpu:{masks:proof.masks.length,views:proof.views.length,mismatches:proof.mismatches.length}}));}
 if(process.argv.includes('--interactive')){const proof=await page.evaluate(()=>window.interactiveBenchmark());proof.browser=browser.version();await writeFile(path.join(root,'docs/interactive-benchmark.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({interactive:proof.results.map(r=>({operation:r.operation,coldMs:r.coldMs,cachedMs:r.changedCachedMedianMs,uncachedMs:r.changedUncachedMs}))}));}
 if(process.argv.includes('--pixels')){const proof=await page.evaluate(()=>window.runPixelBrowserTests());proof.browser=browser.version();proof.errors=errors;await writeFile(path.join(root,'docs/pixel-browser-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify({pixels:proof.status,outputs:proof.totalOutputs}));}
 if(process.argv.includes('--pixel-smoke')){const proof=await page.evaluate(()=>window.runPixelSmokeMeasurements());proof.browser=browser.version();await writeFile(path.join(root,'docs/pixel-smoke-measurements.json'),JSON.stringify(proof,null,2)+'\n');}
 if(process.argv.includes('--benchmark')){const bench=await page.evaluate(()=>window.runBenchmark());bench.browser=browser.version();await writeFile(path.join(root,'docs/kernel-benchmark.json'),JSON.stringify(bench,null,2)+'\n');}
 if(process.argv.includes('--pipeline')){const bench=await page.evaluate(()=>window.runPipelineBenchmark());bench.browser=browser.version();await writeFile(path.join(root,'docs/pipeline-benchmark.json'),JSON.stringify(bench,null,2)+'\n');}
 if(process.argv.includes('--pools')){const bench=await page.evaluate(()=>window.runPoolBenchmark());bench.browser=browser.version();await writeFile(path.join(root,'docs/pool-benchmark.json'),JSON.stringify(bench,null,2)+'\n');}
 result.browser=browser.version();result.errors=errors;
 if(errors.length)throw new Error(errors.join('\n'));
 await writeFile(path.join(root,browserName==='chrome'?'docs/browser-proof.json':'docs/browser-'+browserName+'-proof.json'),JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify({status:result.status,browser:result.browser,exact:result.exact,cancellation:result.cancellation}));
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
