"""Pin ORT 1.30 CPU/GPU runtime; expose and cap actual linear memory per worker.
Only the memory maximum changes. Numerical WASM and JS graph kernels are upstream.
No inference, calibration or external model download is part of this builder.
"""
from pathlib import Path
import hashlib,json,shutil,argparse
root=Path(__file__).resolve().parents[1];p=argparse.ArgumentParser();p.add_argument('--package',type=Path,default=root.parent/'web-engine/.build/ort130/package');a=p.parse_args();assert json.loads((a.package/'package.json').read_text())['version']=='1.30.0'
out=root/'vendor/m3-ort';out.mkdir(exist_ok=True);dist=a.package/'dist';original='new WebAssembly.Memory({initial:256,maximum:65536,shared:!0})';pins={}
for suffix in ['', '.asyncify']:
 name='ort-wasm-simd-threaded'+suffix+'.mjs';s=(dist/name).read_text();assert s.count(original)==1
 s=s.replace(original,'new WebAssembly.Memory({initial:256,maximum:globalThis.__m3MaximumWasmPages,shared:!0})');(out/name).write_text(s)
 (out/('factory'+suffix+'.mjs')).write_text("import create from './"+name+"';\nlet instance;\nexport function heapBytes(){return instance?.HEAPU8.byteLength??0;}\nexport default async function(config){const pages=globalThis.__m3MaximumWasmPages;if(!Number.isInteger(pages)||pages<256||pages>32768)throw Error('Unadmitted ORT heap');instance=await create(config);return instance;}\n")
 pins[name]=hashlib.sha256((dist/name).read_bytes()).hexdigest()
# Reuse the already pinned CPU numerical module, never copy or change it.
cpu=root/'vendor/d2prl/ort-wasm-simd-threaded.wasm';assert cpu.read_bytes()==(dist/cpu.name).read_bytes()
for name in ['ort.wasm.min.mjs','ort.webgpu.min.mjs','ort-wasm-simd-threaded.asyncify.wasm']:
 shutil.copyfile(dist/name,out/name)
for name in ['ONNXRUNTIME-LICENSE.txt','ONNXRUNTIME-ThirdPartyNotices.txt']:shutil.copyfile(root/'vendor/d2prl'/name,out/name)
files={p.name:dict(bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for p in out.iterdir() if p.name!='PINNED.json'}
report=dict(schema=1,version='1.30.0',maximumScope='Per useful worker: admitted 16 MiB to 2 GiB. Numerical WASM unchanged. GPU allocation estimate is separate; not a hardware-enforced GPU quota.',upstreamFactories=pins,files=files,cpuWasm=dict(path='../d2prl/'+cpu.name,bytes=cpu.stat().st_size,sha256=hashlib.sha256(cpu.read_bytes()).hexdigest()))
(out/'PINNED.json').write_text(json.dumps(report,indent=2)+'\n')
assets={'cpu':dict(report['cpuWasm']),'gpu':dict(path='../vendor/m3-ort/ort-wasm-simd-threaded.asyncify.wasm',**files['ort-wasm-simd-threaded.asyncify.wasm'])};assets['cpu']['path']='../vendor/d2prl/'+cpu.name
(root/'src/m3-ort-assets.js').write_text('// Generated by scripts/build-m3-ort-runtime.py.\nexport const M3_ORT_ASSETS=Object.freeze('+json.dumps(assets,separators=(',',':'))+');\n')
print(json.dumps(dict(version=report['version'],files=len(files))))
