"""Link M3 BRISK and read-only qualified ORB/AKAZE objects into own runtime."""
from pathlib import Path
import os,subprocess,json,hashlib
root=Path(__file__).resolve().parents[1];build=Path(os.environ['OPENCV_BUILD_ROOT']).resolve();compiler=Path(os.environ['EMSDK'])/'upstream/emscripten/em++';out=root/'vendor/cloning'
objects=[build/'cloning-orb-reference.o',*[build/f'akaze-area-{n}.o' for n in ['AKAZEFeatures','nldiffusion_functions','fed']],root/'.build/m3/brisk-native.o'];cmd=[str(compiler),str(root/'native/cloning.cpp'),*map(str,objects),str(root/'experiments/cloning/brisk-area.cpp')];cmd.extend(str(root/f'experiments/cloning/akaze-{n}.cpp') for n in ['angles','filters','separable','area'])
for name in ['features2d','flann','imgproc','core']:cmd.extend([str(build/f'cv/lib/libopencv_{name}.a'),'-I',str(build/f'opencv-4.11.0/modules/{name}/include')])
cmd.extend([str(build/'cv/3rdparty/lib/libzlib.a'),'-I',str(build/'cv'),'-I',str(build),'-O3','-fexceptions','-ffp-contract=off','-sDISABLE_EXCEPTION_CATCHING=0','-sMODULARIZE=1','-sEXPORT_ES6=1','-sENVIRONMENT=web,worker,node','-sALLOW_MEMORY_GROWTH=1','-sINITIAL_MEMORY=33554432','-sMEMORY_GROWTH_LINEAR_STEP=16777216','-sMAXIMUM_MEMORY=2147483648','-sABORTING_MALLOC=0','-sFILESYSTEM=0','-sEXPORTED_FUNCTIONS=["_malloc","_free","_cloning_detect","_cloning_detect_akaze","_cloning_detect_brisk","_cloning_detect_brisk_points","_cloning_describe_brisk","_cloning_result","_cloning_descriptors","_cloning_release","_cloning_select","_cloning_match","_cloning_match_sized","_cloning_order_hamming","_cloning_norm","_cloning_draw_points","_cloning_draw_matches","_cloning_count"]','-sEXPORTED_RUNTIME_METHODS=["HEAPU8","HEAPU32","HEAPF64","HEAPF32"]','-o',str(out/'cloning.js')]);subprocess.run(cmd,check=True)
pins=json.loads((out/'PINNED.json').read_text());pins.update(build='scripts/build-m3-cloning.py',nativeContract='core/cloning.py BRISK, explicit ORB and AKAZE');pins['brisk']=json.loads((root/'.build/m3/brisk-native-pin.json').read_text());(out/'BRISK-LICENSE.txt').write_text((build/'opencv-4.11.0/modules/features2d/src/brisk.cpp').read_text().split('#include',1)[0]);(out/'BRISK-AREA-LICENSE.txt').write_text((root/'experiments/cloning/brisk-area.cpp').read_text().split('//M*/',1)[0]+'//M*/\n')
for name in ['cloning.js','cloning.wasm','BRISK-LICENSE.txt','BRISK-AREA-LICENSE.txt']:
 data=(out/name).read_bytes();pins['files'][name]=dict(bytes=len(data),sha256=hashlib.sha256(data).hexdigest())
(out/'PINNED.json').write_text(json.dumps(pins,indent=2)+'\n')
