"""Isolated async libtiff module; shared SDK/libraries/sources remain read-only."""
from pathlib import Path
import os,subprocess,hashlib,json
ROOT=Path(__file__).resolve().parents[1];BUILD=Path(os.environ['OPENCV_BUILD_ROOT']);SDK=Path(os.environ['EMSDK']);CC=SDK/'upstream/emscripten/emcc';OUT=ROOT/'vendor/tiff-stream';OUT.mkdir(parents=True,exist_ok=True);WORK=ROOT/'.build/m5/tiff-stream';WORK.mkdir(parents=True,exist_ok=True);TIFF=BUILD/'opencv-4.11.0/3rdparty/libtiff';env={**os.environ,'EM_FROZEN_CACHE':'1','EMCC_CORES':'1'}
sha=lambda b:hashlib.sha256(b).hexdigest()
original=(TIFF/'tif_read.c').read_text();old='if (tif->tif_rawdatasize != tilesize)';assert original.count(old)==1
patched=original.replace(old,'if (tif->tif_rawcc != tilesize)');patched=patched.replace('(uint64_t)tif->tif_rawdatasize);','(uint64_t)tif->tif_rawcc);',1);(WORK/'tif_read.c').write_text(patched)
# Actual remaining encoded bytes must equal an uncompressed tile's useful size;
# allocator-rounded capacity is not a file byte count. This retains the guard.
includes=(BUILD/'cv/3rdparty/libtiff/CMakeFiles/libtiff.dir/includes_C.rsp');version=subprocess.check_output([str(CC),'--version'],env=env,text=True).splitlines()[0];assert '4.0.15' in version
subprocess.run([str(CC),str(WORK/'tif_read.c'),'@'+str(includes),'-D_FILE_OFFSET_BITS=64','-O3','-fexceptions','-c','-o',str(WORK/'tif_read.o')],env=env,check=True)
libs=[WORK/'tif_read.o',BUILD/'cv/3rdparty/lib/liblibtiff.a',BUILD/'cv/3rdparty/lib/liblibjpeg-turbo.a',BUILD/'cv/3rdparty/lib/libzlib.a']
subprocess.run([str(CC),str(ROOT/'native/tiff-stream.c'),*map(str,libs),'@'+str(includes),'-O3','-fexceptions','-ffile-prefix-map='+str(ROOT)+'/=','-sASYNCIFY=1','-sASYNCIFY_STACK_SIZE=262144','-sMODULARIZE=1','-sEXPORT_ES6=1','-sENVIRONMENT=web,worker,node','-sFILESYSTEM=0','-sALLOW_MEMORY_GROWTH=1','-sIMPORTED_MEMORY=1','-sABORTING_MALLOC=0','-sINITIAL_MEMORY=16777216','-sMAXIMUM_MEMORY=268435456','-sEXPORTED_FUNCTIONS=["_tiff_stream_open","_tiff_stream_block","_tiff_stream_width","_tiff_stream_height","_tiff_stream_block_width","_tiff_stream_block_height","_tiff_stream_out_width","_tiff_stream_out_height","_tiff_stream_data","_tiff_stream_error","_tiff_stream_close"]','-sEXPORTED_RUNTIME_METHODS=["HEAPU8","ccall"]','-o',str(OUT/'tiff-stream.js')],env=env,check=True)
for name,source in [('LICENSE',TIFF/'COPYRIGHT'),('ZLIB-README.txt',ROOT/'vendor/png-stream/ZLIB-README.txt'),('JPEG-LICENSE.md',ROOT/'vendor/libjpeg/LICENSE.md'),('JPEG-README.ijg',ROOT/'vendor/libjpeg/README.ijg')]: (OUT/name).write_bytes(source.read_bytes())
(OUT/'PINNED.json').write_text(json.dumps(dict(libtiff='4.6.0',compiler=version,originalTiffReadSha256=sha(original.encode()),patchedTiffReadSha256=sha(patched.encode()),patch='Uncompressed tile byte-count guard uses tif_rawcc (actual bytes) instead of tif_rawdatasize (rounded capacity); diagnostic agrees. No pixel conversion changes.',sources={p.name:sha(p.read_bytes())for p in [ROOT/'native/tiff-stream.c',TIFF/'tif_getimage.c',TIFF/'tiffio.h']},objects={p.name:sha(p.read_bytes())for p in libs},files={p.name:sha(p.read_bytes())for p in OUT.iterdir()if p.name!='PINNED.json'}),indent=2)+'\n');print('Built TIFF stream',version)
