from pathlib import Path
import json,hashlib,scipy,numpy as np
from scipy.ndimage._filters import _gaussian_kernel1d
if scipy.__version__!='1.17.1' or np.__version__!='1.26.4':raise RuntimeError('Use pinned SciPy 1.17.1 and NumPy 1.26.4')
ROOT=Path(__file__).resolve().parents[1];weights={};indices={}
for q2 in range(1,65):
 for q1 in range(max(3,2*q2),min(128,8*q2)+1):
  sigma=max(2.,q1/q2);key=str(sigma)
  if key not in weights:
   radius=int(4*sigma+.5);weights[key]=_gaussian_kernel1d(sigma,0,radius)[radius:][::-1].tolist()
  indices[f'{q1}/{q2}']=list(weights).index(key)
arrays=list(weights.values());path=ROOT/'src/double-jpeg-weights.js';path.write_text('// Generated by scripts/generate-double-jpeg-weights.py. SciPy 1.17.1 float64 Gaussian coefficients.\nexport const GAUSSIAN_INDEX=Object.freeze('+json.dumps(indices,separators=(',',':'))+');\nexport const GAUSSIAN_WEIGHTS=Object.freeze('+json.dumps(arrays,separators=(',',':'))+'.map(Object.freeze));\n')
print(len(indices),'step pairs,',len(arrays),'distinct kernels,',path.stat().st_size,'bytes; SHA256',hashlib.sha256(path.read_bytes()).hexdigest())
