"""Pin native Sewar Gaussian coefficients; no learned weights are involved."""
from pathlib import Path
import importlib.metadata as metadata
import hashlib, json, sewar.full_ref, sewar.utils
from sewar.utils import fspecial, Filter
ROOT=Path(__file__).resolve().parents[1]
lines=['// Generated by generate-comparison-kernels.py from the pinned native Sewar.']
for name,n,sigma in [('ssim',11,1.5),('vif17',17,3.4),('vif9',9,1.8),('vif5',5,1.),('vif3',3,.6)]:
 k=fspecial(Filter.GAUSSIAN,n,sigma=sigma)
 lines.append('static const double comparisonKernel_'+name+'['+str(n*n)+']={'+','.join(float(x).hex() for x in k.flat)+'};')
(ROOT/'native/comparison-kernels.h').write_text('\n'.join(lines)+'\n')
for package,pattern,target in [('sewar','licenses/LICENSE','SEWAR-LICENSE.txt'),('scipy','.dist-info/LICENSE.txt','SCIPY-LICENSE.txt')]:
 d=metadata.distribution(package)
 f=next(f for f in d.files if str(f).endswith(pattern))
 (ROOT/'vendor/comparison'/target).write_bytes(d.locate_file(f).read_bytes())
# Preserve the actual locally patched numerical oracle as part of the source kit.
for module,name in [(sewar.full_ref,'sewar-full-ref.py'),(sewar.utils,'sewar-utils.py')]:
 (ROOT/'vendor/comparison'/name).write_bytes(Path(module.__file__).read_bytes())
