"""Freeze the reference pocketfft trigonometric seeds, not image-dependent data.

Regeneration requires the Darwin/arm64 binary64-long-double reference host.
Portable WASM builds consume the checked-in, hash-pinned table instead.
"""
from pathlib import Path
import hashlib, json, platform, struct, subprocess, sys

ROOT = Path(__file__).resolve().parents[1]
assert platform.system() == 'Darwin' and platform.machine() == 'arm64'
vendor = ROOT / 'vendor/pocketfft'
source = (vendor / 'pocketfft_hdronly.h').read_text()
expected = json.loads((vendor / 'PINNED.json').read_text())['files'][0]['sha256']
assert hashlib.sha256(source.encode()).hexdigest() == expected
build = ROOT / '.build'
build.mkdir(exist_ok=True)
# Expose the two seed arrays only in a disposable generator header.
source = source.replace('template<typename T> class sincos_2pibyn\n  {\n  private:',
                        'template<typename T> class sincos_2pibyn\n  {\n  public:', 1)
(build / 'prnu-twiddles-generator.h').write_text(source)
maximum = 2**21
lengths = []
p2 = 1
while p2 <= maximum:
    p3 = p2
    while p3 <= maximum:
        p5 = p3
        while p5 <= maximum:
            lengths.append(p5)
            p5 *= 5
        p3 *= 3
    p2 *= 2
lengths.sort()
cpp = '''
#define POCKETFFT_NO_MULTITHREADING
#include "prnu-twiddles-generator.h"
#include <fstream>
int main(int argc,char**argv){
 static_assert(sizeof(long double)==8,"Native reference must use binary64 long double");
 std::ofstream out(argv[1],std::ios::binary);
 const size_t lengths[]={LENGTHS};
 for(size_t n:lengths){
  pocketfft::detail::sincos_2pibyn<double> table(n);
  for(size_t j=0;j<table.v1.size();j++){const auto z=table.v1[j];out.write((const char*)&z.r,8);out.write((const char*)&z.i,8);}
  for(size_t j=0;j<table.v2.size();j++){const auto z=table.v2[j];out.write((const char*)&z.r,8);out.write((const char*)&z.i,8);}
 }
 return out.good()?0:1;
}
'''.replace('LENGTHS', ','.join(map(str, lengths)))
(build / 'prnu-twiddles-generator.cpp').write_text(cpp)
sdk = subprocess.check_output(['xcrun', '--sdk', 'macosx', '--show-sdk-path'], text=True).strip()
subprocess.run(['clang++', '-std=c++17', '-O3', '-ffp-contract=on', '-isysroot', sdk,
                str(build / 'prnu-twiddles-generator.cpp'), '-o', str(build / 'prnu-twiddles-generator')], check=True)
subprocess.run([str(build / 'prnu-twiddles-generator'), str(build / 'prnu-twiddles-seeds.bin')], check=True)
index, words = bytearray(), 0
for n in lengths:
    nval, count1 = (n+2)//2, 2
    while count1**2 < nval:
        count1 *= 2
    count2 = (nval+count1-1)//count1
    index += struct.pack('<IIII', n, words, count1, count2)
    words += 2*(count1+count2)
seeds = (build / 'prnu-twiddles-seeds.bin').read_bytes()
assert len(seeds) == words*8
data = b'PRNUFFT1' + struct.pack('<IIII', maximum, len(lengths), words, 0) + index + seeds
name = 'prnu-twiddles.bin'
(vendor / name).write_bytes(data)
record = dict(schema=1, file=name, bytes=len(data), sha256=hashlib.sha256(data).hexdigest(),
              maximumLength=maximum, lengths=len(lengths), complexSeeds=words//2,
              reference='Darwin arm64 binary64 sin/cos; SciPy 1.17.1 pocketfft',
              pocketfftHeaderSha256=expected,
              format='PRNUFFT1; little-endian u32 max,count,doubleWords,reserved; count*(n,wordOffset,v1Count,v2Count); interleaved float64 real/imaginary seeds',
              generator='scripts/generate-prnu-twiddles.py')
(vendor / 'PRNU-TWIDDLES.json').write_text(json.dumps(record, indent=2)+'\n')
(ROOT / 'src/prnu-twiddles.js').write_text('// Generated by scripts/generate-prnu-twiddles.py.\nexport const PRNU_TWIDDLES='+json.dumps({k:record[k] for k in ['bytes','sha256','maximumLength']})+';\n')
print(json.dumps(record))
