"""Freeze the native Matplotlib byte lookup, including its truncation artifacts."""
from pathlib import Path
import hashlib
import json
import matplotlib
import numpy as np

assert matplotlib.__version__ == '3.8.4'
root = Path(__file__).resolve().parents[1]
# Integer arguments select LUT entries directly; no normalization is implicit.
rgb = matplotlib.colormaps['gray'](np.arange(256), bytes=True)[:, :3]
assert np.array_equal(rgb[:, 0], rgb[:, 1]) and np.array_equal(rgb[:, 1], rgb[:, 2])
digest = hashlib.sha256(rgb.tobytes()).hexdigest()
(root / 'src/gray-palette.js').write_text(
    '// Generated by scripts/generate-gray-palette.py; Matplotlib 3.8.4 gray bytes.\n'
    f'// RGB256 SHA256 {digest}. The byte LUT is not exactly the integer ramp.\n'
    'export const GRAY_PALETTE=Object.freeze('
    + json.dumps(rgb[:, 0].tolist(), separators=(',', ':')) + ');\n')
