"""Vendor pinned runtime code only, never English language weights."""
from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parents[1];source=root/'.build/m3/ocr/node_modules/tesseract.js-core'
assert json.loads((source/'package.json').read_text())['version']=='7.0.0'
out=root/'vendor/text-ocr';out.mkdir(exist_ok=True);files={}
for variant in ['lstm','simd-lstm']:
 stem='tesseract-core-'+variant
 for suffix in ['js','wasm']:
  name=stem+('.mjs' if suffix=='js' else '.wasm');data=(source/(stem+'.'+suffix)).read_bytes()
  if suffix=='js':data+=b'\nexport default TesseractCore;\n'
  (out/name).write_bytes(data);files[name]={'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
(out/'LICENSE').write_bytes((source/'LICENSE').read_bytes())
(out/'PINNED.json').write_text(json.dumps(dict(schema=1,package='tesseract.js-core',version='7.0.0',upstream='https://github.com/naptha/tesseract.js-core',adaptation='Append ESM default export; WASM memory maximum bounded per run before instantiation; no inference math changes.',files=files),indent=2)+'\n')
(root/'src/text-ocr-assets.js').write_text('// Generated by scripts/vendor-text-ocr.py; language data stay external.\nexport const TEXT_OCR_ASSETS='+json.dumps(files,indent=2)+';\n')
