import test from 'node:test';import assert from 'node:assert/strict';import {createAnalysisScopeController} from '../src/analysis-scope.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
test('Whole-image scope cancels detection, clears exclusions and rejects all old generations; automatic mode can return',async()=>{
 const detections=[],analyses=[],events=[],controller=createAnalysisScopeController({imageId:'i',width:300,height:200,detectSubimages:request=>{const d=deferred();detections.push({request,...d});return d.promise;},analyze:request=>{const d=deferred();analyses.push({request,...d});return d.promise;},onEvent:e=>events.push(e)});
 const first=controller.start();assert.equal(controller.getState().status,'detecting');const full=controller.useWholeImage();assert.equal(detections[0].request.signal.aborted,true);assert.deepEqual(analyses[0].request.regions,[{id:'whole-image',bounds:[0,0,300,200]}]);assert.deepEqual(analyses[0].request.exclusions,[]);assert.equal(analyses[0].request.restartAllBranches,true);
 const count=events.length;detections[0].request.onProgress({fraction:.9});detections[0].resolve([{id:'stale',bounds:[0,0,2,2]}]);assert.equal((await first).status,'superseded');assert.equal(events.length,count);analyses[0].resolve({branches:['real-provider-test-double'],generation:2});assert.equal((await full).generation,2);
 const excluded=controller.replaceExclusions([[5,5,10,10]]);assert.deepEqual(analyses[1].request.exclusions,[[5,5,10,10]]);const auto=controller.useAutomaticRegions();assert.equal(analyses[1].request.signal.aborted,true);assert.deepEqual(controller.getState().exclusions,[]);assert.equal(controller.getState().result,null);const before=events.length;analyses[1].request.onProgress({fraction:1});analyses[1].resolve({obsolete:true});assert.equal((await excluded).status,'superseded');assert.equal(events.length,before);
 detections[1].resolve([{id:'new',bounds:[20,20,280,180]}]);await Promise.resolve();assert.deepEqual(analyses[2].request.exclusions,[]);assert.equal(analyses[2].request.mode,'automatic');analyses[2].resolve({ok:true});const result=await auto;assert.equal(result.status,'complete');assert.deepEqual(result.regions,[{id:'new',bounds:[20,20,280,180]}]);assert.deepEqual(events.filter(e=>e.type==='complete').map(e=>e.generation),[2,4]);controller.dispose();
});
test('Empty or failed detection does not silently run whole-image branches; unavailable adapters remain explicit',async()=>{
 assert.throws(()=>createAnalysisScopeController({imageId:'i',width:20,height:20}),{code:'UNSUPPORTED_OPERATION'});let calls=0,fail=false;const c=createAnalysisScopeController({imageId:'i',width:20,height:20,detectSubimages:async()=>{if(fail)throw new Error('Detection failed');return [];},analyze:async()=>{calls++;return {};}});assert.equal((await c.start()).status,'no-regions');assert.equal(calls,0);fail=true;assert.equal((await c.useAutomaticRegions()).status,'detection-failed');assert.equal(calls,0);assert.equal((await c.useWholeImage()).status,'complete');assert.equal(calls,1);c.dispose();await assert.rejects(c.useWholeImage(),{code:'DISPOSED'});
});
test('Cancellation and disposal suppress late errors as well as progress/results',async()=>{
 const d=deferred(),events=[],c=createAnalysisScopeController({imageId:'i',width:20,height:20,detectSubimages:()=>d.promise,analyze:async()=>({}),onEvent:e=>events.push(e)}),job=c.start();c.cancel();const count=events.length;d.reject(new Error('Old detector failure'));assert.equal((await job).status,'superseded');assert.equal(events.length,count);c.dispose();assert.equal(c.getState().status,'disposed');
});
test('A scope action dispatched synchronously by a UI event cannot reuse the previous generation',async()=>{
 let c,restarted=false,newJob;const calls=[];c=createAnalysisScopeController({imageId:'i',width:20,height:20,detectSubimages:async()=>{throw new Error('Superseded detection must not start');},analyze:async request=>{calls.push(request);return {ok:true};},onEvent:e=>{if(e.type==='reset'&&!restarted){restarted=true;newJob=c.useWholeImage();}}});const old=c.start();assert.equal((await old).status,'superseded');assert.equal((await newJob).generation,2);assert.deepEqual(calls.map(x=>x.generation),[2]);c.dispose();
});
