import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {automaticViewSelection} from '../src/automatic-visible-entries.js';import {createAutomaticAnalysisView} from '../src/automatic-analysis-view.js';import {CLONE_SOURCES,ELA_SOURCE} from '../src/clone-relations.js';
const ref=JSON.parse(await readFile(new URL('./data/automatic-view-native.json',import.meta.url)));
test('complete display selections match actual native widget methods',()=>{for(const c of ref.cases){const actual=automaticViewSelection(ref.entries,c.view);assert.deepEqual(actual.entries.map(e=>e.id),c.expected,c.name);assert.equal(actual.mode,c.mode,c.name);assert.equal(actual.corroborating,c.corroborating,c.name);}});
test('view and export share global source/branch/family controls and restore per-tab presentation',()=>{
 const view=createAutomaticAnalysisView({complete:true,width:100,height:80});view.setPresentation('biomes');view.setRelation('all');view.setEla({background:3,biomes:true});assert.deepEqual(view.visible(ref.entries).map(e=>e.id),ref.cases.find(c=>c.name==='mode-3').expected);
 view.setForgeryscopeBranch('blots');view.setHidden(['d2']);view.focus('blots');view.selectTab(ELA_SOURCE);assert.equal(view.getState().focused,null);assert.deepEqual(view.visible(ref.entries).map(e=>e.id),['low']);assert.throws(()=>view.setPresentation('overlay'),{code:'INVALID_INPUT'});
 view.setElaFamilies({energy:false,legacy:true});assert.deepEqual(view.visible(ref.entries),[]);view.selectTab('overlay');assert.equal(view.getState().elaEnergy,false);assert.equal(view.getState().forgeryscopeBranch,'blots');assert.deepEqual(view.getState().hidden,['d2']);assert.equal(view.getState().presentation,'biomes');view.setEla({background:0,biomes:true});assert.ok(view.visible(ref.entries).some(e=>e.id==='cell'));
 view.setEnabledSources(CLONE_SOURCES);view.selectTab(ELA_SOURCE);assert.equal(view.getState().elaEffective.background,0);assert.deepEqual(view.visible(ref.entries),[]);view.selectTab('overlay');view.setEnabledSources([...CLONE_SOURCES,ELA_SOURCE]);view.setEla({background:2,biomes:true});assert.deepEqual(view.visible(ref.entries),[]);view.selectTab('D2PRL');view.setHidden([]);assert.deepEqual(view.visible(ref.entries).map(e=>e.id),['d2']);assert.equal(view.getState().elaEffective.background,0);
});
