import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {Budget} from '../src/cache.js';import {automaticAnalysisPlan,automaticSelection} from '../src/automatic-analysis-plan.js';import {createAutomaticAnalysisSession} from '../src/automatic-analysis-session.js';import {createAutomaticAnalysisView} from '../src/automatic-analysis-view.js';import {exportAutomaticSession} from '../src/automatic-session-export.js';import {unpackScientificNpz} from './automatic-npz-fixture.js';
const wasmBinary=await readFile(new URL('../vendor/composition/composition.wasm',import.meta.url));
test('partial automatic archive records unavailable engines and real original BGR identity without fabricating results',async()=>{
 const budget=new Budget(96*1024**2),width=8,height=9,plan=automaticAnalysisPlan({width,height,...automaticSelection(width,height,[])}),session=createAutomaticAnalysisSession({plan,providers:{},budget}),image={width,height,format:'rgb8',data:Uint8Array.from({length:width*height*3},(_,i)=>i%256)},bgr=Uint8Array.from(image.data,(_,i)=>image.data[i-i%3+2-i%3]);
 await session.run();const view=createAutomaticAnalysisView({width,height});view.setD2prlMinimum(91);const archive=await exportAutomaticSession(session,{image,view:view.getState()},{storage:'memory'},{budget,wasmBinary});await session.dispose();
 try{const bytes=new Uint8Array(archive.byteLength);await archive.store.readInto(bytes);const arrays=unpackScientificNpz(bytes),meta=JSON.parse(arrays.metadata_json.text.replaceAll('Infinity','1e999'));assert.deepEqual(meta.results,{});assert.equal(Object.values(meta.errors).filter(e=>e.code==='ENGINE_UNAVAILABLE').length,4);assert.ok(Object.values(meta.states).every(s=>s==='failed'));assert.equal(meta.corroboration.d2prl_min_component,91);assert.equal(meta.decoded_bgr8_sha256,createHash('sha256').update(bgr).digest('hex'));assert.ok(arrays.root_corroboration_counts.data.every(x=>x===0));assert.ok(arrays.root_corroboration_context_counts.data.every(x=>x===0));assert.equal(budget.total(),archive.byteLength);}finally{await archive.dispose();}assert.equal(budget.total(),0);
});
test('export refuses inconsistent view filters and cleans snapshot owners after missing source',async()=>{
 const budget=new Budget(96*1024**2),plan=automaticAnalysisPlan({width:8,height:8,...automaticSelection(8,8,[])}),session=createAutomaticAnalysisSession({plan,providers:{},budget}),view=createAutomaticAnalysisView({width:8,height:8}).getState();await session.run();const baseline=budget.total();assert.throws(()=>exportAutomaticSession(session,{view,filters:{d2Minimum:1}},{},{budget,wasmBinary}),{code:'INVALID_INPUT'});await assert.rejects(exportAutomaticSession(session,{}, {storage:'memory'},{budget,wasmBinary}),{code:'INVALID_INPUT'});assert.equal(budget.total(),baseline);await session.dispose();assert.equal(budget.total(),0);
});
