import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {Budget} from '../src/cache.js';import {contiguousSurface} from '../src/image-sources.js';import {automaticForgeryscopeCropSurface} from '../src/automatic-forgeryscope-stream.js';import {analyzeAutomaticForgeryscope} from '../src/automatic-forgeryscope.js';import {forgeryscopeMaskField} from '../src/forgeryscope-segmented-result.js';import {automaticAiSnapshot} from '../src/automatic-ai-snapshot.js';import {streamAutomaticNpz} from '../src/automatic-npz-stream.js';import {unpackScientificNpz} from './automatic-npz-fixture.js';
const reference=JSON.parse(await readFile(new URL('./data/automatic-ai-native.json',import.meta.url))),sha=a=>createHash('sha256').update(a).digest('hex'),names=['mask','map','candidates','geometric','branch_microscopy','branch_blots','branch_lanes'],rgb=(width,height)=>({width,height,format:'rgb8',data:Uint8Array.from({length:width*height*3},(_,i)=>((Math.floor(i/3)%width)*17+Math.floor(i/(width*3))*31+i%3*43)%256)});
test('translated M2 source crops preserve native black exclusions and borrowed source',async()=>{
 for(const c of reference.cases.filter(c=>!c.invalid)){const budget=new Budget(32*1024**2),pixels=rgb(c.width,c.height),image={surface:contiguousSurface(pixels,budget),sha256:sha(pixels.data)},original=sha(pixels.data);
  try{for(let i=0;i<c.boxes.length;i++){const crop=automaticForgeryscopeCropSurface(image,c.boxes[i],c.excludedBoxes),value=await crop.surface.readWindow();try{assert.equal(sha(value.pixels.data),c.crops[i].sha256,c.name);assert.deepEqual(crop.exclusions,c.crops[i].local);const w=await crop.surface.readWindow({x:1,y:1,width:3,height:2});try{const expected=new Uint8Array(18);for(let y=0;y<2;y++)expected.set(value.pixels.data.subarray(((y+1)*value.pixels.width+1)*3,((y+1)*value.pixels.width+4)*3),y*9);assert.deepEqual(w.pixels.data,expected);}finally{w.release();}}finally{value.release();}}assert.equal(sha(pixels.data),original);}finally{await image.surface.dispose();}assert.equal(budget.total(),0);}
});
// Protocol fixtures below exercise composition/ownership, not neural inference.
function analyzer(segmented,{failure,controller}={}){return {async analyze(source,params){let window;const pixels=source.surface?(window=await source.surface.readWindow()).pixels:source;try{if(failure==='throw')throw Error('inference failed');if(failure==='cancel')controller.abort();const {width,height}=pixels,n=width*height,mask=Uint8Array.from({length:n},(_,i)=>+(pixels.data[i*3]%3===0)),r={width,height,metadata:{status:'ok',comparisons:[],excluded_boxes:params.exclusions},provenance:{fixture:'protocol only'},metrics:{preflightExecutions:0},release(){}};for(const name of names)r[name]=segmented?forgeryscopeMaskField(mask,{floating:name==='map'}):name==='map'?Float32Array.from(mask):mask.slice();if(failure==='shape')r.width++;if(failure==='read')r.mask={...r.mask,readBytes(){throw Error('field read failed');}};if(failure==='release')r.release=async()=>{throw Error('release failed');};return r;}finally{window?.release();}}};}
function fixture(){const width=47,height=39,regions=[[[0,0],[35,0],[35,31],[0,31]],[[13,9],[46,9],[46,38],[13,38]]],excluded=[[[8,7],[18,7],[18,19],[8,19]]];return {width,height,regions,envelope:null,excluded,cpu:true,jobs:[{id:'forgeryscope',enabled:true,params:{regions,excluded,compare:false}}]};}
test('global segmented AI fields, analyzed exclusions and NPZ match contiguous assembly across overlapping zones',async()=>{
 const plan=fixture(),budget=new Budget(64*1024**2),pixels=rgb(plan.width,plan.height),image={segmented:true,surface:contiguousSurface(pixels,budget),sha256:sha(pixels.data)};let a,b,aa,bb;
 try{a=await analyzeAutomaticForgeryscope(pixels,plan,{budget,analyzer:analyzer(false)});b=await analyzeAutomaticForgeryscope(image,plan,{budget,analyzer:analyzer(true)});for(const name of [...names,'analyzed']){const bytes=new Uint8Array(b.stores[name].byteLength);await b.stores[name].readInto(bytes);assert.deepEqual(bytes,new Uint8Array(a[name].buffer),name);}assert.deepEqual({...b.metadata,result_storage:'ram'},a.metadata);
 aa=await streamAutomaticNpz({results:{forgeryscope:automaticAiSnapshot('forgeryscope',a)}},{},{storage:'memory'},{budget});bb=await streamAutomaticNpz({results:{forgeryscope:automaticAiSnapshot('forgeryscope',b)}},{},{storage:'memory'},{budget});const unpack=async output=>{const bytes=new Uint8Array(output.byteLength);await output.store.readInto(bytes);return unpackScientificNpz(bytes);},left=await unpack(aa),right=await unpack(bb);for(const [name,value]of Object.entries(left).filter(([k])=>k.startsWith('root_')))assert.deepEqual(right[name],value,name);
 }finally{await aa?.dispose();await bb?.dispose();await a?.release();await b?.release();await image.surface.dispose();}assert.equal(budget.total(),0);
});
test('paged automatic source failures and cancellation leave no output/window leases',async()=>{
 const plan=fixture(),budget=new Budget(64*1024**2),image={segmented:true,surface:contiguousSurface(rgb(plan.width,plan.height),budget),sha256:'fixture'};
 try{for(const failure of ['throw','cancel','shape','read','release']){const controller=new AbortController();await assert.rejects(analyzeAutomaticForgeryscope(image,plan,{budget,signal:controller.signal,analyzer:analyzer(true,{failure,controller})}),failure==='cancel'?{code:'CANCELLED'}:failure==='shape'?{code:'INVALID_INPUT'}:/failed/);assert.equal(budget.total(),0,failure);}}finally{await image.surface.dispose();}
});
