import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {automaticPointSnapshot} from '../src/automatic-point-snapshot.js';import {streamAutomaticNpz} from '../src/automatic-npz-stream.js';import {Budget} from '../src/cache.js';import {unpackScientificNpz} from './automatic-npz-fixture.js';
const ref=JSON.parse(await readFile(new URL('./data/automatic-point-snapshot-native.json',import.meta.url))),sha=x=>createHash('sha256').update(x).digest('hex');
function fixture(kind){const {pointType,...r}=ref.inputs[kind],{width,height}=ref,n=width*height,Type=pointType==='float32'?Float32Array:Float64Array,value={...r,points:Type.from(r.points.flat()),pairs:Float64Array.from(r.pairs.flat()),groups:r.groups.map(g=>Uint32Array.from(g)),colors:Uint8Array.from(r.colors.flat()),pair_search_regions:Int32Array.from(r.pair_search_regions),params:{effectiveBrowserConfiguration:true},status:'ok',metrics:{preflightExecutions:0}};
 if(kind==='patchmatch')Object.assign(value,{pair_algorithms:Uint8Array.from({length:r.pairs.length},(_,i)=>i%2),group_variants:['normal'],group_frames:['normal'],dense_maps:[0,1].map(k=>({width,height,selected:Uint8Array.from({length:n},(_,i)=>+(i%3===0)),errors:k===0?Float32Array.from({length:n},(_,i)=>(i%71)/8):undefined,targets:Int32Array.from({length:n},(_,i)=>i%53-1),distancesSquared:Float32Array.from({length:n},(_,i)=>(i%37)/16),shift:12,context:{origin:[7,11],pairSearchRegion:2,compare:false},pass:{algorithm:'PatchMatch SIFT',stage:k?'mirror':'base',descriptorFrame:k?'quarter_turn/bin=10':'normal',patch:8,targetPatch:k?10:8},allowed:Uint8Array.from({length:n},(_,i)=>i%4),displayRows:new Uint32Array([0,19,53]),comparisons:9007199254740997n}))});
 return value;}
test('classical snapshots retain native array types, int64 biome indices and full dense fields',async()=>{
 const budget=new Budget(16*1024**2),results=Object.fromEntries(['sift','patchmatch'].map(kind=>[kind,automaticPointSnapshot(fixture(kind),{nativeParams:ref.inputs[kind].params})])),output=await streamAutomaticNpz({results},{},{storage:'memory'},{budget});
 try{const bytes=new Uint8Array(output.byteLength);await output.store.readInto(bytes);const arrays=unpackScientificNpz(bytes),metadata=JSON.parse(arrays.metadata_json.text);for(const [name,e]of Object.entries(ref.arrays)){assert.deepEqual(arrays[name].shape,e.shape,name);assert.equal(arrays[name].dtype,e.dtype,name);assert.equal(sha(arrays[name].data),e.sha256,name);}for(const kind of ['sift','patchmatch']){const details=metadata.results[kind].browser_details;assert.equal(details.params.effectiveBrowserConfiguration,true);delete metadata.results[kind].browser_details;}assert.deepEqual(metadata,ref.metadata);assert.equal(Object.keys(arrays).filter(k=>!k.endsWith('json')).length,Object.keys(ref.arrays).length+4);for(let i=0;i<2;i++){const name='root_results_patchmatch_browser_details_dense_fields_'+i;assert.equal(arrays[name+'_allowed'].dtype,'|u1');assert.deepEqual(arrays[name+'_allowed'].shape,[ref.height,ref.width]);assert.equal(arrays[name+'_displayRows'].dtype,'<u4');}}
 finally{await output.dispose();}assert.equal(budget.total(),0);
});
test('classical snapshot rejects ambiguous arrays and preserves empty native matrices',async()=>{
 const v=fixture('sift'),nativeParams=ref.inputs.sift.params;for(const value of [{...v,points:new Float32Array(3)},{...v,groups:[[0,1]]},{...v,pair_search_regions:new BigInt64Array(v.pair_search_regions.length)},{...v,unknown:new Uint8Array(1)}])assert.throws(()=>automaticPointSnapshot(value,{nativeParams}),{code:'INVALID_INPUT'});
 const empty={...v,points:new Float64Array(0),pairs:new Float64Array(0),groups:[],colors:new Uint8Array(0),pair_search_regions:new Int32Array(0)},budget=new Budget(4*1024**2),output=await streamAutomaticNpz(automaticPointSnapshot(empty,{nativeParams}),{},{storage:'memory'},{budget});try{const bytes=new Uint8Array(output.byteLength);await output.store.readInto(bytes);const arrays=unpackScientificNpz(bytes);assert.deepEqual(arrays.root_points.shape,[0,7]);assert.deepEqual(arrays.root_pairs.shape,[0,4]);assert.deepEqual(arrays.root_colors.shape,[0,3]);}finally{await output.dispose();}assert.equal(budget.total(),0);
});

test('paged dense fields export every native byte and reject unmarked or truncated stores',async()=>{
 const original=fixture('patchmatch'),paged=fixture('patchmatch'),nativeParams=ref.inputs.patchmatch.params;
 for(const f of paged.dense_maps){f.paged=true;f.dispose=async()=>{throw Error('borrowed fields must not be disposed by snapshot');};for(const key of ['selected','errors','targets','distancesSquared','allowed'])if(f[key]){const source=new Uint8Array(f[key].buffer,f[key].byteOffset,f[key].byteLength);f[key]={byteLength:source.length,async readInto(bytes,offset=0){bytes.set(source.subarray(offset,offset+bytes.length));}};}}
 const budget=new Budget(16*1024**2),archives=[];
 try{for(const v of [original,paged]){const output=await streamAutomaticNpz(automaticPointSnapshot(v,{nativeParams}),{},{storage:'memory'},{budget});archives.push(output);}const unpacked=[];for(const archive of archives){const bytes=new Uint8Array(archive.byteLength);await archive.store.readInto(bytes);unpacked.push(unpackScientificNpz(bytes));}for(const [key,a] of Object.entries(unpacked[0]))if(!key.endsWith('json')){assert.equal(unpacked[1][key].dtype,a.dtype,key);assert.deepEqual(unpacked[1][key].shape,a.shape,key);assert.equal(sha(unpacked[1][key].data),sha(a.data),key);}const metadata=JSON.parse(unpacked[1].metadata_json.text);assert.equal(metadata.browser_details.dense_fields[0].paged,true);assert.equal(Object.hasOwn(metadata.browser_details.dense_fields[0],'dispose'),false);
 paged.dense_maps[0].paged=false;assert.throws(()=>automaticPointSnapshot(paged,{nativeParams}),{code:'INVALID_INPUT'});paged.dense_maps[0].paged=true;paged.dense_maps[0].targets.byteLength--;assert.throws(()=>automaticPointSnapshot(paged,{nativeParams}),{code:'INVALID_INPUT'});
 }finally{for(const archive of archives)await archive.dispose();}assert.equal(budget.total(),0);
});
