import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {automaticAiSnapshot} from '../src/automatic-ai-snapshot.js';import {streamAutomaticNpz} from '../src/automatic-npz-stream.js';import {Budget} from '../src/cache.js';import {unpackScientificNpz} from './automatic-npz-fixture.js';
const ref=JSON.parse(await readFile(new URL('./data/automatic-ai-snapshot-native.json',import.meta.url))),sha=x=>createHash('sha256').update(x).digest('hex');
function fixture(){const {width,height}=ref,n=width*height,make=names=>Object.fromEntries(names.map((name,j)=>[name,['map','source','target'].includes(name)?Float32Array.from({length:n},(_,i)=>(i%37-18)/8):Uint8Array.from({length:n},(_,i)=>+( (i+j)%3===0))])),forge={width,height,...make(['map','mask','candidates','analyzed','geometric','branch_microscopy','branch_blots','branch_lanes']),metadata:{variant:'Forgeryscope Auto',boxes:[[0,0,width,height]],status:'ok'}},d2={width,height,...make(['map','mask','candidates','analyzed','source','target']),metadata:{variant:'D2PRL',boxes:[[0,0,width,height],[3,2,17,16]],analysisId:'saved-analysis',resultId:'initial-result',min_component:500}},count=3*448**2;
 const raw={width,height,rawGrids:d2.metadata.boxes.map((bounds,j)=>({bounds,raw:Float32Array.from({length:count},(_,i)=>((j*count+i)%127-63)/16)})),metadata:{...d2.metadata,resultId:'refiltered-result',min_component:17,raw_shape:[3,448,448]}};return {forge,d2,raw};}
test('AI archive preserves native mask/role types and ordered raw D2PRL grids across chunks',async()=>{
 const {forge,d2,raw}=fixture(),budget=new Budget(16*1024**2),snapshot={results:{forgeryscope:automaticAiSnapshot('forgeryscope',forge),d2prl:automaticAiSnapshot('d2prl',d2,{raw})}},output=await streamAutomaticNpz(snapshot,{}, {storage:'memory'},{budget});
 try{for(const g of raw.rawGrids)g.raw.fill(0);const bytes=new Uint8Array(output.byteLength);await output.store.readInto(bytes);const arrays=unpackScientificNpz(bytes);assert.deepEqual(Object.keys(arrays).filter(k=>!k.endsWith('json')),Object.keys(ref.arrays));for(const [name,expected]of Object.entries(ref.arrays)){assert.equal(arrays[name].dtype,expected.dtype,name);assert.deepEqual(arrays[name].shape,expected.shape,name);assert.equal(sha(arrays[name].data),expected.sha256,name);}assert.equal(arrays.metadata_json.text,ref.metadataText);}finally{await output.dispose();}assert.equal(budget.total(),0);
});
test('AI snapshots reject mixed analyses, reordered grids, missing data and lossy role conversion',async()=>{
 const {forge,d2,raw}=fixture();for(const operation of [()=>automaticAiSnapshot('unknown',forge),()=>automaticAiSnapshot('d2prl',d2),()=>automaticAiSnapshot('d2prl',{...d2,target:new Uint8Array(d2.target.length)},{raw}),()=>automaticAiSnapshot('forgeryscope',{...forge,extra:new Uint8Array(1)}),()=>automaticAiSnapshot('d2prl',d2,{raw:{...raw,rawGrids:raw.rawGrids.toReversed()}}),()=>automaticAiSnapshot('d2prl',d2,{raw:{...raw,metadata:{...raw.metadata,analysisId:'other'}}})])assert.throws(operation,{code:'INVALID_INPUT'});
 const budget=new Budget(16*1024**2),controller=new AbortController();await assert.rejects(streamAutomaticNpz({result:automaticAiSnapshot('d2prl',d2,{raw})},{},{storage:'memory'},{budget,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),0);
});

function paged(result){const stores={};for(const name of ['map','mask','candidates','analyzed','source','target']){const a=result[name],data=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);stores[name]={byteLength:data.byteLength,async readInto(out,at){out.set(data.subarray(at,at+out.length));}};}return {width:result.width,height:result.height,metadata:result.metadata,layout:'segmented',stores};}
test('segmented D2PRL snapshot exports the same complete scientific archive and rejects mixed layouts',async()=>{
 const {d2,raw}=fixture(),result=paged(d2),budget=new Budget(32*1024**2);let a,b;
 try{a=await streamAutomaticNpz({d2prl:automaticAiSnapshot('d2prl',d2,{raw})},{},{storage:'memory'},{budget});b=await streamAutomaticNpz({d2prl:automaticAiSnapshot('d2prl',result,{raw})},{},{storage:'memory'},{budget});assert.equal(a.byteLength,b.byteLength);assert.equal(a.sha256,b.sha256);const bytes=new Uint8Array(b.byteLength);await b.store.readInto(bytes);const arrays=unpackScientificNpz(bytes);for(const [name,expected]of Object.entries(ref.arrays).filter(([k])=>k.startsWith('root_results_d2prl_')))assert.equal(sha(arrays[name.replace('results_','')].data),expected.sha256,name);
 for(const bad of [{...result,mask:d2.mask},{...result,stores:{...result.stores,extra:result.stores.mask}},{...result,stores:{...result.stores,target:{...result.stores.target,byteLength:1}}},{...result,layout:'unknown'}])assert.throws(()=>automaticAiSnapshot('d2prl',bad,{raw}),{code:'INVALID_INPUT'});
 }finally{await a?.dispose();await b?.dispose();}assert.equal(budget.total(),0);
});
