import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createAutomaticAnalyzer} from '../src/index.js';import {Budget} from '../src/cache.js';import {automaticSelection} from '../src/automatic-analysis-plan.js';import {unpackScientificNpz} from './automatic-npz-fixture.js';
test('public integration facade preserves explicit missing engines and caller-owned source',async()=>{
 const budget=new Budget(96*1024**2),data=new Uint8Array(8*8*3),sourceReservation=budget.reserve(data.length),image={width:8,height:8,format:'rgb8',data},selection=automaticSelection(8,8,[]),compositionWasmBinary=await readFile(new URL('../vendor/composition/composition.wasm',import.meta.url)),analyzer=await createAutomaticAnalyzer({image,selection,budget,d2Minimum:0,compositionWasmBinary});selection.regions.length=0;analyzer.plan.regions.length=0;
 const state=await analyzer.run();assert.equal(Object.values(state.errors).filter(e=>e.code==='ENGINE_UNAVAILABLE').length,4);assert.equal(state.preflightExecutions,0);analyzer.view.setD2prlMinimum(91);assert.throws(()=>analyzer.prepare({d2Minimum:1}),{code:'INVALID_INPUT'});const frame=await analyzer.prepare();assert.deepEqual(analyzer.visible(frame),[]);assert.equal(frame.filters.d2Minimum,91);const archive=await analyzer.export({}, {storage:'memory'});await analyzer.dispose();assert.throws(()=>analyzer.prepare(),{code:'DISPOSED'});await frame.release();const bytes=new Uint8Array(archive.byteLength);await archive.store.readInto(bytes);const meta=JSON.parse(unpackScientificNpz(bytes).metadata_json.text.replaceAll('Infinity','1e999'));assert.equal(meta.configuration.zones.length,1);assert.equal(meta.corroboration.d2prl_min_component,91);await archive.dispose();assert.equal(budget.total(),data.length);sourceReservation();assert.equal(budget.total(),0);
});
test('all-disabled complete selection allocates no ELA provider or fallback analysis',async()=>{
 const budget=new Budget(1024**2),image={width:8,height:8,format:'rgb8',data:new Uint8Array(192)},selection=automaticSelection(8,8,[]);selection.disabled=[0];const analyzer=await createAutomaticAnalyzer({image,selection,budget,complete:true,ela:{cellParams:{block:123}}});assert.ok(Object.values((await analyzer.run()).states).every(s=>s==='no-active-zones'));const frame=await analyzer.prepare();assert.deepEqual(frame.entries,[]);await frame.release();await analyzer.dispose();assert.equal(budget.total(),0);
 await assert.rejects(createAutomaticAnalyzer({image,selection:automaticSelection(8,8,[]),budget,complete:true,ela:{cellParams:{block:123}}}),{code:'INVALID_INPUT'});assert.equal(budget.total(),0);
});
