import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Budget} from '../src/cache.js';import {createCloneEntryGeometry} from '../src/clone-entry-geometry.js';import {forgeryscopeEntries,d2prlEntries} from '../src/automatic-ai-entries.js';
const reference=JSON.parse(await readFile(new URL('./data/clone-entries-native.json',import.meta.url))),wasmBinary=new Uint8Array(await readFile(new URL('../vendor/clone-entries/clone-entries.wasm',import.meta.url)));
test('native float32 hulls, Python JSON stable ids and BGR colors',async()=>{const budget=new Budget(256*1024**2),g=await createCloneEntryGeometry({budget,wasmBinary});try{for(const c of reference.entries){const result=await g.entry(c.source,c.polygons,c.count,c.provenance);try{assert.deepEqual(result?.entry??null,c.expected,c.source+'/'+c.count);}finally{result?.release();}}}finally{g.dispose();}assert.equal(budget.total(),0);});
const flattened=e=>({...e,pixel_mask:Array.from({length:e.pixel_mask.height},(_,y)=>[...e.pixel_mask.data.subarray(y*e.pixel_mask.width,(y+1)*e.pixel_mask.width)])});
test('native D2PRL exact masks, holes, external contours, component order and stable identities',async()=>{for(const c of reference.masks){const budget=new Budget(256*1024**2),result=await d2prlEntries({...c,mask:Uint8Array.from(c.mask.flat())},{budget,wasmBinary});try{assert.deepEqual(result.entries.map(flattened),c.expected,c.name);}finally{result.release();}assert.equal(budget.total(),0);}});
test('native Forgeryscope filtering, display polygons, duplicate identities and source offsets',async()=>{for(const c of reference.forgeryscope){const budget=new Budget(256*1024**2),result=await forgeryscopeEntries(c.input,{...c,budget,wasmBinary});try{assert.deepEqual(result.entries,c.expected);}finally{result.release();}assert.equal(budget.total(),0);}});
test('D2PRL threshold changes require real cached-grid refilter, with cleanup on cancellation',async()=>{
 const c=reference.masks[0],input={...c,mask:Uint8Array.from(c.mask.flat())},budget=new Budget(256*1024**2);await assert.rejects(d2prlEntries(input,{budget,minimum:100,wasmBinary}),{code:'INVALID_INPUT'});let refilters=0,released=0;
 const refilter=async minimum=>{refilters++;return {...input,metadata:{...input.metadata,min_component:minimum},release(){released++;}};};const result=await d2prlEntries(input,{budget,minimum:100,wasmBinary,refilter});assert.equal(refilters,1);assert.equal(released,1);assert.ok(result.entries.every(e=>e.provenance.min_component===100));result.release();assert.equal(budget.total(),0);
 const controller=new AbortController();await assert.rejects(d2prlEntries(input,{budget,wasmBinary,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),0);
 await assert.rejects(d2prlEntries(input,{budget,wasmBinary,onProgress:()=>{throw Error('sink failed');}}),/sink failed/);assert.equal(budget.total(),0);
});
