import test from 'node:test';
import assert from 'node:assert/strict';
import {Budget} from '../src/cache.js';
import {EngineError} from '../src/errors.js';
import {createD2prlRecovery} from '../experiments/d2prl/recovery.js';
import {createUnetGraph} from '../experiments/d2prl/unet-graph.js';
import {createPatchMatch} from '../experiments/d2prl/patchmatch.js';
import {createD2prlAnalysis} from '../experiments/d2prl/analysis.js';
const MiB=1024**2,N=448**2,terminal=()=>new EngineError('MEMORY_ALLOCATION','Array buffer allocation failed',{details:{recovery:{loopDetected:true}}});
function graphFixture(budget,{fault=false}={}){let refusals=0,calls=[];const recovery=createD2prlRecovery({budget,reclaim:async()=>1}),graph={schema:1,status:'unqualified-experimental-graph',inputShape:[1,3,448,448],input:'rgb',output:'out',parameters:{},nodes:['a','b','out'].map((name,index)=>({op:'Test',inputs:[index?['a','b'][index-1]:'rgb'],outputs:[name],attributes:{}}))};const engine=createUnetGraph({budget,graph,layouts:{records:[]},operation:(name,work)=>recovery(name,()=>{if(fault&&name==='unet-node:2'&&refusals++<5)throw new RangeError('Array buffer allocation failed');return work();}),math:{async run(_op,[input]){calls.push(input.data[0]);const release=budget.reserve(N*4),data=new Float32Array(N);data.fill(input.data[0]+1);return{data,shape:[1,1,448,448],release};}}});return{engine,calls};}
test('UNet terminal preserves validated nodes; explicit resume does not replay them',async()=>{const budget=new Budget(64*MiB),{engine,calls}=graphFixture(budget,{fault:true}),rgb=new Float32Array(3*N);await assert.rejects(engine.run(rgb,{checkpointKey:'source+zone+recipe'}),e=>e.details?.recovery?.loopDetected);assert.deepEqual(calls,[0,1]);assert.equal(engine.snapshot().nextNode,2);const output=await engine.run(rgb,{checkpointKey:'source+zone+recipe'});assert.deepEqual(calls,[0,1,2]);assert.equal(output.data[0],3);output.release();engine.dispose();assert.equal(budget.total(),0);});
test('changing a checkpoint identity discards prior owned graph values',async()=>{const budget=new Budget(64*MiB),{engine,calls}=graphFixture(budget,{fault:true}),rgb=new Float32Array(3*N);await assert.rejects(engine.run(rgb,{checkpointKey:'old'}));const output=await engine.run(rgb,{checkpointKey:'new'});assert.deepEqual(calls,[0,1,0,1,2]);output.release();engine.releaseCheckpoint();engine.dispose();assert.equal(budget.total(),0);});
async function pmRun(fault){const budget=new Budget(64*MiB),operation=createD2prlRecovery({budget,reclaim:async()=>1});let calls=0,refusals=0,trace=[],input;const engine=await createPatchMatch(null,{budget,operation,evaluatorFactory:async()=>({async evaluate({offsetX,offsetY,side}){if(fault&&calls===7&&refusals++<5)throw new RangeError('Array buffer allocation failed');calls++;return{x:offsetX.slice(0,side*side),y:offsetY.slice(0,side*side)};},dispose(){}})});input={zmFeatures:new Uint16Array(36*64),cnnFeatures:new Uint16Array(96*64),side:8,iterations:4,randomState:{state:Array.from({length:624},(_,i)=>Math.imul(i+1,1664525)>>>0),left:1,next:0}};const hooks={checkpointKey:'pm-source',onTrace:e=>trace.push([e.branch,e.phase,e.call])};if(fault){await assert.rejects(engine.run(input,hooks),e=>e.details?.recovery?.loopDetected);assert.equal(engine.checkpointSnapshot().completed,7);assert.ok(engine.checkpointSnapshot().pending);}const result=await engine.run(input,hooks),value={offsets:result.offsets,coordinates:result.coordinates,random:result.finalRandomState,trace,calls};result.release();engine.dispose();assert.equal(budget.total(),0);return value;}
test('PatchMatch terminal at evaluation keeps exact candidate/RNG cursor and completed evaluations',async()=>{assert.deepEqual(await pmRun(true),await pmRun(false));});
test('analysis retains completed zones through terminal resume and releases the active pipeline key',async()=>{const budget=new Budget(64*MiB),calls=[],keys=[],released=[];let failed=false;const session=createD2prlAnalysis({budget,modelId:'test',releaseInferenceCheckpoint:key=>released.push(key),infer:async(input,options)=>{keys.push(options.checkpointKey);calls.push(input.rgb[0]);if(input.rgb[0]===2&&!failed){failed=true;throw terminal();}return{raw:new Float32Array(3*N),release(){}};},project:{async run(input){return{metadata:{exclusions:[],zones:input.zones},release(){}};}}});const pixels={width:16,height:8,data:new Uint8Array(16*8*3)};for(let y=0;y<8;y++){pixels.data.fill(1,y*48,y*48+24);pixels.data.fill(2,y*48+24,y*48+48);}const input={pixels,zones:[{id:'a',kind:'region',bounds:[0,0,8,8]},{id:'b',kind:'region',bounds:[8,0,16,8]}]};await assert.rejects(session.run(input,{checkpointKey:'group-key'}));const result=await session.run(input,{checkpointKey:'group-key'});assert.deepEqual(calls,[1,2,2]);assert.equal(keys[1],keys[2]);assert.equal(result.metadata.cache_hits,1);result.release();await session.dispose();assert.ok(released.includes(keys[1]));assert.equal(budget.total(),0);});
test('cancellation discards checkpoints rather than retaining cancelled output',async()=>{const budget=new Budget(64*MiB),{engine}=graphFixture(budget,{fault:true}),rgb=new Float32Array(3*N);await assert.rejects(engine.run(rgb,{checkpointKey:'old'}));const controller=new AbortController();await assert.rejects(engine.run(rgb,{checkpointKey:'old',signal:controller.signal,onNode(){controller.abort();}}),{code:'CANCELLED'});assert.equal(engine.snapshot(),null);engine.dispose();assert.equal(budget.total(),0);});

import {createDescriptors} from '../experiments/d2prl/descriptors.js';
import {createUnionHead} from '../experiments/d2prl/union-head.js';
import {createHash} from 'node:crypto';
const digest=view=>createHash('sha256').update(new Uint8Array(view.buffer,view.byteOffset,view.byteLength)).digest('hex');
async function descriptorsRun(fault){const budget=new Budget(512*MiB),calls=[],traces=[],operation=createD2prlRecovery({budget,reclaim:async()=>1});let refusals=0;
 const output=(Type,length,value,shape)=>{const release=budget.reserve(Type.BYTES_PER_ELEMENT*length),data=new Type(length);data.fill(value);return{data,shape,release};};
 const conv={run:spec=>operation('fixture-convolution',()=>{if(fault&&spec.name==='448-cnn-6'&&refusals++<5)throw new RangeError('Array buffer allocation failed');calls.push(spec.name);return output(Float32Array,spec.outChannels*spec.side**2,spec.name.length,[1,spec.outChannels,spec.side,spec.side]);})};
 const math={async run(op,args){const input=args.input;if(op==='resize')return output(Float32Array,args.channels*args.outHeight*args.outWidth,input[0],[1,args.channels,args.outHeight,args.outWidth]);if(op==='reflect')return output(Float32Array,args.channels*(args.height+2*args.pad)*(args.width+2*args.pad),input[0],[1,args.channels,args.height+2*args.pad,args.width+2*args.pad]);return output(op==='half'?Uint16Array:Float32Array,input.length,input[0],[1,args.channels??12,args.height??448,args.width??448]);}};
 const engine=createDescriptors({budget,operation,math,convolution:conv,loadConvolution:async name=>({name,side:+name.split('-')[0],outChannels:name.includes('-zm-')?12:32,release(){}}),loadBatchNorm:async()=>({release(){}})}),rgb=new Float32Array(3*N),hooks={checkpointKey:'descriptors',onStage:name=>traces.push(name)};
 if(fault){await assert.rejects(engine.run(rgb,hooks),e=>e.details?.recovery?.loopDetected);assert.ok(engine.checkpointSnapshot().nextStep>0);}const result=await engine.run(rgb,hooks),value={hashes:[digest(result.zm),digest(result.cnn)],calls,traces};result.release();engine.dispose();assert.equal(budget.total(),0);return value;
}
test('descriptor checkpoint preserves previously completed convolutions and descriptor planes',async()=>{assert.deepEqual(await descriptorsRun(true),await descriptorsRun(false));});
async function unionRun(fault){const budget=new Budget(128*MiB),operation=createD2prlRecovery({budget,reclaim:async()=>1}),calls=[],loads=[];let refusals=0;const out=value=>{const release=budget.reserve(4*N),data=new Float32Array(N);data.fill(value);return{data,shape:[1,1,448,448],release};};const spec=name=>({name,bytes:4,shape:[1,1,1,1]});
 const layers=Array.from({length:5},(_,i)=>({name:'layer'+i,weights:spec('w'+i),bias:spec('b'+i),padding:0})),batchnorm=Array.from({length:4},(_,i)=>({params:spec('bn'+i),epsilon:1}));
 const engine=createUnionHead({budget,operation,layers,batchnorm,dlfWeights:{7:spec('d7'),9:spec('d9'),11:spec('d11')},layouts:{records:[]},loadParameter:async(_kind,s)=>{loads.push(s.name);return Float32Array.of(s.name[0]==='w'?+s.name[1]:1);},dlf:{async run({kernel}){calls.push('d'+kernel);const result=out(kernel);return{scores:result.data,release:result.release};}},convolution:{run:args=>operation('union-native',()=>{const index=args.weights[0];if(fault&&index===3&&refusals++<5)throw new RangeError('Array buffer allocation failed');calls.push('c'+index);return out(args.input[0]+1);})},featureMath:{async run(_op,args){calls.push('affine');return out(args.input[0]+2);}},neuralMath:{async run(_op,[input]){return out(input.data[0]+3);}}});const pair=()=>({x:new Float32Array(N),y:new Float32Array(N)}),input={offsets:{zm:pair(),cnn:pair()},coordinates:{zm:pair(),cnn:pair()}},hooks={checkpointKey:'union'};
 if(fault)await assert.rejects(engine.run(input,hooks),e=>e.details?.recovery?.loopDetected);const result=await engine.run(input,hooks),value={hash:digest(result.data),calls,loads};result.release();engine.dispose();assert.equal(budget.total(),0);return value;
}
test('union checkpoint keeps completed DLF/convolutions and held weights at refusal',async()=>{assert.deepEqual(await unionRun(true),await unionRun(false));});
test('a changed RNG identity invalidates the previous PatchMatch checkpoint',async()=>{const budget=new Budget(64*MiB),operation=createD2prlRecovery({budget,reclaim:async()=>1});let calls=0,refusals=0;const engine=await createPatchMatch(null,{budget,operation,evaluatorFactory:async()=>({async evaluate({offsetX,offsetY,side}){if(calls===2&&refusals++<5)throw new RangeError('Array buffer allocation failed');calls++;return{x:offsetX.slice(0,side*side),y:offsetY.slice(0,side*side)};},dispose(){}})}),input={zmFeatures:new Uint16Array(36*64),cnnFeatures:new Uint16Array(96*64),side:8,iterations:1,randomState:{state:Array.from({length:624},(_,i)=>Math.imul(i+1,1664525)>>>0),left:1,next:0}};await assert.rejects(engine.run(input,{checkpointKey:'same'}));input.randomState={...input.randomState,state:[...input.randomState.state]};input.randomState.state[12]^=1;const output=await engine.run(input,{checkpointKey:'same'});assert.equal(calls,5,'Two prior evaluations and three fresh evaluations with changed seed');output.release();engine.dispose();assert.equal(budget.total(),0);});
test('an already cancelled explicit graph resume discards the retained checkpoint',async()=>{const budget=new Budget(64*MiB),{engine}=graphFixture(budget,{fault:true}),rgb=new Float32Array(3*N);await assert.rejects(engine.run(rgb,{checkpointKey:'old'}));await assert.rejects(engine.run(rgb,{checkpointKey:'old',signal:AbortSignal.abort()}),{code:'CANCELLED'});assert.equal(engine.snapshot(),null);engine.dispose();assert.equal(budget.total(),0);});

for(const replacement of [false,true])test(`cancelled queued analysis ${replacement?'preserves the following resume checkpoint':'releases the preceding terminal checkpoint'}`,async()=>{
 const budget=new Budget(64*MiB),calls=[],keys=[],released=[];let failed=false;
 const session=createD2prlAnalysis({budget,modelId:'test',releaseInferenceCheckpoint:key=>released.push(key),infer:async(input,options)=>{calls.push(input.rgb[0]);keys.push(options.checkpointKey);if(input.rgb[0]===2&&!failed){failed=true;throw terminal();}return{raw:new Float32Array(3*N),release(){}};},project:{async run(input){return{metadata:{exclusions:[],zones:input.zones},release(){}};}}});
 const pixels={width:16,height:8,data:new Uint8Array(16*8*3)};for(let y=0;y<8;y++){pixels.data.fill(1,y*48,y*48+24);pixels.data.fill(2,y*48+24,y*48+48);}
 const input={pixels,zones:[{id:'a',kind:'region',bounds:[0,0,8,8]},{id:'b',kind:'region',bounds:[8,0,16,8]}]},hooks={checkpointKey:'retained-terminal'};
 await assert.rejects(session.run(input,hooks));assert.ok(budget.total()>0);assert.equal(released.length,0);
 const cancelled=session.run(input,{...hooks,signal:AbortSignal.abort()}),resumed=replacement?session.run(input,hooks):null;
 await assert.rejects(cancelled,{code:'CANCELLED'});
 if(resumed){const result=await resumed;assert.deepEqual(calls,[1,2,2]);assert.equal(result.metadata.cache_hits,1);result.release();}
 else{assert.deepEqual(calls,[1,2]);assert.equal(budget.total(),0);assert.deepEqual(released,keys);}
 await session.dispose();assert.equal(budget.total(),0);
});

test('analysis forwards an explicit recovery parent through projection and refilter',async()=>{
 const budget=new Budget(64*MiB),parent=budget.beginOperation({owner:'automatic',id:'prepare'}),seen=[],session=createD2prlAnalysis({budget,modelId:'parent-link',infer:async()=>({raw:new Float32Array(3*N),release(){}}),project:{async run(input,hooks){seen.push(hooks.resourceOperation);return {metadata:{exclusions:[],zones:input.zones},release(){}};}}});
 try{const output=await session.run({pixels:{width:8,height:8,data:new Uint8Array(8*8*3)},zones:[{id:'one',kind:'region',bounds:[0,0,8,8]}]},{resourceOperation:parent});output.release();assert.deepEqual(seen,[parent]);}finally{await session.dispose();parent.release();}assert.equal(budget.total(),0);
});
