import {readFile} from 'node:fs/promises';import test from 'node:test';import assert from 'node:assert/strict';import {Budget} from '../src/cache.js';import {D2PRL_MODEL_IDENTITY} from '../src/d2prl-model-identity.js';
const enabled=process.execArgv.includes('--experimental-test-module-mocks');
// Only lifecycle/protocol doubles; no neural or projection parity is asserted.
test('adapter-owned projected outputs and raw grid copies survive adapter disposal', {skip:!enabled&&'Run with --experimental-test-module-mocks for isolated ownership protocol tests'},async t=>{
 const budget=new Budget(160*1024**2);let inferences=0;const checkpointReleases=[];
 const manifest={schema:1,side:448,iterations:40,seed:22,referenceThreads:8,modelId:'ownership-protocol-fixture',checkpointSha256:'2749c7436169ce689deaeb197ce5dae3d1a4533999833928168ec0b0d703df36'};
 t.mock.module('../experiments/d2prl/model.js',{namedExports:{readVerifiedModelAsset:async()=>new TextEncoder().encode(JSON.stringify(manifest)),createD2prlModel:async()=>({async run(){inferences++;const release=budget.reserve(3*448**2*4);return {raw:new Float32Array(3*448**2).fill(.25),decision:{protocolFixture:true},execution:{protocolFixture:true},release};},releaseCheckpoint(key){checkpointReleases.push(key);},dispose(){}})}});
 t.mock.module('../experiments/d2prl/postprocess.js',{namedExports:{createPostprocess:()=>({dispose(){}})}});
 t.mock.module('../experiments/d2prl/spatial.js',{namedExports:{createSpatial:()=>({dispose(){}})}});
 t.mock.module('../src/d2prl-runtime.js',{namedExports:{d2prlRuntime:async()=>({})}});
 t.mock.module('../experiments/d2prl/zones.js',{namedExports:{createD2prlZones:()=>({async run(input){const n=input.width*input.height,release=budget.reserve(n*16+1024);return {width:input.width,height:input.height,map:new Float32Array(n).fill(input.zones[0].raw[0]),mask:new Uint8Array(n).fill(1),target:new Float32Array(n),source:new Float32Array(n),candidates:new Uint8Array(n),analyzed:new Uint8Array(n).fill(1),metadata:{min_component:input.minimum,boxes:input.zones.map(z=>z.bounds),exclusions:input.exclusions,zones:input.zones.map(({id,bounds})=>({id,bounds}))},release};}})}});
 const {createD2prlAdapter}=await import('../src/d2prl-adapter.js'),adapter=createD2prlAdapter({budget,profile:{maxWorkers:1},version:'ownership-proof'}),image={sha256:'source-fixture',pixels:{width:8,height:8,format:'rgb8',data:new Uint8Array(192)},provenance:{test:'protocol'}};
 await adapter.load({...D2PRL_MODEL_IDENTITY,url:'https://ownership.invalid/model.json'});const baseline=budget.active;
 const publicResult=await adapter.run({id:'public',imageId:'image',params:{minimum:0},backend:'cpu'},image,{checkpointKey:'owned-fixture'});assert.equal(inferences,1);assert.equal(checkpointReleases.length,1);assert.ok(checkpointReleases[0].includes('owned-fixture'));assert.equal(budget.active,baseline,'Existing public run releases delivery reservation');
 const owned=await adapter.runOwned({id:'owned',imageId:'image',params:{minimum:17,refilterOf:publicResult.data.metadata.analysisId},backend:'cpu'},image);assert.equal(inferences,1,'Actual analysis controller refilters without inference');assert.ok(budget.active>baseline);const raw=adapter.readRawOwned({imageId:'image',resultId:owned.data.metadata.resultId});assert.equal(raw.data.rawGrids[0].raw[0],.25);const pressure=budget.reserve(budget.limit-budget.active-budget.retained);assert.equal(budget.cacheBytes,0);pressure();const retained=adapter.readRawOwned({imageId:'image',resultId:owned.data.metadata.resultId});assert.equal(retained.data.rawGrids[0].raw[0],.25);retained.release();
 await adapter.dispose();assert.ok(budget.total()>0,'Consumers still own reservations after engine disposal');assert.equal(owned.data.map[0],.25);assert.equal(owned.data.metadata.min_component,17);assert.equal(raw.data.rawGrids[0].raw[0],.25);owned.release();owned.release();raw.release();raw.release();assert.equal(budget.total(),0);
 const {createAutomaticD2prlProvider}=await import('../src/automatic-d2prl-provider.js'),{automaticAnalysisPlan,automaticSelection}=await import('../src/automatic-analysis-plan.js'),{createAutomaticAnalysisSession}=await import('../src/automatic-analysis-session.js');
 const secondAdapter=createD2prlAdapter({budget,profile:{maxWorkers:1},version:'ownership-proof'});await secondAdapter.load({...D2PRL_MODEL_IDENTITY,url:'https://ownership.invalid/model.json'});const wasmBinary=await readFile(new URL('../vendor/clone-entries/clone-entries.wasm',import.meta.url)),plan=automaticAnalysisPlan({width:8,height:8,cpu:true,d2Minimum:0,...automaticSelection(8,8,[])});plan.jobs=plan.jobs.filter(j=>j.id==='d2prl');
 const provider=createAutomaticD2prlProvider({adapter:secondAdapter,image,imageId:'image',wasmBinary}),automatic=createAutomaticAnalysisSession({plan,providers:{d2prl:provider},budget});await automatic.run();assert.equal(inferences,2);const initial=await automatic.prepare();assert.equal(initial.entries.length,1);assert.equal(initial.entries[0].count,64);const sharedPressure=budget.reserve(budget.limit-budget.active-budget.retained);assert.equal(budget.cacheBytes,0);sharedPressure();const filtered=await automatic.prepare({d2Minimum:17});assert.equal(inferences,2);assert.equal(filtered.entries[0].provenance.min_component,17);assert.equal(filtered.entries[0].id,initial.entries[0].id);
 const {exportAutomaticSession}=await import('../src/automatic-session-export.js'),corroborationWasm=await readFile(new URL('../vendor/composition/composition.wasm',import.meta.url));
 const exported=await exportAutomaticSession(automatic,{image,filters:{d2Minimum:17},provenance:{scope:'protocol doubles, not neural parity'}},{storage:'memory'},{budget,wasmBinary:corroborationWasm});
 const exportedBytes=new Uint8Array(exported.byteLength);await exported.store.readInto(exportedBytes);const {unpackScientificNpz:unpack}=await import('./automatic-npz-fixture.js'),exportedArrays=unpack(exportedBytes),meta=JSON.parse(exportedArrays.metadata_json.text.replaceAll('Infinity','1e999'));
 assert.deepEqual(exportedArrays.root_results_d2prl_raw_probabilities.shape,[1,3,448,448]);assert.ok(exportedArrays.root_corroboration_counts.data.every(n=>n===1));assert.equal(meta.results.d2prl.metadata.min_component,0);assert.equal(meta.corroboration.d2prl_min_component,17);assert.equal(meta.biomes.length,1);assert.equal(inferences,2);await exported.dispose();
 const exportBaseline=budget.total(),cancelExport=new AbortController();await assert.rejects(exportAutomaticSession(automatic,{image,filters:{d2Minimum:17}},{storage:'memory'},{budget,wasmBinary:corroborationWasm,signal:cancelExport.signal,onProgress:p=>{if(p.phase==='automatic-npz')cancelExport.abort();}}),{code:'CANCELLED'});assert.equal(budget.total(),exportBaseline);
 const lease=automatic.acquireResults(),rawSnapshot=provider.readRaw(lease.values.d2prl);await automatic.dispose();await secondAdapter.dispose();
 const {automaticAiSnapshot}=await import('../src/automatic-ai-snapshot.js'),{streamAutomaticNpz}=await import('../src/automatic-npz-stream.js'),{unpackScientificNpz}=await import('./automatic-npz-fixture.js');
 const archive=await streamAutomaticNpz({results:{d2prl:automaticAiSnapshot('d2prl',lease.values.d2prl.result,{raw:rawSnapshot.value.result})}},{scope:'ownership protocol doubles, not inference parity'},{storage:'memory'},{budget});const bytes=new Uint8Array(archive.byteLength);await archive.store.readInto(bytes);const arrays=unpackScientificNpz(bytes);assert.deepEqual(arrays.root_results_d2prl_raw_probabilities.shape,[1,3,448,448]);assert.equal(arrays.root_results_d2prl_source.dtype,'<f4');await archive.dispose();await lease.release();assert.equal(rawSnapshot.value.result.rawGrids[0].raw[0],.25);assert.equal(initial.entries[0].pixel_mask.data.length,64);await initial.release();await filtered.release();rawSnapshot.release();assert.equal(budget.total(),0);

});
