import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Budget} from '../src/cache.js';
import {createParameterStore} from '../experiments/d2prl/parameter-store.js';
import {createD2prlRecovery} from '../experiments/d2prl/recovery.js';
import {createWasmTensorArena,isWasmTensorView} from '../src/wasm-tensor-arena.js';
const MiB=1024**2;
const fixture=(length=3*MiB)=>{const data=Uint8Array.from({length},(_,i)=>(i*7)%251),sha256=createHash('sha256').update(data).digest('hex');return{data,spec:{file:'assets/'+sha256+'.bin',sha256,bytes:length,dtype:'float32',shape:[length/4]}};};
function source(data,{faultAt=[],ignoreRange=false,requests=[]}={}){return async(_url,options)=>{const start=+(options.headers?.Range?.match(/\d+/)?.[0]??0);requests.push(start);const last=ignoreRange?data.length-1:+(options.headers?.Range?.match(/-(\d+)$/)?.[1]??data.length-1);let at=ignoreRange?0:start;return new Response(new ReadableStream({pull(c){if(faultAt.includes(at)){faultAt.splice(faultAt.indexOf(at),1);c.error(new TypeError('socket ended'));return;}if(at===last+1){c.close();return;}const end=Math.min(at+128*1024,last+1);c.enqueue(data.slice(at,end));at=end;}}),{status:start&&!ignoreRange?206:200,headers:start&&!ignoreRange?{'Content-Range':`bytes ${start}-${last}/${data.length}`}:{}});};}
test('weights stream to stable Wasm, reuse retained parameters, release exact ownership',async()=>{const {data,spec}=fixture(),budget=new Budget(64*MiB),requests=[],store=createParameterStore({budget,assetBaseUrl:'https://model/',fetchAsset:source(data,{requests})});const first=await store.acquire(spec,{retain:true}),view=first.data;assert.ok(isWasmTensorView(view));assert.deepEqual(new Uint8Array(view.buffer,view.byteOffset,view.byteLength),data);assert.equal(first.byteLength,data.length);first.release();assert.throws(()=>first.data);const second=await store.acquire(spec);assert.equal(second.data.buffer,view.buffer);assert.equal(requests.length,1);second.release();store.clear();store.dispose();assert.equal(budget.total(),0);assert.equal(budget.resourceSnapshot().domains.wasm.backings,0);});
for(const ignoreRange of [false,true])test('two network refusals preserve hashed prefix with '+(ignoreRange?'200 fallback':'validated Range'),async()=>{const {data,spec}=fixture(),budget=new Budget(64*MiB),requests=[],events=[],operation=createD2prlRecovery({budget,onRecovery:e=>events.push(e)}),store=createParameterStore({budget,operation,assetBaseUrl:'https://model/',fetchAsset:source(data,{requests,ignoreRange,faultAt:[512*1024,1536*1024]})});const value=await store.acquire(spec);assert.deepEqual(new Uint8Array(value.data.buffer,value.byteOffset,value.byteLength),data);assert.deepEqual(requests,[0,512*1024,1536*1024]);assert.equal(store.snapshot().committedBytes,data.length);assert.equal(events.length,2);value.release();store.dispose();assert.equal(budget.total(),0);});
test('allocation retry does not re-read committed data; terminal keeps prefix for explicit resume',async()=>{const {data,spec}=fixture(),budget=new Budget(64*MiB),requests=[];let failures=5;const base=createD2prlRecovery({budget}),operation=(label,work,options)=>base(label,()=>{if(label.startsWith('parameter:chunk:')&&store.snapshot().committedBytes>=512*1024&&failures-->0)throw new RangeError('Array buffer allocation failed');return work();},options);const store=createParameterStore({budget,operation,assetBaseUrl:'https://model/',fetchAsset:source(data,{requests})});await assert.rejects(store.acquire(spec),e=>e.details?.recovery?.loopDetected);assert.equal(store.snapshot().committedBytes,512*1024);const value=await store.acquire(spec);assert.deepEqual(requests,[0,512*1024]);assert.equal(store.snapshot().committedBytes,data.length);assert.deepEqual(new Uint8Array(value.data.buffer,value.byteOffset,value.byteLength),data);value.release();store.dispose();assert.equal(budget.total(),0);});
test('wrong size/hash/range never publish a parameter and cancellation clears incomplete banks',async()=>{for(const mode of ['digest','range','truncated','cancel']){const {data,spec}=fixture(),budget=new Budget(64*MiB),controller=new AbortController();let count=0;const store=createParameterStore({budget,assetBaseUrl:'https://model/',fetchAsset:async()=>{count++;if(mode==='range')return new Response(data,{status:206,headers:{'Content-Range':`bytes 1-${data.length}/${data.length}`}});return new Response(new ReadableStream({pull(c){if(mode==='cancel')controller.abort();c.enqueue(mode==='truncated'?data.subarray(0,4):data);c.close();}}));}});await assert.rejects(store.acquire(mode==='digest'?{...spec,sha256:'0'.repeat(64)}:spec,{signal:controller.signal}),e=>['MODEL_IDENTITY','CANCELLED'].includes(e.code));assert.equal(store.snapshot().entries,0);store.dispose();assert.equal(budget.total(),0);}});
test('initial Wasm refusal is retried without fetching and int64 offsets stay exact',async()=>{const {data,spec}=fixture(64),budget=new Budget(64*MiB),requests=[];let fail=true;const arena=createWasmTensorArena({budget,memoryFactory:desc=>{if(fail){fail=false;throw new RangeError('WebAssembly.Memory(): could not allocate memory');}return new WebAssembly.Memory(desc);}}),store=createParameterStore({budget,arena,operation:createD2prlRecovery({budget}),assetBaseUrl:'https://model/',fetchAsset:source(data,{requests})});const value=await store.acquire({...spec,dtype:'int64'});assert.ok(value.data instanceof BigInt64Array);assert.equal(value.data.length,8);assert.equal(requests.length,1);value.release();store.dispose();arena.dispose();assert.equal(budget.total(),0);});
test('different live parameter extents share one bank and one SHA instance without whole-heap views',async()=>{const first=fixture(12),second=fixture(64),budget=new Budget(64*MiB),store=createParameterStore({budget,assetBaseUrl:'https://model/',fetchAsset:async url=>new Response(url.includes(first.spec.sha256)?first.data:second.data)}),a=await store.acquire(first.spec),b=await store.acquire(second.spec);assert.equal(a.data.buffer,b.data.buffer);assert.equal(b.byteOffset,16);assert.equal(b.data.length,16);assert.deepEqual(new Uint8Array(b.data.buffer,b.byteOffset,b.byteLength),second.data);assert.equal(store.snapshot().hashInstances,1);assert.equal(budget.resourceSnapshot().domains.wasm.backings,2);a.release();store.dispose();assert.equal(b.byteLength,64);assert.equal(b.data.byteLength,64);b.release();assert.equal(budget.total(),0);});
test('an EOF network fault resumes at the final byte without hashing the prefix twice',async()=>{const {data,spec}=fixture(),budget=new Budget(64*MiB),requests=[],store=createParameterStore({budget,operation:createD2prlRecovery({budget}),assetBaseUrl:'https://model/',fetchAsset:source(data,{requests,faultAt:[data.length]})});const value=await store.acquire(spec);assert.deepEqual(requests,[0,data.length-1]);assert.equal(store.snapshot().committedBytes,data.length);value.release();store.dispose();assert.equal(budget.total(),0);});
test('chunk admission refusal holds the received bytes and retries admission without reopening HTTP',async()=>{const {data,spec}=fixture(),budget=new Budget(64*MiB),requests=[];let failures=2;const operation=createD2prlRecovery({budget,reclaim:async()=>1}),wrapped=(label,work,options)=>operation(label,()=>{if(label==='parameter:chunk-admission'&&failures>0&&failures--)throw new RangeError('Array buffer allocation failed');return work();},options),store=createParameterStore({budget,operation:wrapped,assetBaseUrl:'https://model/',fetchAsset:async()=>{requests.push(0);return new Response(data);}});const value=await store.acquire(spec);assert.equal(requests.length,1);assert.equal(failures,0);assert.equal(store.snapshot().committedBytes,data.length);value.release();store.dispose();assert.equal(budget.total(),0);});
test('large interrupted responses continue in bounded closed ranges accepted by the production host',async()=>{const {data,spec}=fixture(9*MiB),budget=new Budget(64*MiB),requests=[],store=createParameterStore({budget,operation:createD2prlRecovery({budget}),assetBaseUrl:'https://model/',fetchAsset:source(data,{requests,faultAt:[512*1024]})});const value=await store.acquire(spec);assert.deepEqual(requests,[0,512*1024,4*MiB+512*1024,8*MiB+512*1024]);assert.equal(store.snapshot().committedBytes,data.length);assert.deepEqual(new Uint8Array(value.data.buffer,value.byteOffset,value.byteLength),data);value.release();store.dispose();assert.equal(budget.total(),0);});
