import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {initJpegWasm} from '../src/jpeg.js';import {histogramEvidence,quantizationLattice} from '../src/double-jpeg.js';import {createEngine,exportAnalysis} from '../src/index.js';
const read=async name=>new Uint8Array(await readFile(new URL('../fixtures/'+name,import.meta.url)));
const compare=(actual,expected,label)=>{for(const [key,value] of Object.entries(expected)){if(key==='jpeglib_version')continue;if(Array.isArray(value)){assert.deepEqual(Array.from(actual[key]),value,label+'/'+key);}else if(typeof value==='number'&&!Number.isInteger(value)){assert.ok(Math.abs(actual[key]-value)<=1e-12,label+'/'+key);}else assert.equal(actual[key],value,label+'/'+key);}};
test('public segmented DCT adapter preserves the native evidence and owned cache',async()=>{
 await initJpegWasm({wasmBinary:await readFile(new URL('../vendor/libjpeg/jpeg.wasm',import.meta.url))});
 const ref=JSON.parse(new TextDecoder().decode(await read('double-jpeg-reference.json'))),engine=createEngine({memoryBudgetBytes:128*1024**2});
 try{for(const item of ref.cases){const bytes=await read(item.file),loaded=await engine.loadBlob({id:'paged',blob:new Blob([bytes]),layout:'segmented'});assert(loaded.availableOperations.includes('jpeg.multiple'));
  const task={id:'dct',imageId:'paged',operation:'jpeg.multiple'},result=await engine.run(task),{records,...expected}=item.expected;compare(result.data,expected,item.name);for(let i=0;i<9;i++)compare(result.data.records[i],records[i],item.name+'/'+i);
  result.data.records[0].histogram.fill(0);const cached=await engine.run(task);assert(cached.metrics.cache.result);assert.deepEqual([...cached.data.records[0].histogram],records[0].histogram);await engine.unload('paged');assert.equal(engine.capabilities().memory.activeReservationBytes,0);assert.equal(engine.capabilities().memory.cacheBytes,0);
 }}finally{await engine.dispose();}
});
test('Stored JPEG coefficients and lattice decisions match 13 native files and 335 histogram cases; cache and JSON preserve evidence',async()=>{
 await initJpegWasm({wasmBinary:await readFile(new URL('../vendor/libjpeg/jpeg.wasm',import.meta.url))});const ref=JSON.parse(new TextDecoder().decode(await read('double-jpeg-reference.json'))),engine=createEngine();
 try{for(const f of ref.cases){const bytes=await read(f.file);await engine.load({id:'i',bytes});const task={id:'dct',imageId:'i',operation:'jpeg.multiple'},r=await engine.run(task);const {records,...expected}=f.expected;compare(r.data,expected,f.name);for(let i=0;i<9;i++){compare(r.data.records[i],records[i],f.name+'/'+i);const record=r.data.records[i];if(record.eligible)assert.deepEqual(record.candidate_lattice,quantizationLattice(record.candidate_step,record.current_step));}assert.equal(r.pixels,undefined);assert.equal(r.provenance.originalSha256,r.data.source_sha256);const exported=JSON.parse(new TextDecoder().decode(exportAnalysis(r).bytes));assert.deepEqual(exported.data.records[0].histogram,records[0].histogram);r.data.records[0].histogram.fill(0);const again=await engine.run(task);assert.ok(again.metrics.cache.result);assert.deepEqual(Array.from(again.data.records[0].histogram),records[0].histogram);await engine.unload('i');assert.equal(engine.capabilities().memory.retainedBytes,0);assert.equal(engine.capabilities().memory.cacheBytes,0);}
 for(const [i,h] of ref.histograms.entries())compare(await histogramEvidence(h.histogram,h.q2),h.expected,'histogram/'+i);
 const f=ref.cases[4],bytes=await read(f.file);await engine.load({id:'original',bytes,pixels:{width:1,height:1,format:'rgb8',data:new Uint8Array(3)}});const r=await engine.run({id:'original-only',imageId:'original',operation:'jpeg.multiple'});assert.equal(r.data.verdict,f.expected.verdict,'Evidence must come from encoded coefficients even when caller pixels differ');assert.deepEqual(r.data.dimensions,f.expected.dimensions);await engine.unload('original');
 await engine.load({id:'not-jpeg',bytes:new Uint8Array([1,2,3,4]),pixels:{width:1,height:1,format:'rgb8',data:new Uint8Array(3)}});await assert.rejects(engine.run({id:'invalid',imageId:'not-jpeg',operation:'jpeg.multiple'}),{code:'UNSUPPORTED_FORMAT'});assert.equal(engine.capabilities().memory.activeReservationBytes,0);await engine.unload('not-jpeg');
 await engine.load({id:'truncated',bytes:bytes.slice(0,-200),pixels:{width:1,height:1,format:'rgb8',data:new Uint8Array(3)}});await assert.rejects(engine.run({id:'invalid',imageId:'truncated',operation:'jpeg.multiple'}),{code:'INVALID_INPUT'});assert.equal(engine.capabilities().memory.activeReservationBytes,0);
 }finally{engine.dispose();}
});
