import test from'node:test';import assert from'node:assert/strict';import{readFile,writeFile}from'node:fs/promises';import{gunzipSync}from'node:zlib';import{createHash}from'node:crypto';import{createEngine}from'../src/index.js';import{energyLogData}from'../src/energy-log-data.js';
const root=new URL('../fixtures/ela-energy/',import.meta.url),reference=JSON.parse(await readFile(new URL('pipeline.json',root))),compressed=await readFile(new URL(reference.payload.file,root)),payload=gunzipSync(compressed),bytes=part=>payload.subarray(part.offset,part.offset+part.length),sha=b=>createHash('sha256').update(b).digest('hex'),task={id:'energy',imageId:'image',operation:'ela.energy'};
function verify(actual,row){const d=actual.data;for(const key of ['energy_planes','energy_low_score','energy_high_score','energy_scope','energy_labels'])assert.deepEqual(new Uint8Array(d[key].buffer,d[key].byteOffset,d[key].byteLength),new Uint8Array(bytes(row[key])),row.name+' '+key);assert.deepEqual(d.energy_summary,row.summary,row.name+' summary');assert.deepEqual(d.regions,row.regions,row.name+' regions');assert.deepEqual(d.metadata.energy.automatic,row.automatic);assert.deepEqual(d.metadata.energy.quantiles,row.quantiles);assert.deepEqual(d.metadata.energy.thresholds,row.thresholds);for(const[key,value]of Object.entries(row.metadata))assert.deepEqual(d.metadata[key],value,row.name+' '+key);}
function readNpz(input){const view=new DataView(input.buffer,input.byteOffset,input.byteLength),decoder=new TextDecoder(),entries={};let at=0;while(view.getUint32(at,true)===0x04034b50){assert.equal(view.getUint16(at+8,true),0);const size=view.getUint32(at+18,true),length=view.getUint16(at+26,true),extra=view.getUint16(at+28,true),name=decoder.decode(input.subarray(at+30,at+30+length)),start=at+30+length+extra;assert.equal(decoder.decode(input.subarray(start+1,start+6)),'NUMPY');const headerLength=view.getUint16(start+8,true),header=decoder.decode(input.subarray(start+10,start+10+headerLength));entries[name]={header,bytes:input.slice(start+10+headerLength,start+size)};at=start+size;}return entries;}
test('51 actual API original-byte energy pipelines reproduce every native plane, score, label and region',async()=>{
 assert.equal(sha(compressed),reference.payload.compressedSha256);assert.equal(sha(payload),reference.payload.sha256);assert.equal(sha(new Uint8Array(energyLogData().buffer)),'aff6010f016381a1b499181f218ad90b8da34c77a3169f2e477efa56d52172d3');
 const engine=createEngine({memoryBudgetBytes:2*1024**3,cpuKernel:'single'});
 try{for(const source of reference.sources){const original=await readFile(new URL(source.file,root));assert.equal(sha(original),source.sha256);await engine.loadBlob({id:'image',blob:new Blob([original])});assert.deepEqual(engine.imagePixels('image').data,new Uint8Array(bytes(source.pixels)),source.name+' decode');
  for(const row of reference.cases.filter(x=>x.source===source.name)){const result=await engine.run({...task,params:row.params});verify(result,row);assert.equal(result.provenance.originalSha256,source.sha256);assert.equal(result.metrics.memory.activeReservationBytes,0);assert.deepEqual(engine.original('image'),new Uint8Array(original));}
  engine.unload('image');assert.equal(engine.capabilities().memory.cacheBytes,0);
 }}finally{engine.dispose();}
});
test('Energy stage caches reuse recompressions and scores, results/NPZ/JSON retain owned exact arrays',async()=>{
 const source=reference.sources.find(x=>x.name==='composite'),row=reference.cases.find(x=>x.source===source.name&&x.params.profile==='standard'),original=await readFile(new URL(source.file,root)),engine=createEngine({memoryBudgetBytes:512*1024**2});
 try{await engine.loadBlob({id:'image',blob:new Blob([original])});const first=await engine.run({...task,params:row.params});assert.equal(first.metrics.energyRecompressions,3);const exported=engine.exportResult(first,{format:'npz'}),entries=readNpz(exported.bytes);
  for(const key of ['energy_planes','energy_low_score','energy_high_score','energy_scope','energy_labels']){assert.deepEqual(entries[key+'.npy'].bytes,new Uint8Array(bytes(row[key])));assert.ok(entries[key+'.npy'].header.includes(key.endsWith('scope')||key.endsWith('labels')?"'<i4'":"'<f4'"));}
  const json=JSON.parse(new TextDecoder().decode(engine.exportResult(first).bytes));assert.deepEqual(json.data.regions,row.regions);assert.equal(json.provenance.originalSha256,source.sha256);await writeFile(new URL('../.build/ela-energy-export.npz',import.meta.url),exported.bytes);
  first.data.energy_low_score[0]=999;first.data.energy_labels[0]=999;const cached=await engine.run({...task,params:row.params});assert.ok(cached.metrics.cache.result);verify(cached,row);
  const edited=await engine.run({...task,params:{...row.params,profile:'manual',shadow:10,minimum:1}});assert.equal(edited.metrics.energyRecompressions,0);assert.equal(edited.metrics.energyPreparationMs,0);assert.ok(Object.entries(edited.metrics.cache.stages).some(([key,hit])=>key.startsWith('energy-scores/')&&hit));
  assert.equal(first.metrics.energyPanelDetections,1);
  const bounds=await engine.run({...task,params:{...row.params,profile:'manual',histogramLow:100,histogramHigh:900}});assert.equal(bounds.metrics.energyRecompressions,0);assert.equal(bounds.metrics.energyPanelDetections,0);assert.equal(bounds.metrics.cache.stages['energy-panels'],true);assert.ok(bounds.metrics.energyPreparationMs>0);assert.deepEqual(bounds.data.energy_scope,cached.data.energy_scope);
  await assert.rejects(engine.run({...task,params:{profile:'standard',shadow:20}}),{code:'INVALID_INPUT'});await assert.rejects(engine.run({...task,backend:'webgpu'}),{code:'UNSUPPORTED_BACKEND'});await assert.rejects(engine.run({...task,regions:[{}]}),{code:'UNSUPPORTED_REGION'});assert.throws(()=>engine.exportResult(cached,{format:'npz',maxBytes:1}),{code:'MEMORY_LIMIT'});
 }finally{engine.dispose();}
});
test('Energy calculation cancels during useful work, releases reservations and succeeds after retry',async()=>{
 const source=reference.sources.at(-1),row=reference.cases.find(x=>x.source===source.name),original=await readFile(new URL(source.file,root)),engine=createEngine({memoryBudgetBytes:1024**3});
 try{await engine.loadBlob({id:'image',blob:new Blob([original])});const controller=new AbortController();await assert.rejects(engine.run({...task,params:row.params},{signal:controller.signal,onProgress:event=>{if(event.fraction>0&&event.fraction<1)controller.abort();}}),{code:'CANCELLED'});assert.equal(engine.capabilities().memory.activeReservationBytes,0);verify(await engine.run({...task,params:row.params}),row);
 }finally{engine.dispose();}
});

test('Shared engine budget refuses energy workspace without altering or losing the original',async()=>{
 const source=reference.sources.find(x=>x.name==='composite'),original=await readFile(new URL(source.file,root)),pixels={width:source.width,height:source.height,format:'rgb8',data:new Uint8Array(bytes(source.pixels))},probe=createEngine(),resident=Math.max(32*1024**2,probe.capabilities().memory.knownHeapCapacityBytes);probe.dispose();
 const engine=createEngine({memoryBudgetBytes:resident+original.length*3+pixels.width*pixels.height*24+8*1024**2});
 try{await engine.load({id:'image',bytes:new Uint8Array(original),pixels});await assert.rejects(engine.run({...task,params:{block:16}}),{code:'MEMORY_LIMIT'});assert.equal(engine.capabilities().memory.activeReservationBytes,0);assert.deepEqual(engine.original('image'),new Uint8Array(original));await engine.unload('image');assert.equal(engine.capabilities().memory.cacheBytes,0);}finally{engine.dispose();}
});
