import test from 'node:test';import assert from 'node:assert/strict';import {crc32} from 'node:zlib';import {createHash} from 'node:crypto';
import {streamEnergyNpz} from '../src/energy-npz-stream.js';import {energyNpz} from '../src/npz.js';import {Budget} from '../src/cache.js';
test('progressive energy NPZ is byte-identical to contiguous scientific export across quality boundaries',async()=>{
 const width=259,height=193,n=width*height,data={width,height,metadata:{profile:'énergie 🧪',quality:75}},provenance={test:'native typed arrays'},budget=new Budget(16*1024**2),store=typed=>({byteLength:typed.byteLength,readInto(out,at){out.set(new Uint8Array(typed.buffer,typed.byteOffset+at,out.length));}});
 for(const key of ['energy_planes','energy_low_score','energy_high_score','energy_scope','energy_labels']){const Type=['energy_scope','energy_labels'].includes(key)?Int32Array:Float32Array;data[key]=Type.from({length:(key==='energy_planes'?3:1)*n},(_,i)=>i%17-7+(Type===Float32Array?1/9:0));}
 const analysis={...data,energy_planes:[0,1,2].map(q=>store(data.energy_planes.subarray(q*n,(q+1)*n)))};for(const key of ['energy_low_score','energy_high_score','energy_scope','energy_labels'])analysis[key]=store(data[key]);let result;
 try{result=await streamEnergyNpz(analysis,provenance,{storage:'memory'},{budget});const bytes=new Uint8Array(result.byteLength);await result.store.readInto(bytes,0);assert.deepEqual(bytes,energyNpz({data,provenance},16*1024**2).bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),result.sha256);const view=new DataView(bytes.buffer);let at=0,count=0;while(view.getUint32(at,true)===0x04034b50){const length=view.getUint16(at+26,true),size=view.getUint32(at+18,true),start=at+30+length;assert.equal(crc32(bytes.subarray(start,start+size)),view.getUint32(at+14,true));at=start+size;count++;}assert.equal(count,7);}
 finally{await result?.store.dispose();await result?.session?.dispose();}assert.equal(budget.total(),0);await assert.rejects(streamEnergyNpz(analysis,provenance,{maxBytes:10},{budget}),{code:'EXPORT_LIMIT'});const controller=new AbortController();await assert.rejects(streamEnergyNpz(analysis,provenance,{}, {budget,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),0);
});
