import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {prepareSegmentedEnergy} from '../src/energy-prepare-stream.js';import {Budget} from '../src/cache.js';import {createRgbSurface} from '../src/rgb-surface.js';import {detectPanels} from '../src/auto-zones.js';import {referenceLogFunction} from '../src/energy-log-reference.js';import {prepareEnergy} from '../src/energy-prepare.js';
const root=new URL('../fixtures/ela-energy/',import.meta.url),ref=JSON.parse(await readFile(new URL('preparation.json',root))),payload=gunzipSync(await readFile(new URL(ref.payload.file,root))),log=referenceLogFunction(JSON.parse(await readFile(new URL('log-domain.json',root))),gunzipSync(await readFile(new URL('log-corrections.bin.gz',root))));const bytes=part=>payload.subarray(part.offset,part.offset+part.length),store=data=>({byteLength:data.byteLength,readInto(out,offset){out.set(data.subarray(offset,offset+out.length));}});
async function read(s){const output=new Uint8Array(s.byteLength);await s.readInto(output);return output;}
test('segmented preparation reproduces all 84 native energy maps, scopes and summaries with explicit panels',async()=>{
 for(const row of ref.cases){const budget=new Budget(32*1024**2),rgb=bytes(row.image),p=bytes(row.planes),n=row.width*row.height,image={surface:createRgbSurface(store(rgb),{width:row.width,height:row.height,budget,ownsStore:false})},original={width:row.width,height:row.height,format:'rgb8',data:rgb},planes=[0,1,2].map(q=>store(p.subarray(q*n*4,(q+1)*n*4)));let result;
  try{const polygons=await detectPanels(original);result=await prepareSegmentedEnergy(image,planes,row.quantiles,log,{budget,polygons});assert.deepEqual(result.energy_summary,row.summary,row.name+' summaries');for(const key of ['energy_low_score','energy_high_score','energy_scope'])assert.deepEqual(await read(result[key]),new Uint8Array(bytes(row[key])),row.name+' '+key);}finally{await result?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
 }
});
test('overlapping panels keep native overwrite order, skipped identities, and final median',async()=>{
 const width=97,height=97,n=width*height,rgb=new Uint8Array(n*3).fill(90),planes=Float32Array.from({length:n*3},(_,i)=>(i%113)/9),polygons=[[[0,0],[1,0],[1,1],[0,1]],[[2,2],[65,2],[65,65],[2,65]],[[40,20],[90,20],[90,90],[40,90]]],budget=new Budget(32*1024**2),image={surface:createRgbSurface(store(rgb),{width,height,budget,ownsStore:false})};let result;
 try{const expected=await prepareEnergy({width,height,format:'rgb8',data:rgb},planes,[.01,.99],log,{panelDetector:async()=>polygons});result=await prepareSegmentedEnergy(image,[0,1,2].map(q=>store(new Uint8Array(planes.buffer,q*n*4,n*4))),[.01,.99],log,{budget,polygons});assert.deepEqual(result.energy_summary,expected.energy_summary);assert.deepEqual(result.energy_summary.map(s=>s.id),[2,3]);for(const key of ['energy_low_score','energy_high_score','energy_scope'])assert.deepEqual(await read(result[key]),new Uint8Array(expected[key].buffer));}finally{await result?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
});
test('preparation validates invalid values even outside panels and cleans every cancelled stage',async()=>{
 const width=97,height=97,n=width*height,rgb=new Uint8Array(n*3).fill(90),plane=new Float32Array(n).fill(7),planes=[0,1,2].map(()=>store(new Uint8Array(plane.buffer))),budget=new Budget(32*1024**2),image={surface:createRgbSurface(store(rgb),{width,height,budget,ownsStore:false})};
 try{await assert.rejects(prepareSegmentedEnergy(image,planes,[.01,.99],log,{budget}),{code:'INVALID_INPUT'});plane[n-1]=NaN;await assert.rejects(prepareSegmentedEnergy(image,planes,[.01,.99],log,{budget,polygons:[[[0,0],[40,0],[40,40],[0,40]]]}),{code:'INVALID_INPUT'});assert.equal(budget.total(),0);plane[n-1]=7;
  for(const phase of ['energy-valid','energy-panel-mean','energy-panel-scores','energy-quality-median']){const controller=new AbortController();await assert.rejects(prepareSegmentedEnergy(image,planes,[.01,.99],log,{budget,polygons:[],signal:controller.signal,onProgress:e=>{if(e.phase===phase)controller.abort();}}),{code:'CANCELLED'});assert.equal(budget.total(),0);}await assert.rejects(prepareSegmentedEnergy(image,planes,[.01,.99],log,{budget:new Budget(1),polygons:[]}),{code:'MEMORY_LIMIT'});
 }finally{await image.surface.dispose();}
});
