import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {Budget} from '../src/cache.js';import {segmentSegmentedEnergy} from '../src/energy-segment-stream.js';import {segmentEnergy} from '../src/energy-segment.js';import {selectFloat32Ranks} from '../src/float32-ranks-stream.js';
const root=new URL('../fixtures/ela-energy/',import.meta.url),ref=JSON.parse(await readFile(new URL('segmentation.json',root))),payload=gunzipSync(await readFile(new URL(ref.payload.file,root))),bytes=part=>payload.subarray(part.offset,part.offset+part.length),store=data=>({byteLength:data.byteLength,readInto(out,at){out.set(data.subarray(at,at+out.length));}});
function base(row){const b={width:row.width,height:row.height,metadata:{block:row.block},energy_summary:row.summary};for(const key of ['energy_scope','energy_low_score','energy_high_score','energy_allowed'])if(row[key])b[key]=store(bytes(row[key]));return b;}
test('paged global energy hysteresis preserves every native label and region summary',async()=>{
 for(const row of ref.cases){const budget=new Budget(32*1024**2);let r;try{r=await segmentSegmentedEnergy(base(row),{thresholds:row.thresholds,minimum:row.minimum,offset:row.offset},{budget});const actual=new Uint8Array(r.labels.byteLength);await r.labels.readInto(actual);assert.deepEqual(actual,new Uint8Array(bytes(row.labels)),row.name+' labels');assert.deepEqual(r.regions,row.regions,row.name+' regions');}finally{await r?.dispose();}assert.equal(budget.total(),0);}
});
test('exact float32 rank selection retains wide domain, duplicate ranks and native even-median rounding',async()=>{
 const values=Float32Array.of(0,1000,3e38,17,17),budget=new Budget(2*1024**2),data=new Uint8Array(values.buffer);assert.deepEqual(await selectFloat32Ranks(store(data),5,[4,0,2,2],{budget}),[values[2],0,17,17]);assert.equal(budget.total(),0);
 const n=256,score=new Float32Array(n).fill(values[2]),scope=new Int32Array(n).fill(1),original={width:16,height:16,metadata:{block:1},energy_summary:[{id:1,bbox:[0,0,16,16]}],energy_scope:scope,energy_low_score:score,energy_high_score:new Float32Array(n)},expected=await segmentEnergy(original,{minimum:1});let r;
 const wide=new Budget(16*1024**2);try{r=await segmentSegmentedEnergy({...original,...Object.fromEntries(['energy_scope','energy_low_score','energy_high_score'].map(k=>[k,store(new Uint8Array(original[k].buffer))]))},{minimum:1},{budget:wide});assert.deepEqual(r.regions,expected.regions);assert.equal(r.regions[0].score,Infinity);}finally{await r?.dispose();}assert.equal(wide.total(),0);
});
test('invalid maps, admission, cancellation and consumer errors leave no unpublished region stores',async()=>{
 const row=ref.cases.find(r=>r.regions.length>0),input=base(row),budget=new Budget(32*1024**2);await assert.rejects(segmentSegmentedEnergy(input,{thresholds:[-1,0]},{budget}),{code:'INVALID_INPUT'});await assert.rejects(segmentSegmentedEnergy(input,{}, {budget:new Budget(1)}),{code:'MEMORY_LIMIT'});const controller=new AbortController();await assert.rejects(segmentSegmentedEnergy(input,{thresholds:[0,0],minimum:0},{budget,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),0);await assert.rejects(segmentSegmentedEnergy(input,{thresholds:[0,0],minimum:0},{budget,onProgress:()=>{throw Error('consumer');}}),/consumer/);assert.equal(budget.total(),0);
});
