import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {Budget} from '../src/cache.js';import {estimateSegmentedEnergy,segmentedEnergyDeviations} from '../src/energy-auto-stream.js';import {referenceLogFunction} from '../src/energy-log-reference.js';
const root=new URL('../fixtures/ela-energy/',import.meta.url),ref=JSON.parse(await readFile(new URL('automatic.json',root))),payload=gunzipSync(await readFile(new URL(ref.payload.file,root))),log=referenceLogFunction(JSON.parse(await readFile(new URL('log-domain.json',root))),gunzipSync(await readFile(new URL('log-corrections.bin.gz',root))));const bytes=part=>payload.subarray(part.offset,part.offset+part.length),store=data=>({byteLength:data.byteLength,readInto(out,at){out.set(data.subarray(at,at+out.length));}});
test('segmented scientific profile sampling preserves every native estimate and one-sided Otsu threshold',async()=>{
 for(const row of ref.estimates){const budget=new Budget(8*1024**2),data=bytes(row.planes),n=row.scope.length/4,planes=[0,1,2].map(q=>store(data.subarray(q*n*4,(q+1)*n*4)));assert.deepEqual(await estimateSegmentedEnergy({energy_planes:planes,energy_scope:store(bytes(row.scope)),energy_summary:row.summary},log,{budget}),row.result,row.name);assert.equal(budget.total(),0);}
 for(const row of ref.deviations){const budget=new Budget(8*1024**2);assert.deepEqual(await segmentedEnergyDeviations({energy_low_score:store(bytes(row.low)),energy_high_score:store(bytes(row.high))},{budget}),row.result,row.name);assert.equal(budget.total(),0);}
});
test('profile sample errors, refusal and cancellation release all owned buffers',async()=>{
 const row=ref.estimates.at(-1),data=bytes(row.planes),n=row.scope.length/4,base={energy_planes:[0,1,2].map(q=>store(data.subarray(q*n*4,(q+1)*n*4))),energy_scope:store(bytes(row.scope)),energy_summary:row.summary},budget=new Budget(8*1024**2);
 await assert.rejects(estimateSegmentedEnergy({...base,energy_summary:[{id:1},{id:1}]},log,{budget}),{code:'INVALID_INPUT'});assert.equal(budget.total(),0);await assert.rejects(estimateSegmentedEnergy(base,log,{budget:new Budget(1)}),{code:'MEMORY_LIMIT'});const controller=new AbortController();await assert.rejects(estimateSegmentedEnergy(base,log,{budget,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),0);const broken={...base,energy_scope:{byteLength:base.energy_scope.byteLength,readInto(){throw Error('storage');}}};await assert.rejects(estimateSegmentedEnergy(broken,log,{budget}),/storage/);assert.equal(budget.total(),0);
});
