import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {frequencyStreamMath} from '../src/frequency-stream-math.js';import {cvFrequencyMask,initCvWasm} from '../src/opencv.js';import {gray} from '../src/pixel-utils.js';
test('strip polar normalization and circle Gaussian axes preserve native frequency bases and masks',async()=>{
 await initCvWasm({wasmBinary:await fs.readFile(new URL('../vendor/opencv/opencv.wasm',import.meta.url))});const math=await frequencyStreamMath(),ref=JSON.parse(await fs.readFile(new URL('../fixtures/frequency-reference.json',import.meta.url)));
 for(const c of ref.cases){const rgb=await fs.readFile(new URL('../fixtures/'+c.file,import.meta.url)),[height,width]=c.baseShape,padded=new Float32Array(width*height);for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*3;padded[y*width+x]=gray(rgb[i],rgb[i+1],rgb[i+2]);}
  const dft=math.full(padded,width,height),shifted=new Float32Array(dft.length);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const dst=(((y+Math.floor(height/2))%height)*width+(x+Math.floor(width/2))%width)*2,src=(y*width+x)*2;shifted.set(dft.subarray(src,src+2),dst);}
  const polar=math.polar(shifted),parts=[0,1].map(k=>Float32Array.from({length:width*height},(_,i)=>polar[i*2+k]));for(let k=0;k<2;k++)parts[k]=math.normalize(parts[k],Math.min(...parts[k]),Math.max(...parts[k]));const base=Float32Array.from({length:width*height*4},(_,i)=>i%4<2?shifted[Math.floor(i/4)*2+i%4]:parts[i%4-2][Math.floor(i/4)]),b=await fs.readFile(new URL('../fixtures/'+c.baseFile,import.meta.url));assert.deepEqual(new Uint8Array(base.buffer),new Uint8Array(b),c.name+' base');
  for(const [split,smooth]of [[0,0],[15,25],[100,100],[45,1]]){const horizontal=new Float32Array(width*height);for(let y=0;y<height;y+=3)horizontal.set(math.maskHorizontal(width,height,y,Math.min(3,height-y),split,smooth),y*width);const columns=new Float32Array(horizontal.length);for(let x=0;x<width;x++)for(let y=0;y<height;y++)columns[x*height+y]=horizontal[y*width+x];const vertical=math.maskVertical(columns,width,height,width,smooth),mask=new Float32Array(columns.length);for(let x=0;x<width;x++)for(let y=0;y<height;y++)mask[y*width+x]=vertical[x*height+y];assert.deepEqual(mask,await cvFrequencyMask(width,height,split,smooth,2),c.name+' mask');}
 }
});
