import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {initCvWasm,cvFrequencyBase} from '../src/opencv.js';import {createEngine} from '../src/index.js';
test('Frequency split preserves 4320 native views, float32 base and threshold decisions; filter changes reuse analysis',async()=>{
 await initCvWasm({wasmBinary:await readFile(new URL('../vendor/opencv/opencv.wasm',import.meta.url))});const ref=JSON.parse(await readFile(new URL('../fixtures/frequency-reference.json',import.meta.url))),engine=createEngine(),hash=a=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');let count=0;
 try{for(const f of ref.cases){const data=new Uint8Array(await readFile(new URL('../fixtures/'+f.file,import.meta.url))),image={width:f.width,height:f.height,format:'rgb8',data},base=await cvFrequencyBase(image),expected=await readFile(new URL('../fixtures/'+f.baseFile,import.meta.url));assert.equal(hash(base.values),hash(expected),'frequency base '+f.name);await engine.load({id:'i',bytes:data,pixels:image});let last,first=true;
  for(const e of f.expected){const r=await engine.run({id:'f',imageId:'i',operation:'detail.frequency',params:e.params}),key=JSON.stringify([e.params.split,e.params.smooth,e.params.threshold]);assert.equal(r.metrics.cache.analysis,last===key);if(last!==key){assert.equal(r.metrics.cache.stages.dft,!first);first=false;}last=key;
   const frames=[r.pixels,r.data.high,r.data.magnitude,r.data.phase];for(let i=0;i<4;i++){assert.equal(hash(frames[i].data),e.sha256[i],f.name+' '+JSON.stringify(e.params)+' '+i);count++;}assert.equal(r.data.zeroPercent,e.zeroPercent);assert.deepEqual(r.data.frequencyDimensions,[f.baseShape[1],f.baseShape[0]]);assert.equal(r.layers[3].field,'data.phase');r.data.mask.data.fill(0);r.data.high.data.fill(0);
  }engine.unload('i');assert.equal(engine.capabilities().memory.cacheBytes,0);
 }assert.equal(count,4320);}finally{engine.dispose();}
});
