import {createWorkerEngine} from '../src/worker-client.js';
const read=async name=>new Uint8Array(await(await fetch('/fixtures/'+name)).arrayBuffer()),json=async name=>JSON.parse(new TextDecoder().decode(await read(name)));
const hash=async a=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a)),x=>x.toString(16).padStart(2,'0')).join('');
const assert=(v,m)=>{if(!v)throw new Error(m);};
export async function ghostBrowserTest(){
 const ref=await json('ghost-reference.json'),engine=createWorkerEngine({resourceHints:{hardwareConcurrency:4}}),report={schema:1,status:'passed',maps:0,previewPlanes:0,large:[],limits:['Synthetic maps and per-plane palettes; native Matplotlib plot layout is not reproduced']};
 try{for(const f of ref.cases){const bytes=await read(f.file);await engine.load({id:'i',bytes,pixels:{width:f.width,height:f.height,format:'rgb8',data:bytes}});for(const e of f.expected){const task={id:'g',imageId:'i',operation:'jpeg.ghosts',params:e.params},r=await engine.run(task);assert(await hash(r.data.raw)===e.rawSha256,'Ghost raw '+f.name);assert(await hash(r.data.maps)===e.sha256,'Ghost normalization '+f.name);report.maps++;for(let i=0;i<r.data.views.length;i++){assert(await hash(r.data.views[i].pixels.data)===e.previews.gray[i],'Ghost gray palette');report.previewPlanes++;}r.data.maps.fill(-1);const colored=await engine.run({...task,params:{...e.params,grayscale:false,includeOriginal:true}});assert(colored.metrics.cache.analysis&&await hash(colored.data.maps)===e.sha256,'Owned map cache');for(let i=0;i<colored.data.views.length;i++){assert(await hash(colored.data.views[i].pixels.data)===e.previews.viridis[i],'Ghost viridis palette');report.previewPlanes++;}}
 await engine.unload('i');console.log('Ghost qualified',f.name);}
 const large=await json('ghost-large-reference.json'),bytes=await read(large.file);await engine.load({id:'large',bytes});for(const e of large.expected){const r=await engine.run({id:'pool',imageId:'large',operation:'jpeg.ghosts',params:e.params});assert(await hash(r.data.raw)===e.raw&&await hash(r.data.maps)===e.maps,'Large Ghost pool parity');assert(r.metrics.scheduling.preflightExecutions===0&&r.metrics.scheduling.taskExecutions===1,'Ghost one useful pass without preflight');report.large.push({params:e.params,workers:r.metrics.workers,metrics:r.metrics});}
 const again=await engine.run({id:'cache',imageId:'large',operation:'jpeg.ghosts',params:{...large.expected[2].params,grayscale:false}});assert(again.metrics.cache.analysis,'No repeated JPEG work for palette change');
 const subset=await engine.run({id:'subset',imageId:'large',operation:'jpeg.ghosts',params:{...large.expected[2].params,low:55,high:85}});assert(Object.entries(subset.metrics.cache.stages).filter(([k])=>k.startsWith('blocks/')).every(([,hit])=>hit),'Subset reuses quality blocks');
 const controller=new AbortController();let cancelled=false;try{await engine.run({id:'abort',imageId:'large',operation:'jpeg.ghosts',params:{x:2,y:2}},{signal:controller.signal,onProgress:()=>controller.abort()});}catch(e){cancelled=e.code==='CANCELLED'&&e.imagesCleared;}assert(cancelled,'Ghost pool cancellation');await engine.load({id:'large',bytes});const recovery=await engine.run({id:'recovery',imageId:'large',operation:'jpeg.ghosts',params:{low:75,high:75}});assert(recovery.data.qualities.length===1,'Recovery');await engine.unload('large');const memory=(await engine.capabilities()).memory;assert(memory.retainedBytes===0&&memory.cacheBytes===0&&memory.activeReservationBytes===0,'Ghost pool released');report.cancellation='Parallel abort and source reload verified';return report;
 }finally{engine.dispose();}
}
