import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {initJpegWasm} from '../src/jpeg.js';import {createEngine} from '../src/index.js';
const hash=a=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');
test('Ghost maps retain native raw float64 block means and normalized cubes across quality endpoints and phase rolls',async()=>{
 await initJpegWasm({wasmBinary:await readFile(new URL('../vendor/libjpeg/jpeg.wasm',import.meta.url))});const ref=JSON.parse(await readFile(new URL('../fixtures/ghost-reference.json',import.meta.url))),engine=createEngine();
 try{for(const f of ref.cases){const bytes=new Uint8Array(await readFile(new URL('../fixtures/'+f.file,import.meta.url)));await engine.load({id:'i',bytes,pixels:{width:f.width,height:f.height,format:'rgb8',data:bytes}});
  for(const e of f.expected){const task={id:'ghost',imageId:'i',operation:'jpeg.ghosts',params:e.params},r=await engine.run(task);assert.equal(hash(r.data.raw),e.rawSha256,f.name+' raw '+JSON.stringify(e.params));assert.equal(hash(r.data.maps),e.sha256,f.name+' maps '+JSON.stringify(e.params));assert.deepEqual([r.data.rows,r.data.cols,r.data.qualities.length],e.shape);assert.equal(r.data.views.length,e.shape[2]);for(let i=0;i<r.data.views.length;i++)assert.equal(hash(r.data.views[i].pixels.data),e.previews.gray[i]);r.data.maps.fill(-1);const again=await engine.run({...task,params:{...e.params,grayscale:false,includeOriginal:true}});assert.ok(again.metrics.cache.analysis);assert.equal(hash(again.data.maps),e.sha256);assert.deepEqual(again.data.original.data,bytes);for(let i=0;i<again.data.views.length;i++)assert.equal(hash(again.data.views[i].pixels.data),e.previews.viridis[i]);assert.equal(again.layers[0].field,'data.original');}
  await engine.unload('i');assert.equal(engine.capabilities().memory.cacheBytes,0);
 }await engine.load({id:'small',bytes:new Uint8Array([1]),pixels:{width:1,height:1,format:'rgb8',data:new Uint8Array(3)}});await assert.rejects(engine.run({id:'small',imageId:'small',operation:'jpeg.ghosts'}),{code:'INVALID_INPUT'});await assert.rejects(engine.run({id:'wrong',imageId:'small',operation:'jpeg.ghosts',params:{low:90,high:20}}),{code:'INVALID_INPUT'});
 }finally{engine.dispose();}
});
