import test from 'node:test';import assert from 'node:assert/strict';import{createHash}from'node:crypto';
import{Budget}from'../src/cache.js';import{createSegmentedBytes}from'../src/segmented-bytes.js';import{createRgbSurface}from'../src/rgb-surface.js';import{orientRgb}from'../src/image-headers.js';import{createNeuralInput}from'../src/neural-input.js';import{createD2prlAnalysis}from'../experiments/d2prl/analysis.js';import{createSegmentationAnalysis}from'../experiments/segmentation/analysis.js';
const hash=a=>createHash('sha256').update(a).digest('hex');
async function source(budget,orientation=1){const width=31,height=27,data=Uint8Array.from({length:width*height*3},(_,i)=>i*31^(i>>>3)),store=await createSegmentedBytes(data.length,{budget,chunkBytes:113});await store.write(data);const surface=createRgbSurface(store,{width,height,budget,orientation});return{data,width,height,surface,input:createNeuralInput(surface,{budget})};}
test('Canonical neural identity hashes oriented RGB, memoizes only completed reads and releases every window',async()=>{
 for(let o=1;o<=8;o++){const budget=new Budget(8*1024**2),s=await source(budget,o);try{const expected=await orientRgb({...s,format:'rgb8'},o),before=budget.total();let events=0;assert.equal(await s.input.sha256({onProgress:()=>events++}),hash(expected.data));assert.ok(events>0);assert.equal(await s.input.sha256({onProgress:()=>assert.fail('Rehashed immutable source')}),hash(expected.data));assert.equal(budget.total(),before);const rows=s.input.region([3,5,15,21]),v=await rows.readRows(2,3);try{for(let y=0;y<3;y++)assert.deepEqual(v.pixels.data.subarray(y*36,(y+1)*36),expected.data.subarray(((y+7)*expected.width+3)*3,((y+7)*expected.width+15)*3));}finally{v.release();}}finally{await s.surface.dispose();}assert.equal(budget.total(),0);}
 const budget=new Budget(8*1024**2),s=await source(budget),before=budget.total(),abort=new AbortController();await assert.rejects(s.input.sha256({signal:abort.signal,onProgress:()=>abort.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),before);budget.limit=before+1;await assert.rejects(s.input.sha256(),{code:'MEMORY_LIMIT'});budget.limit=8*1024**2;assert.equal(await s.input.sha256(),hash(s.data));await s.surface.dispose();assert.equal(budget.total(),0);
});
test('Both controllers consume real row crops, keep only serializable context and recompose cached grids',async()=>{
 for(const family of ['d2prl','segmentation']){const budget=new Budget(32*1024**2),s=await source(budget),zones=[{id:'a',kind:'region',bounds:[3,5,23,25]},{id:'b',kind:'region',bounds:[11,7,31,27]}];let calls=0,projections=0;
  const consume=async input=>{assert.equal(input.rgb??input.data,undefined);const v=await input.readRows(0,input.height);try{const b=zones[calls].bounds;for(let y=0;y<20;y++)assert.deepEqual(v.pixels.data.subarray(y*60,(y+1)*60),s.data.subarray(((y+b[1])*31+b[0])*3,((y+b[1])*31+b[0]+20)*3));}finally{v.release();}calls++;};
  const project={async run(input){assert.equal(input.layout,'segmented');projections++;return{metadata:{exclusions:input.exclusions??[],zones:input.zones.map(({id,bounds})=>({id,bounds}))},async release(){}};}};
  const session=family==='d2prl'?createD2prlAnalysis({budget,modelId:'test-control-only',project,infer:async input=>{await consume(input);return{raw:new Float32Array(3*448**2),release(){}};}}):createSegmentationAnalysis({budget,project,prepare:{async run(input){await consume(input);return{tensor:new Float32Array(3*256**2),release(){}};}},inference:{model:{side:256,kind:'sigmoid',id:'test-control-only'},async run(){return{raw:new Float32Array(256**2),release(){}};}}});
  try{const first=await session.run({inputSource:s.input,zones});assert.equal(calls,2);await first.release();const view=family==='d2prl'?await session.refilter({analysisId:first.metadata.analysisId,minimum:17,exclusions:[[0,0,8,8]]}):await session.reproject({analysisId:first.metadata.analysisId,zoneIds:['b']});assert.equal(view.metadata.inferences,0);assert.equal(calls,2);assert.equal(projections,2);await view.release();const raw=session.readRaw(view.metadata.resultId);assert.equal(raw.rawGrids.length,family==='d2prl'?2:1);raw.release();}finally{await session.dispose();await s.surface.dispose();}assert.equal(budget.total(),0);
 }
});
