import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{Budget}from'../src/cache.js';import{createSegmentedBytes}from'../src/segmented-bytes.js';import{publishNeuralResult}from'../src/publish-neural-result.js';import{createResultSurfaces}from'../src/segmented-results.js';import{createRasterExports as createNeuralExports}from'../src/raster-export.js';
test('Published neural handles and paged scientific exports own separate lifetimes',async()=>{
 const budget=new Budget(32*1024**2),width=17,height=13,stores={},surfaceMap=new Map(),results=createResultSurfaces(surfaceMap),exports=createNeuralExports(budget);
 for(const key of ['map','mask','analyzed','candidates']){const bytes=width*height*(key==='map'?4:1);stores[key]=await createSegmentedBytes(bytes,{budget});await stores[key].write(new Uint8Array(bytes));}
 const analysis={width,height,stores,metadata:{status:'empty',zones:[]},dispose:()=>Promise.all(Object.values(stores).map(s=>s.dispose()))},published=await publishNeuralResult(analysis,'image',{operation:'ai.clones.segmentation'},{budget,publishResult:(id,r)=>results.publishBundle(id,r)}),record=surfaceMap.get(published.surface.id).record;
 const before=budget.total(),abort=new AbortController();await assert.rejects(exports.createScientific(record,{format:'npz'},{signal:abort.signal,onProgress:()=>abort.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),before);assert.equal(exports.size,0);
 const descriptor=await exports.createScientific(record,{format:'npz'},{imageId:'image'});await results.clear('image');assert.equal(surfaceMap.size,0);const page=await exports.read({exportId:descriptor.id,revision:1});assert.equal(page.bytes.byteLength,descriptor.byteLength);assert.equal(createHash('sha256').update(page.bytes).digest('hex'),descriptor.sha256);page.bytes.fill(99);assert.notEqual((await exports.read({exportId:descriptor.id,revision:1,length:1})).bytes[0],99);
 await assert.rejects(exports.read({exportId:descriptor.id,revision:2}),{code:'INVALID_INPUT'});await assert.rejects(exports.read({exportId:descriptor.id,revision:1,length:4*1024**2+1}),{code:'INVALID_INPUT'});await exports.release(descriptor.id);await assert.rejects(exports.read({exportId:descriptor.id,revision:1}),{code:'NOT_FOUND'});await exports.clear();assert.equal(budget.total(),0);
});
test('Cancellation or publication failure rolls back all unpublished neural planes',async()=>{
 for(const fail of ['cancel','publisher']){const budget=new Budget(8*1024**2),stores={};for(const key of ['map','mask','analyzed','candidates'])stores[key]=await createSegmentedBytes(4*4*(key==='map'?4:1),{budget});const value={width:4,height:4,stores,metadata:{zones:[]},dispose:()=>Promise.all(Object.values(stores).map(s=>s.dispose()))},abort=new AbortController();let calls=0;if(fail==='cancel')abort.abort();
  await assert.rejects(publishNeuralResult(value,'image',{operation:'ai.clones.segmentation'},{budget,signal:abort.signal,publishResult(){calls++;throw Error('Publication failed');}}),fail==='cancel'?{code:'CANCELLED'}:/Publication failed/);assert.equal(calls,fail==='cancel'?0:1);assert.equal(budget.total(),0);
 }
});
