import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Budget} from '../src/cache.js';import {contiguousSurface} from '../src/image-sources.js';import {segmentedNoisesnifferStatistics} from '../src/segmented-noisesniffer-statistics.js';import {segmentedNoisesnifferSelection} from '../src/segmented-noisesniffer-selection.js';import {pagedNoisesnifferSelection} from '../src/noisesniffer-paged-selection.js';import {noisesnifferParams} from '../src/noisesniffer.js';
test('external global selection preserves all channel/bin orders and flags with stored sparse patches',async()=>{
 const manifest=JSON.parse(await fs.readFile(new URL('../fixtures/noisesniffer-reference.json',import.meta.url)));let cases=0;
 for(const c of manifest.cases.filter(c=>['patch-8','patch-3','constant-8','ties-3'].includes(c.name)).slice(0,4)){
 const budget=new Budget(256*1024**2),data=new Uint8Array(await fs.readFile(new URL('../fixtures/'+c.input.file,import.meta.url))),image={surface:contiguousSurface({width:c.width,height:c.height,data},budget),store:{byteLength:data.length,readInto(out,offset){out.set(data.subarray(offset,offset+out.length));}}};
 for(const a of c.analyses.slice(0,2)){const [blockSize,cellSize,samplesPerBin,lowFrequencyFraction,lowNoiseFraction]=a.parameters,p=noisesnifferParams({blockSize,cellSize,samplesPerBin,lowFrequencyFraction,lowNoiseFraction}),stats=await segmentedNoisesnifferStatistics(image,blockSize,{budget});let actual,expected;try{expected=await segmentedNoisesnifferSelection(image,p,stats,{budget});actual=await pagedNoisesnifferSelection(image,p,stats,{budget,storage:'memory'});assert.equal(actual.selectedCount,expected.selectedCount);assert.equal(actual.lowCount,expected.lowCount);for(const k of ['selected','low_noise','flags']){const x=new Uint8Array(actual[k].byteLength),y=new Uint8Array(expected[k].byteLength);await actual[k].readInto(x);await expected[k].readInto(y);assert.deepEqual(x,y,c.name+'/'+k);}assert.deepEqual(actual.all_blocks,expected.all_blocks);assert.deepEqual(actual.low_noise_blocks,expected.low_noise_blocks);cases++;}finally{await actual?.dispose();await expected?.dispose();await stats.dispose();}}
 assert.equal(budget.total(),0);}
 assert.ok(cases>=2);console.log({cases});
});
