import test from 'node:test';import assert from 'node:assert/strict';
import {createTemporarySession} from '../src/opfs-storage.js';
function environment({failCreate=0,badWrite=false,badSize=false,shortIO=false}={}){
 const nodes=new Map();let opened=0;class File{async createSyncAccessHandle(){const file=this;opened++;if(opened===failCreate)throw Object.assign(Error('quota'),{name:'QuotaExceededError'});file.closed=false;return {truncate(size){assert.ok(size<=1024**3);file.size=badSize?0:size;},getSize(){return file.size;},write(source,{at}){if(badWrite)return 4294967288;const n=shortIO?Math.min(5,source.length):source.length;for(let i=0;i<n;i++)file.bytes.set(at+i,source[i]);return n;},read(target,{at}){const n=shortIO?Math.min(3,target.length):target.length;for(let i=0;i<n;i++)target[i]=file.bytes.get(at+i)??0;return n;},flush(){},close(){file.closed=true;}};}constructor(){this.bytes=new Map();}}
 class Directory{constructor(){this.entries=new Map();}async getDirectoryHandle(name,{create=false}={}){if(!this.entries.has(name)){if(!create)throw Object.assign(Error('absent'),{name:'NotFoundError'});this.entries.set(name,new Directory());}return this.entries.get(name);}async getFileHandle(name){if(!this.entries.has(name)){const f=new File();nodes.set(name,f);this.entries.set(name,f);}return this.entries.get(name);}async removeEntry(name){const f=this.entries.get(name);if(f instanceof File){assert.ok(f.closed||failCreate||badSize);nodes.delete(name);}this.entries.delete(name);}}
 const root=new Directory(),priorNav=Object.getOwnPropertyDescriptor(globalThis,'navigator'),priorFile=Object.getOwnPropertyDescriptor(globalThis,'FileSystemFileHandle');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{storage:{estimate:async()=>({quota:20*1024**3,usage:0}),getDirectory:async()=>root}}});Object.defineProperty(globalThis,'FileSystemFileHandle',{configurable:true,value:File});return {nodes,restore(){for(const [key,prior]of [['navigator',priorNav],['FileSystemFileHandle',priorFile]])if(prior)Object.defineProperty(globalThis,key,prior);else delete globalThis[key];}};
}
test('OPFS logical arrays cross GiB and uint32 seams with short physical I/O',async()=>{const env=environment({shortIO:true});let session;try{session=await createTemporarySession();const length=2**32+61,store=await session.create(length);assert.equal(session.snapshot().physicalFiles,5);for(const offset of [1024**3-13,2**31-13,2**32-13]){const expected=Uint8Array.from({length:37},(_,i)=>i*7),actual=new Uint8Array(37);store.write(expected,offset);store.readInto(actual,offset);assert.deepEqual(actual,expected);}await Promise.all([store.dispose(),store.dispose()]);assert.equal(session.snapshot().reservedBytes,0);assert.equal(env.nodes.size,0);}finally{await session?.dispose();env.restore();}});
test('OPFS cleans partial multi-file allocation and restores logical admission',async()=>{const env=environment({failCreate:3});let session;try{session=await createTemporarySession();await assert.rejects(session.create(3*1024**3),e=>e.code==='STORAGE_QUOTA');assert.equal(session.snapshot().reservedBytes,0);assert.equal(env.nodes.size,0);const next=await session.create(17);await next.dispose();}finally{await session?.dispose();env.restore();}});
test('OPFS rejects impossible successful byte counts and failed truncation',async()=>{for(const options of [{badWrite:true},{badSize:true}]){const env=environment(options);let session;try{session=await createTemporarySession();if(options.badSize)await assert.rejects(session.create(17),e=>e.code==='STORAGE_IO');else{const store=await session.create(17);assert.throws(()=>store.write(new Uint8Array(1),0),e=>e.code==='STORAGE_IO');await store.dispose();}assert.equal(session.snapshot().reservedBytes,0);}finally{await session?.dispose();env.restore();}}});
