import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {decodePngRows} from '../src/png-stream.js';import {createBlobSource} from '../src/blob-source.js';import {createSegmentedBytes} from '../src/segmented-bytes.js';import {createRgbSurface} from '../src/rgb-surface.js';import {imageHeader} from '../src/image-headers.js';import {Budget} from '../src/cache.js';
const wasmBinary=await readFile(new URL('../vendor/png-stream/png-stream.wasm',import.meta.url));
test('libpng async scanlines preserve native RGB across depths, palette, alpha, Adam7 and EXIF orientation',async()=>{
 const root=new URL('./data/png-formats/',import.meta.url),ref=JSON.parse(await readFile(new URL('reference.json',root)));
 for(const item of ref.cases){const budget=new Budget(64*1024**2),source=createBlobSource(new Blob([await readFile(new URL(item.file,root))]),{budget}),header=imageHeader(new Uint8Array(await source.blob().arrayBuffer())),store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight*3,{budget}),surface=createRgbSurface(store,{width:header.sourceWidth,height:header.sourceHeight,orientation:header.orientation,budget});
  try{const result=await decodePngRows(source,header,store,{budget,wasmBinary}),window=await surface.readWindow();try{assert.equal(createHash('sha256').update(window.pixels.data).digest('hex'),item.rgbSha256,item.file);assert.equal(result.passes,item.interlace?7:1);}finally{window.release();}}finally{await surface.dispose();source.dispose();}assert.equal(budget.total(),0);
 }
});
test('PNG stream corrupt/truncated input, source-read cancellation and budget refusal release native admission',async()=>{
 const original=new Uint8Array(await readFile(new URL('./data/png-formats/png-0.png',import.meta.url))),header=imageHeader(original),corrupt=original.slice();let at=8;while(at+12<=corrupt.length){const length=new DataView(corrupt.buffer).getUint32(at),type=new TextDecoder().decode(corrupt.subarray(at+4,at+8));if(type==='IDAT'){corrupt[at+8]^=255;break;}at+=length+12;}
 for(const mode of ['crc','truncated','cancel','budget']){const budget=new Budget((mode==='budget'?1:64)*1024**2),controller=new AbortController();class InputBlob extends Blob {slice(start,end,...args){if(mode==='cancel')controller.abort();return super.slice(start,end,...args);}}const source=createBlobSource(new InputBlob([mode==='crc'?corrupt:mode==='truncated'?original.subarray(0,40):original]),{budget}),store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight*3,{budget});try{await assert.rejects(decodePngRows(source,header,store,{budget,signal:controller.signal,wasmBinary}),{code:mode==='cancel'?'CANCELLED':mode==='budget'?'MEMORY_LIMIT':'INVALID_INPUT'});assert.equal(budget.active,0);}finally{await store.dispose();source.dispose();}assert.equal(budget.total(),0);}
});
