import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {readPrnuDatabase,writePrnuDatabase} from '../src/prnu-hdf5.js';import {createSegmentedBytes} from '../src/segmented-bytes.js';import {Budget} from '../src/cache.js';
test('stored native fingerprints export progressively to exact HDF5 datasets and metadata',async()=>{
 const budget=new Budget(512*1024**2),bytes=new Uint8Array(await fs.readFile(new URL('../fixtures/prnu-snapshot.h5',import.meta.url))),original=await readPrnuDatabase(bytes,{maxWorkingBytes:budget.limit}),stored=await readPrnuDatabase(bytes,{maxWorkingBytes:budget.limit,createFingerprintStore:n=>createSegmentedBytes(n,{budget})});
 try{const data=await writePrnuDatabase(stored,{maxWorkingBytes:budget.limit,admit:n=>budget.reserve(n)}),restored=await readPrnuDatabase(data,{maxWorkingBytes:budget.limit});for(const [i,c]of restored.cameras.entries()){assert.deepEqual(c,original.cameras[i]);}const stop=new AbortController();stop.abort();await assert.rejects(writePrnuDatabase(stored,{signal:stop.signal,maxWorkingBytes:budget.limit,admit:n=>budget.reserve(n)}),{code:'CANCELLED'});}finally{await stored.dispose();}assert.equal(budget.total(),0);
});
test('HDF5 encoded random-access storage preserves datasets without a full encoded byte buffer',async()=>{
 const budget=new Budget(128*1024**2),bytes=new Uint8Array(await fs.readFile(new URL('../fixtures/prnu-snapshot.h5',import.meta.url))),original=await readPrnuDatabase(bytes,{maxWorkingBytes:budget.limit}),store=await createSegmentedBytes(8*1024**2,{budget}),options={maxWorkingBytes:budget.limit,admit:n=>budget.reserve(n)};
 try{const written=await writePrnuDatabase(original,{...options,encodedStore:store}),view={byteLength:written.byteLength,readInto:store.readInto};assert.ok(written.byteLength>0);const restored=await readPrnuDatabase(view,{...options,createFingerprintStore:n=>createSegmentedBytes(n,{budget})});try{for(let i=0;i<original.cameras.length;i++){const expected=original.cameras[i].fingerprint.values,actual=new Float64Array(expected.length);await restored.cameras[i].fingerprint.store.readInto(new Uint8Array(actual.buffer));assert.deepEqual(actual,expected);assert.deepEqual(restored.cameras[i].trainingManifest,original.cameras[i].trainingManifest);}}finally{await restored.dispose();}}finally{await store.dispose();}assert.equal(budget.total(),0);
});
