import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {createRasterExports} from '../src/raster-export.js';import {Budget} from '../src/cache.js';import {createRgbSurface,createMaskSurface,createFlagSurface} from '../src/rgb-surface.js';import {createEngine,pipeRasterExport} from '../src/index.js';import {decodeExportPng} from './png-export-oracle.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function bytes(engine,exported){const parts=[];for(let at=0;at<exported.byteLength;){const p=await engine.read({exportId:exported.id,revision:1,offset:at,length:Math.min(113,exported.byteLength-at)});parts.push(p.bytes);at=p.nextOffset;}return new Uint8Array(Buffer.concat(parts));}
test('native PNG exports preserve every oriented RGB byte and raw mask/flag values, with independent CRC/filter decoding',async()=>{
 for(const format of ['rgb8','mask8','rgb-flags8'])for(const orientation of [1,2,3,4,5,6,7,8]){const budget=new Budget(48*1024**2),channels=format==='mask8'?1:3,data=Uint8Array.from({length:67*71*channels},(_,i)=>format==='rgb8'?i*37^(i>>>3):i%3),store={byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},factory=format==='rgb8'?createRgbSurface:format==='mask8'?createMaskSurface:createFlagSurface,surface=factory(store,{width:67,height:71,orientation,budget,ownsStore:false,range:[0,2],semantics:'raw evidence'}),manager=createRasterExports(budget);
  try{const expected=await surface.readWindow(),reference=expected.pixels.data.slice();expected.release();const exported=await manager.create(surface,{compression:orientation%3===0?0:orientation%3===1?6:9},{imageId:'test',originalSha256:'reference'}),encoded=await bytes(manager,exported),decoded=decodeExportPng(encoded);assert.equal(sha(encoded),exported.sha256);assert.deepEqual(decoded.data,reference);assert.equal(decoded.channels,channels);assert.equal(decoded.width,surface.descriptor.width);await manager.release(exported.id);assert.equal(budget.total(),0);}finally{await manager.clear();await surface.dispose();}
 }
});
test('public export survives source unload, owned pages reject stale handles, stream applies backpressure and releases',async()=>{
 const engine=createEngine({memoryBudgetBytes:128*1024**2,cpuKernel:'single'}),source=new Uint8Array(await readFile(new URL('../fixtures/exif-6-le.jpg',import.meta.url)));
 try{const loaded=await engine.loadBlob({id:'source',blob:new Blob([source])}),expected=await engine.readPixels({surfaceId:loaded.surface.id,revision:1,rect:{x:0,y:0,width:loaded.width,height:loaded.height}}),exported=await engine.exportSurface({surfaceId:loaded.surface.id,revision:1});await engine.unload('source');await assert.rejects(engine.readExport({exportId:exported.id,revision:2}),{code:'INVALID_INPUT'});await assert.rejects(engine.readExport({exportId:exported.id,revision:1,length:5*1024**2}),{code:'INVALID_INPUT'});
  const chunks=[];let inWrite=false;await pipeRasterExport(engine,exported,new WritableStream({async write(part){assert.equal(inWrite,false);inWrite=true;await new Promise(r=>setTimeout(r,2));chunks.push(part);inWrite=false;}}));const encoded=new Uint8Array(Buffer.concat(chunks));assert.equal(sha(encoded),exported.sha256);assert.deepEqual(decodeExportPng(encoded).data,expected.pixels.data);await assert.rejects(engine.readExport({exportId:exported.id,revision:1}),{code:'NOT_FOUND'});assert.equal(engine.capabilities().memory.retainedBytes,0);
 }finally{await engine.dispose();}
});
test('output cap, cancellation, source read failure and memory refusal release unpublished storage',async()=>{
 for(const mode of ['cap','cancel','read','memory']){const budget=new Budget((mode==='memory'?1:48)*1024**2),manager=createRasterExports(budget),controller=new AbortController(),surface={descriptor:{id:'s',revision:1,width:512,height:128,format:'rgb8'},async readWindow({height}){if(mode==='read')throw new Error('source unavailable');const release=budget.reserve(512*height*3);return {pixels:{data:new Uint8Array(512*height*3)},release};}};
  await assert.rejects(manager.create(surface,{...(mode==='cap'?{maxBytes:100}:{}),compression:0},{signal:controller.signal,onProgress:()=>{if(mode==='cancel')controller.abort();}}),e=>e.code===(mode==='cap'?'EXPORT_LIMIT':mode==='cancel'?'CANCELLED':mode==='memory'?'MEMORY_LIMIT':undefined)&&(mode!=='read'||e.message==='source unavailable'));assert.equal(manager.size,0);assert.equal(budget.total(),0);await manager.clear();
 }
});
test('failed destination aborts and releases the completed export',async()=>{
 const engine=createEngine({memoryBudgetBytes:128*1024**2}),data=Uint8Array.from({length:9*7*3},(_,i)=>i),loaded=await engine.load({id:'i',bytes:new Uint8Array([1]),pixels:{width:9,height:7,format:'rgb8',data},provenance:{source:'test'}});try{const output=await engine.exportSurface({surfaceId:loaded.surface.id,revision:1});let aborted=false;await assert.rejects(pipeRasterExport(engine,output,new WritableStream({write(){throw Error('destination full');},abort(){aborted=true;}})),/destination full/);await assert.rejects(engine.readExport({exportId:output.id,revision:1}),{code:'NOT_FOUND'});assert.equal(engine.capabilities().memory.activeReservationBytes,0);}finally{await engine.dispose();}
});
test('multi-page destination backpressure and disposed engine cleanup retain no complete encoded copy',async()=>{
 const width=1027,height=769,data=Uint8Array.from({length:width*height*3},(_,i)=>i*17^(i>>>7)),engine=createEngine({memoryBudgetBytes:128*1024**2});try{const loaded=await engine.load({id:'rgb',bytes:new Uint8Array([2]),pixels:{width,height,format:'rgb8',data},provenance:{source:'test'}}),output=await engine.exportSurface({surfaceId:loaded.surface.id,revision:1,compression:0});let writing=false,reads=0;const parts=[],api={async readExport(...args){assert.equal(writing,false);reads++;return engine.readExport(...args);},releaseExport:id=>engine.releaseExport(id)};
  await pipeRasterExport(api,output,new WritableStream({async write(page){writing=true;parts.push(page);await new Promise(r=>setTimeout(r,1));writing=false;}}));assert.ok(reads>=3);assert.deepEqual(decodeExportPng(new Uint8Array(Buffer.concat(parts))).data,data);
  await engine.exportSurface({surfaceId:loaded.surface.id,revision:1});await engine.dispose();assert.equal(engine.capabilities().memory.retainedBytes,0);
 }finally{try{await engine.dispose();}catch(e){assert.equal(e.code,'DISPOSED');}}
});
test('public result-mask export keeps raw evidence and survives source/result release',async()=>{
 const engine=createEngine({memoryBudgetBytes:96*1024**2,cpuKernel:'single'});try{const source=await engine.loadBlob({id:'source',blob:new Blob([await readFile(new URL('./data/recompression-segmented-parallel.jpg',import.meta.url))])});assert.equal(source.provenance.layout,'segmented-scanlines');const result=await engine.run({id:'mask',imageId:'source',operation:'noise.minmax',params:{filter:1}}),mask=result.maskSurfaces.minimum,original=await engine.readMask({surfaceId:mask.id,revision:mask.revision,rect:{x:0,y:0,width:mask.width,height:mask.height}}),exported=await engine.exportSurface({surfaceId:mask.id,revision:mask.revision});assert.equal(exported.sourceFormat,'mask8');assert.deepEqual(exported.provenance.range,mask.range);await engine.unload('source');const encoded=await bytes({read:r=>engine.readExport(r)},exported);assert.deepEqual(decodeExportPng(encoded).data,original.mask.data);await engine.releaseExport(exported.id);assert.equal(engine.capabilities().memory.retainedBytes,0);}finally{await engine.dispose();}
});
