import {resamplingFourierParams,resamplingFourierGeometry} from '../src/resampling-fourier.js';
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {Budget} from '../src/cache.js';import {loadSegmentedJpeg,disposeSegmentedImage} from '../src/image-sources.js';import {segmentedResamplingAnalysis} from '../src/segmented-resampling-analysis.js';import {resamplingAnalysisParams,resamplingAnalysisRegions} from '../src/resampling-analysis.js';
const base=new URL('../.build/resampling-analysis/',import.meta.url),fixture=new URL('../fixtures/',import.meta.url);const read=async name=>new Uint8Array(await fs.readFile(new URL(name,base)));const table=async t=>{const p=await t.readRows({offset:0,length:t.descriptor.rowCount});try{return Float64Array.from({length:p.length},(_,i)=>p.data[i*3+2]);}finally{p.release();}};const surfaces=r=>[r.surface,...Object.values(r.tableRecords??{}).map(v=>v.surface),...Object.values(r.rgbRecords??{}).map(v=>v.surface)];const close=async r=>Promise.all(surfaces(r).map(s=>s.dispose()));const rgb=async s=>{const v=await s.readWindow();try{return v.pixels.data.slice();}finally{v.release();}};
test('global native ROI maps, composites and their Fourier outputs preserve bits and existing tolerance',async t=>{
 let records;try{records=JSON.parse(await fs.readFile(new URL('reference.json',base)));}catch(e){if(e.code==='ENOENT'){t.skip('Generate local native integration oracle first.');return;}throw e;}
 for(const row of records){const budget=new Budget(128*1024**2),source=await loadSegmentedJpeg(new Blob([await fs.readFile(new URL(row.file,fixture))]),{budget});let cache;const live=[];
 try{const p={size:row.size,regions:row.regions,fourierRegions:row.fourierRegions},first=await segmentedResamplingAnalysis(source,p,{budget});cache=first.emCache;live.push(first);assert.deepEqual(new Uint8Array((await table(first.tableRecords.composite.surface)).buffer),await read(row.composite.file));assert.deepEqual(await rgb(first.surface),await read(row.rgb.file));for(let i=0;i<row.maps.length;i++){assert.equal(first.data.maps[i].iterations,row.maps[i].iterations);assert.deepEqual(new Uint8Array((await table(first.tableRecords['probability'+i].surface)).buffer),await read(row.maps[i].file));}
 for(const f of row.fourier){const events=[],r=await segmentedResamplingAnalysis(source,{...p,stage:'fourier',fourier:f.params},{budget,cache,onProgress:p=>events.push(p.phase)});live.push(r);assert(r.metrics.analysisCached);assert(!events.some(v=>v.startsWith('em-')));for(let i=0;i<f.outputs.length;i++){const out=f.outputs[i],values=await table(r.tableRecords['fourier'+i+'_values'].surface),bytes=await read(out.values.file),expected=new Float64Array(bytes.buffer,bytes.byteOffset,bytes.length/8);assert.equal(values.length,expected.length);for(let j=0;j<values.length;j++)assert.ok(Math.abs(values[j]-expected[j])/Math.max(1,Math.abs(expected[j]))<=1e-8);assert.deepEqual(await rgb(i?r.rgbRecords['fourier'+i].surface:r.surface),await read(out.rgb.file));}}
 await cache.dispose();assert.deepEqual(await rgb(first.surface),await read(row.rgb.file));
 }finally{await Promise.all(live.map(close));await cache?.dispose();await disposeSegmentedImage(source);}assert.equal(budget.total(),0);
 }
});
test('regions reject overlap and partial coordinates; cancellation preserves published owners',async()=>{
 assert.throws(()=>resamplingAnalysisParams({regions:[[0,1,2.5,4]]}));assert.throws(()=>resamplingAnalysisRegions(resamplingAnalysisParams({regions:[[0,0,20,20],[10,10,30,30]]}),40,40));
 const budget=new Budget(64*1024**2),source=await loadSegmentedJpeg(new Blob([await fs.readFile(new URL('synthetic.jpg',fixture))]),{budget}),first=await segmentedResamplingAnalysis(source,{},{budget}),cache=first.emCache,expected=await rgb(first.surface),activeBefore=budget.active;assert.equal(activeBefore,2*source.surface.descriptor.width*source.surface.descriptor.height*8,'The binary64 composite owns the shared migration capacity');
 try{for(const phase of ['em-weights','em-coefficients','em-iteration','resampling-fft-rows']){const stop=new AbortController(),p={size:5,stage:phase.startsWith('resampling')?'fourier':'probability'};await assert.rejects(segmentedResamplingAnalysis(source,p,{budget,cache,signal:stop.signal,onProgress:v=>{if(v.phase===phase)stop.abort();}}),{code:'CANCELLED'});assert.deepEqual(await rgb(first.surface),expected);const side=resamplingFourierGeometry(source.surface.descriptor.width-4,source.surface.descriptor.height-4,resamplingFourierParams()).fftSide,expectedActive=phase.startsWith('resampling')?Math.max(activeBefore,2*side*side*16):activeBefore;assert.equal(budget.active,expectedActive,'Only the shared migration capacity remains, including the larger complex Fourier plane once reached');}}
 finally{await close(first);await cache.dispose();await disposeSegmentedImage(source);}assert.equal(budget.total(),0);
});
