import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm,open} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {scientificZipPlan,scientificZipLocal,scientificZipCentral,scientificZipEnd} from '../src/scientific-zip.js';import {streamScientificNpz} from '../src/scientific-npz-stream.js';import {Budget} from '../src/cache.js';
const python=process.env.SHERLOQ_PYTHON??'python3';
test('Python zipfile and NumPy read the real streamed ZIP64 NPZ without changing scientific values',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'sherloq-zip64-')),budget=new Budget(16*1024**2);let archive;
 try{const data=new Float64Array([Math.PI,-0,1e-300,Infinity]);archive=await streamScientificNpz([{key:'résultat',descr:'<f8',shape:[2,2],count:4,elementBytes:8,read:(out,first,count)=>out.set(new Uint8Array(data.buffer,first*8,count*8))}],{unicode:'é 🌍'},{native:true},{zip64:true,storage:'memory'},{budget});assert.equal(archive.metrics.zip64,true);const bytes=new Uint8Array(archive.byteLength);await archive.store.readInto(bytes);const filename=path.join(directory,'evidence.npz');await writeFile(filename,bytes);execFileSync(python,['-c',"import sys,zipfile,numpy as np; p=sys.argv[1]; z=zipfile.ZipFile(p); assert z.testzip() is None; a=np.load(p,allow_pickle=False); x=a['résultat']; assert x.shape==(2,2) and x[0,0]==np.pi and np.signbit(x[0,1]) and x[1,0]==1e-300 and np.isinf(x[1,1]); assert '🌍' in str(a['metadata_json'])",filename]);}
 finally{await archive?.store.dispose();await archive?.session?.dispose();await rm(directory,{recursive:true,force:true});}assert.equal(budget.total(),0);
});
test('Independent ZIP reader resolves a genuine offset above 4 GiB in a sparse test file',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'sherloq-large-zip-')),filename=path.join(directory,'large.zip'),encoder=new TextEncoder(),entries=[{name:encoder.encode('large.bin'),size:0x100000010,crc:0},{name:encoder.encode('tail.txt'),size:0,crc:0}],plan=scientificZipPlan(entries);let file;
 try{assert.equal(plan.zip64,true);file=await open(filename,'w');for(const e of entries)await file.write(scientificZipLocal(e),0,scientificZipLocal(e).length,e.offset);let offset=plan.central;for(const e of entries){const bytes=scientificZipCentral(e);await file.write(bytes,0,bytes.length,offset);offset+=bytes.length;}const end=scientificZipEnd(plan);await file.write(end,0,end.length,offset);await file.close();file=null;execFileSync(python,['-c',"import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); assert z.getinfo('large.bin').file_size==0x100000010; assert z.getinfo('tail.txt').header_offset>2**32; assert z.read('tail.txt')==b''",filename]);}
 finally{await file?.close();await rm(directory,{recursive:true,force:true});}
});
