import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createEngine} from '../src/index.js';
test('public segmented ELA publishes owned output and reuses encoded quality across render controls',async()=>{
 const engine=createEngine({memoryBudgetBytes:116*1024**2,cpuKernel:'single'}),large=new Blob([await readFile(new URL('./data/recompression-segmented-parallel.jpg',import.meta.url))]);try{const source=await engine.loadBlob({id:'source',blob:large});assert.equal(source.provenance.layout,'segmented-scanlines');const a=await engine.run({id:'ela1',imageId:'source',operation:'ela.classic'}),b=await engine.run({id:'ela2',imageId:'source',operation:'ela.classic',params:{scale:37,grayscale:true}});assert.equal(a.layout,'surface');assert.equal(a.metrics.cache.recompressed,false);assert.equal(b.metrics.cache.recompressed,true);assert.equal(b.metrics.recompressions,0);const rect={x:7,y:29,width:31,height:35},one=await engine.readPixels({surfaceId:a.surface.id,revision:1,rect});one.pixels.data.fill(0);assert.notDeepEqual((await engine.readPixels({surfaceId:a.surface.id,revision:1,rect})).pixels.data,one.pixels.data);await engine.releaseSurface(a.surface.id);await engine.unload('source');await assert.rejects(engine.readPixels({surfaceId:b.surface.id,revision:1,rect}),{code:'NOT_FOUND'});assert.equal(engine.capabilities().memory.retainedBytes,0);assert.equal(engine.capabilities().memory.activeReservationBytes,0);}finally{await engine.dispose();}
});
test('cancelled segmented ELA keeps only completed JPEG cache and permits an exact retry',async()=>{
 const engine=createEngine({memoryBudgetBytes:116*1024**2,cpuKernel:'single'}),blob=new Blob([await readFile(new URL('./data/recompression-segmented-parallel.jpg',import.meta.url))]);try{const source=await engine.loadBlob({id:'source',blob}),before=engine.capabilities().memory,[width,height]=source.provenance.sourceSize,encodedCapacity=Math.ceil(width/16)*16*Math.ceil(height/16)*16*6+2048;const controller=new AbortController();await assert.rejects(engine.run({id:'cancel',imageId:'source',operation:'ela.classic'},{signal:controller.signal,onProgress:e=>{if(e.phase==='jpeg-render')controller.abort();}}),{code:'CANCELLED'});const cancelled=engine.capabilities().memory;assert.equal(cancelled.activeReservationBytes,Math.max(before.activeReservationBytes,2*Math.min(1024**2,encodedCapacity)),'The completed JPEG cache retains one shared migration window');assert.equal(cancelled.retainedBytes,before.retainedBytes+encodedCapacity,'Only the source and completed encoded JPEG remain, with no partial ELA output');const result=await engine.run({id:'retry',imageId:'source',operation:'ela.classic'});assert.equal(result.metrics.cache.recompressed,true);await engine.unload('source');assert.equal(engine.capabilities().memory.retainedBytes,0);assert.equal(engine.capabilities().memory.activeReservationBytes,0);assert.equal(engine.capabilities().memory.cacheBytes,0);}finally{await engine.dispose();}
});
test('zero-phase Ghost and ELA reuse the same completed global RGB JPEG',async()=>{
 const {Budget}=await import('../src/cache.js'),{createRgbSurface}=await import('../src/rgb-surface.js'),{segmentedEla}=await import('../src/segmented-ela.js'),{segmentedGhostMaps}=await import('../src/segmented-ghosts.js'),{validateParams}=await import('../src/ela.js'),{ghostParams}=await import('../src/ghost-maps.js'),data=Uint8Array.from({length:35*33*3},(_,i)=>i*31),budget=new Budget(64*1024**2),image={surface:createRgbSurface({byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},{width:35,height:33,budget,ownsStore:false})};try{const a=await segmentedEla(image,validateParams(),{budget});await a.surface.dispose();const g=await segmentedGhostMaps(image,ghostParams({low:75,high:75}),{budget});assert.equal(g.engineMetrics.recompressions,0);const shifted=await segmentedGhostMaps(image,ghostParams({low:75,high:75,x:1,y:7}),{budget});assert.equal(shifted.engineMetrics.recompressions,1);const b=await segmentedEla(image,validateParams({linear:true}),{budget});assert.equal(b.metrics.recompressedCache,true);await b.surface.dispose();}finally{await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
});
