import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {gunzipSync} from 'node:zlib';
import {createSegmentedEnergyCache} from '../src/segmented-energy.js';import {energyParams} from '../src/energy-pipeline.js';import {Budget} from '../src/cache.js';import {createRgbSurface} from '../src/rgb-surface.js';import {createBlobSource} from '../src/blob-source.js';
const root=new URL('../fixtures/ela-energy/',import.meta.url),ref=JSON.parse(await readFile(new URL('pipeline.json',root))),payload=gunzipSync(await readFile(new URL(ref.payload.file,root))),bytes=p=>new Uint8Array(payload.subarray(p.offset,p.offset+p.length));
async function read(store){const out=new Uint8Array(store.byteLength);await store.readInto(out,0);return out;}
async function setup(source){const budget=new Budget(256*1024**2),rgb=bytes(source.pixels),surface=createRgbSurface({byteLength:rgb.length,readInto(out,offset=0){out.set(rgb.subarray(offset,offset+out.length));}},{width:source.width,height:source.height,budget,ownsStore:false}),image={surface,source:createBlobSource(new Blob([await readFile(new URL(source.file,root))]),{budget})},cache=createSegmentedEnergyCache(image,budget);return {image,cache,budget,async dispose(){await cache.dispose();await image.rgbRecompression?.dispose();await surface.dispose();image.source.dispose();assert.equal(budget.total(),0);}};}
async function verify(result,row){const d=result.analysis.value,n=d.width*d.height;for(let q=0;q<3;q++)assert.deepEqual(await read(d.energy_planes[q]),bytes(row.energy_planes).slice(q*n*4,(q+1)*n*4),row.name+' energy '+q);for(const key of ['energy_low_score','energy_high_score','energy_scope','energy_labels'])assert.deepEqual(await read(d[key]),bytes(row[key]),row.name+' '+key);assert.deepEqual(d.energy_summary,row.summary,row.name+' summary');assert.deepEqual(d.regions,row.regions,row.name+' regions');assert.deepEqual(d.metadata.energy.automatic,row.automatic);assert.deepEqual(d.metadata.energy.quantiles,row.quantiles);assert.deepEqual(d.metadata.energy.thresholds,row.thresholds);for(const [key,value] of Object.entries(row.metadata))assert.deepEqual(d.metadata[key],value,row.name+' '+key);}
test('complete segmented energy chain matches all 51 native pipelines',async()=>{for(const source of ref.sources){const state=await setup(source);try{for(const row of ref.cases.filter(r=>r.source===source.name))await verify(await state.cache.analyze(energyParams(row.params)),row);}finally{await state.dispose();}}});
test('segmented energy caches reuse stages and retained results survive cache eviction and disposal',async()=>{const source=ref.sources.find(s=>s.name==='composite'),row=ref.cases.find(r=>r.source===source.name&&r.params.profile==='standard'),state=await setup(source);let release;try{const first=await state.cache.analyze(energyParams(row.params));release=first.analysis.retain();assert.equal(first.metrics.energyQualityPlanesComputed,3);assert.equal(first.metrics.energyPanelDetections,1);assert.equal((await state.cache.analyze(energyParams(row.params))).metrics.cache.result,true);const edited=await state.cache.analyze(energyParams({...row.params,profile:'manual',shadow:10,minimum:1}));assert.equal(edited.metrics.energyQualityPlanesComputed,0);assert.equal(edited.metrics.energyPreparationMs,0);const shifted=await state.cache.analyze(energyParams({quality:first.analysis.value.metadata.quality-5,block:16}));assert.equal(shifted.metrics.energyQualityPlanesComputed,1);for(const quality of [10,40,95])await state.cache.analyze(energyParams({quality,block:16}));await state.cache.dispose();await verify(first,row);}finally{await release?.();await state.dispose();}});
test('segmented energy cancellation preserves completed stages and permits exact retry',async()=>{const source=ref.sources.find(s=>s.name==='composite'),row=ref.cases.find(r=>r.source===source.name),state=await setup(source);try{const controller=new AbortController();await assert.rejects(state.cache.analyze(energyParams(row.params),{signal:controller.signal,onProgress:e=>{if(e.phase==='energy-panel-scores')controller.abort();}}),{code:'CANCELLED'});const result=await state.cache.analyze(energyParams(row.params));assert.equal(result.metrics.energyQualityPlanesComputed,0);await verify(result,row);}finally{await state.dispose();}});
