import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {crc32} from 'node:zlib';
import {createSegmentedZeroAnalysis,segmentedZeroResult} from '../src/segmented-zero.js';import {streamZeroNpz} from '../src/zero-npz-stream.js';import {createRgbSurface} from '../src/rgb-surface.js';import {Budget} from '../src/cache.js';
const root=new URL('../fixtures/',import.meta.url),ref=JSON.parse(await readFile(new URL('zero-reference.json',root))),sha=a=>createHash('sha256').update(a).digest('hex');
function arrays(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),entries={};let at=0;while(view.getUint32(at,true)===0x04034b50){const size=view.getUint32(at+18,true),length=view.getUint16(at+26,true),name=new TextDecoder().decode(bytes.subarray(at+30,at+30+length)),start=at+30+length,all=bytes.subarray(start,start+size),headerLength=new DataView(all.buffer,all.byteOffset).getUint16(8,true);assert.equal(crc32(all),view.getUint32(at+14,true));entries[name.slice(0,-4)]={header:new TextDecoder().decode(all.subarray(10,10+headerLength)),data:all.subarray(10+headerLength)};at=start+size;}assert.equal(view.getUint32(at,true),0x02014b50);return entries;}
test('segmented ZERO renders all five native views and exports native scientific arrays without full matrices',async()=>{
 const selected=[ref.cases[0],ref.cases.find(x=>x.name==='spliced'),ref.cases.at(-1)];
 for(const item of selected){const budget=new Budget(128*1024**2),rgb=new Uint8Array(await readFile(new URL(item.file,root))),image={surface:createRgbSurface({byteLength:rgb.length,readInto:(out,at)=>out.set(rgb.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};
  try{for(const expected of item.expected){let analysis,output;const records=[];try{analysis=await createSegmentedZeroAnalysis(image,{missing:expected.missing},{budget});for(let view=0;view<5;view++){const result=await segmentedZeroResult(analysis,{view},{budget});records.push(result);const part=await result.surface.readWindow();try{assert.equal(sha(part.pixels.data),expected.views[view],item.name+' view '+view);}finally{part.release();}for(const [key,r]of Object.entries(result.maskRecords)){const part=await r.surface.readWindow();try{assert.ok(part.pixels.data.every(v=>v===0||v===1));assert.equal(sha(new Uint8Array(Int32Array.from(part.pixels.data,v=>v*255).buffer)),expected.arrays[key].sha256,item.name+' binary mask');}finally{part.release();}}}
    output=await streamZeroNpz(analysis,{test:'é🧪'}, {},{budget});const bytes=new Uint8Array(output.byteLength);await output.store.readInto(bytes);assert.equal(sha(bytes),output.sha256);const packed=arrays(bytes);for(const [key,value]of Object.entries(expected.arrays)){const entry=packed[key];assert.ok(entry.header.includes(key.startsWith('luminance')||key==='grid_log10_nfa'?'<f8':'<i4'));if(key!=='grid_log10_nfa')assert.equal(sha(entry.data),value.sha256,item.name+' NPZ '+key);else{const values=new DataView(entry.data.buffer,entry.data.byteOffset);for(let i=0;i<64;i++)assert.ok(Math.abs(values.getFloat64(i*8,true)-value.values[i])<=1e-10);}}
    if(item.name==='spliced'&&expected.missing){await mkdir(new URL('../.build/zero-segmented/',import.meta.url),{recursive:true});await writeFile(new URL('../.build/zero-segmented/result.npz',import.meta.url),bytes);}
    await analysis.dispose();analysis=null;const live=await records[0].surface.readWindow({x:0,y:0,width:16,height:16});live.release(); // Surface owners survive cache eviction.
   }finally{await output?.store.dispose();await output?.session?.dispose();for(const r of records)await Promise.all([r.surface.dispose(),...Object.values(r.maskRecords).map(m=>m.surface.dispose())]);await analysis?.dispose();}}
  }finally{await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
 }
});
test('NPZ limit and cancellation keep live ZERO analysis reusable',async()=>{
 const item=ref.cases[0],budget=new Budget(64*1024**2),rgb=new Uint8Array(await readFile(new URL(item.file,root))),image={surface:createRgbSurface({byteLength:rgb.length,readInto:(out,at)=>out.set(rgb.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};let analysis;
 try{analysis=await createSegmentedZeroAnalysis(image,{missing:false},{budget});const baseline=budget.total();await assert.rejects(streamZeroNpz(analysis,{}, {maxBytes:100},{budget}),{code:'EXPORT_LIMIT'});const controller=new AbortController();await assert.rejects(streamZeroNpz(analysis,{}, {},{budget,signal:controller.signal,onProgress:()=>controller.abort()}),{code:'CANCELLED'});assert.equal(budget.total(),baseline);}finally{await analysis?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
});
test('segmented ZERO honors the original-order reference CPU override',async()=>{
 const item=ref.cases.find(x=>x.name==='spliced'),budget=new Budget(96*1024**2),rgb=new Uint8Array(await readFile(new URL(item.file,root))),image={surface:createRgbSurface({byteLength:rgb.length,readInto:(out,at)=>out.set(rgb.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};let analysis;
 try{analysis=await createSegmentedZeroAnalysis(image,{missing:false},{budget,reference:true});assert.equal(analysis.metadata.reference,true);assert.equal(analysis.metrics.original.kernel,'zero-reference-overlapping-bands');const votes=new Uint8Array(item.width*item.height);await analysis.planes.votes.readInto(votes);assert.equal(sha(new Uint8Array(Int32Array.from(new Int8Array(votes.buffer)).buffer)),item.expected[0].arrays.votes.sha256);}finally{await analysis?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
});
