import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {segmentedElaBiomes} from '../src/segmented-ela-biomes.js';import {elaCellParams} from '../src/ela-cell-pipeline.js';
import {Budget} from '../src/cache.js';import {imageCodec} from '../src/codecs.js';import {createRgbSurface} from '../src/rgb-surface.js';import {energyReferenceHeader,energyReferenceQuality} from '../src/energy-pipeline.js';import {imageHeader} from '../src/image-headers.js';
test('segmented ELA biomes preserve native complete pipelines, background and one/64 Ghost phases',async()=>{
 const ref=JSON.parse(await readFile(new URL('data/ela-pipeline-native.json',import.meta.url))),pixels=await imageCodec.decode(new Uint8Array(await readFile(new URL('data/'+ref.file,import.meta.url)))),budget=new Budget(192*1024**2),image={surface:createRgbSurface({byteLength:pixels.data.length,readInto:(out,at)=>out.set(pixels.data.subarray(at,at+out.length))},{width:pixels.width,height:pixels.height,budget,ownsStore:false})},cache=new Map(),ghost=new Map(),memo=async(key,compute)=>{if(cache.has(key))return cache.get(key);const value=await compute();cache.set(key,value);return value;},memoMany=async(names,compute)=>{const missing=names.filter(n=>!cache.has(n));if(missing.length){const values=await compute(missing);missing.forEach((n,i)=>cache.set(n,values[i]));}return names.map(n=>cache.get(n));};
 const execute=async params=>{const releases=[];try{return await segmentedElaBiomes(image,elaCellParams(params),{budget,memo,memoMany,reserveMemory:n=>{const free=budget.reserve(n);releases.push(free);return free;},getGhostPlane:(x,y,q)=>ghost.get(x+'/'+y+'/'+q),putGhostPlane:(x,y,q,v)=>ghost.set(x+'/'+y+'/'+q,v)});}finally{releases.forEach(f=>f());}};
 try{for(const [ci,expected]of ref.cases.entries()){const result=await execute(expected.params);for(const [name,value]of Object.entries(expected.data)){if(name==='regions'){assert.deepEqual(result.data.regions,value);continue;}const flat=value.flat(5).map(Number);assert.equal(result.data[name].length,flat.length);for(let i=0;i<flat.length;i++)assert.ok(Math.abs(result.data[name][i]-flat[i])<=(name==='content'?3e-7:0),ci+'/'+name+'/'+i);}const changed=await execute({...expected.params,threshold:1,minimum:1});assert.equal(changed.engineMetrics.cellRecompressions,0);assert.equal(changed.engineMetrics.ghostPhasesComputed,0);}
  assert.equal(ghost.size,71*64);const shifted=await execute({block:16,quality:80,ghost:false,background:true});assert.equal(shifted.engineMetrics.cellRecompressions,1);assert.equal(budget.active,0);
 }finally{await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
});
test('reference quality from sparse JPEG tables preserves original-byte estimation and PNG fallback',async()=>{
 for(const file of ['../fixtures/odd.jpg','data/recompression-segmented-parallel.jpg']){const bytes=new Uint8Array(await readFile(new URL(file,import.meta.url)));for(const requested of [0,75])assert.deepEqual(energyReferenceHeader(imageHeader(bytes),requested),energyReferenceQuality(bytes,requested));}
 assert.deepEqual(energyReferenceHeader({quantization:{}},0),energyReferenceHeader(undefined,0));assert.deepEqual(energyReferenceHeader(undefined,0),{quality:75,quality_origin:'fallback_no_usable_jpeg_tables',table_deviation:null});
});

test('bounded Ghost stages resume two publication/aggregation failures and preserve the native pipeline',async()=>{
 const {createElaStageCheckpoint}=await import('../src/ela-stage-checkpoint.js'),{EngineError}=await import('../src/errors.js');
 const ref=JSON.parse(await readFile(new URL('data/ela-pipeline-native.json',import.meta.url))),expected=ref.cases.find(v=>v.params.ghost&&!v.params.allGrids),pixels=await imageCodec.decode(new Uint8Array(await readFile(new URL('data/'+ref.file,import.meta.url)))),budget=new Budget(256*1024**2),image={surface:createRgbSurface({byteLength:pixels.data.length,readInto:(out,at)=>out.set(pixels.data.subarray(at,at+out.length))},{width:pixels.width,height:pixels.height,budget,ownsStore:false})},stageCheckpoint=createElaStageCheckpoint(budget),events=[];let faults=0;
 assert.ok(expected);const run=async()=>{const releases=[];try{return await segmentedElaBiomes(image,elaCellParams(expected.params),{budget,stageCheckpoint,reserveMemory:n=>{const free=budget.reserve(n);releases.push(free);return free;},onProgress:event=>{events.push(event);if(faults===0&&event.phase==='ghost-quality'&&event.quality===34||faults===1&&event.phase==='ghost-cell-quality'&&event.quality===50){faults++;throw new EngineError('MEMORY_ALLOCATION','Injected next-stage refusal',{cause:new RangeError('Array buffer allocation failed'),details:{allocationKind:'array-buffer',requestedBytes:8192}});}}});}finally{releases.forEach(f=>f());}};
 try{
  await assert.rejects(run(),{code:'MEMORY_ALLOCATION'});assert.equal(stageCheckpoint.snapshot().ghost.committedQualities,events.filter(v=>v.phase==='ghost-quality').length);assert.ok(stageCheckpoint.snapshot().ghost.committedQualities>=5);const elaCount=events.filter(v=>v.phase==='ela-cell-describe').length;assert.ok(elaCount>0);
  await assert.rejects(run(),{code:'MEMORY_ALLOCATION'});assert.equal(stageCheckpoint.snapshot().ghost.committedQualities,71);assert.equal(stageCheckpoint.snapshot().ghost.aggregatedQualities,21);assert.equal(events.filter(v=>v.phase==='ela-cell-describe').length,elaCount);
  const result=await run();assert.equal(events.filter(v=>v.phase==='ghost-quality').length,71,'Committed qualities never run twice');assert.equal(events.filter(v=>v.phase==='ghost-cell-quality').length,71,'Committed aggregate curves never run twice');assert.equal(stageCheckpoint.snapshot().ghost,null);
  for(const [name,value]of Object.entries(expected.data)){if(name==='regions'){assert.deepEqual(result.data.regions,value);continue;}const flat=value.flat(5).map(Number);assert.equal(result.data[name].length,flat.length);for(let i=0;i<flat.length;i++)assert.ok(Math.abs(result.data[name][i]-flat[i])<=(name==='content'?3e-7:0),name+'/'+i);}
 }finally{await stageCheckpoint.dispose();await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);assert.equal(budget.resourceSnapshot().domains['array-buffer'].materializedBytes,0);
});
