import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {segmentedGhostMaps,segmentedGhostShape} from '../src/segmented-ghosts.js';import {ghostParams,ghostView} from '../src/ghost-maps.js';import {Budget} from '../src/cache.js';import {createRgbSurface} from '../src/rgb-surface.js';import {rolledRgbSurface} from '../src/rolled-rgb-surface.js';
const sha=a=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');
test('segmented Ghost native means, normalized cubes, all phases and palette controls retain exact values',async()=>{
 const reference=JSON.parse(await readFile(new URL('../fixtures/ghost-reference.json',import.meta.url)));
 for(const item of reference.cases){const data=new Uint8Array(await readFile(new URL('../fixtures/'+item.file,import.meta.url))),budget=new Budget(128*1024**2),image={surface:createRgbSurface({byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};try{for(const expected of item.expected){const p=ghostParams(expected.params),free=budget.reserve(segmentedGhostShape(image,p).admissionBytes),result=await segmentedGhostMaps(image,p,{budget});try{assert.equal(sha(result.data.raw),expected.rawSha256,item.name+' raw');assert.equal(sha(result.data.maps),expected.sha256,item.name+' maps');await ghostView(result,p,{},{});for(const [q,view]of result.data.views.entries())assert.equal(sha(view.pixels.data),expected.previews.gray[q]);await ghostView(result,{...p,grayscale:false,includeOriginal:true},{},{surface:image.surface.descriptor});assert.equal(result.data.original,undefined);assert.equal(result.layers[0].surfaceId,image.surface.descriptor.id);for(const [q,view]of result.data.views.entries())assert.equal(sha(view.pixels.data),expected.previews.viridis[q]);}finally{free();}}}finally{await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);}
});
test('every circular phase crosses rows/storage seams exactly and releases window accounting',async()=>{
 const width=31,height=35,data=Uint8Array.from({length:width*height*3},(_,i)=>i*41),budget=new Budget(2*1024**2),surface=createRgbSurface({byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},{width,height,budget,ownsStore:false});
 for(let x=0;x<8;x++)for(let y=0;y<8;y++){const rolled=rolledRgbSurface(surface,x,y,budget);for(const [start,count]of[[0,32],[32,3]]){const part=await rolled.readWindow({x:0,y:start,width,height:count});try{for(let row=0;row<count;row++)for(let col=0;col<width;col++){const input=(((start+row-y+height)%height)*width+(col-x+width)%width)*3,out=(row*width+col)*3;assert.deepEqual(part.pixels.data.subarray(out,out+3),data.subarray(input,input+3));}}finally{part.release();}assert.equal(budget.total(),0);}}
 await surface.dispose();
});
