import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {decodeTiffBlocks} from '../src/tiff-stream.js';import {Budget} from '../src/cache.js';import {createBlobSource} from '../src/blob-source.js';import {createSegmentedBytes} from '../src/segmented-bytes.js';import {createRgbSurface} from '../src/rgb-surface.js';import {imageHeader} from '../src/image-headers.js';
const wasmBinary=await readFile(new URL('../vendor/tiff-stream/tiff-stream.wasm',import.meta.url));
test('bounded libtiff strips/tiles preserve the classic and BigTIFF native RGB corpus',async()=>{
 for(const folder of ['tiff-formats','bigtiff']){const root=new URL('./data/'+folder+'/',import.meta.url),ref=JSON.parse(await readFile(new URL('reference.json',root)));for(const item of ref.cases){const bytes=new Uint8Array(await readFile(new URL(item.file,root))),header=imageHeader(bytes),budget=new Budget(128*1024**2),source=createBlobSource(new Blob([bytes]),{budget}),store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight*3,{budget}),surface=createRgbSurface(store,{width:header.sourceWidth,height:header.sourceHeight,orientation:1,budget});
  try{if(!item.rgbSha256){await assert.rejects(decodeTiffBlocks(source,header,store,{budget,wasmBinary}));continue;}await decodeTiffBlocks(source,header,store,{budget,wasmBinary});const part=await surface.readWindow();try{assert.equal(createHash('sha256').update(part.pixels.data).digest('hex'),item.rgbSha256,folder+'/'+item.file);}finally{part.release();}}finally{await surface.dispose();source.dispose();}assert.equal(budget.total(),0);
 }}
});
test('truncated tile refusal, async read cancellation and oversized block admission stay explicit',async()=>{
 const {tiffStreamPlan}=await import('../src/tiff-stream.js'),original=new Uint8Array(await readFile(new URL('./data/tiff-formats/tiled-rgb-u1.tiff',import.meta.url))),header=imageHeader(original),entry=header.directories[0].entries.find(e=>e.tag===324),firstOffset=Array.isArray(entry.value)?entry.value[0]:entry.value,corrupt=original.slice(0,firstOffset+4);
 for(const mode of ['bytes','cancel','budget']){const budget=new Budget((mode==='budget'?1:128)*1024**2),controller=new AbortController();class Input extends Blob{slice(start,end,...args){if(mode==='cancel')controller.abort();return super.slice(start,end,...args);}}const source=createBlobSource(new Input([mode==='bytes'?corrupt:original]),{budget}),store=await createSegmentedBytes(header.sourceWidth*header.sourceHeight*3,{budget});try{await assert.rejects(decodeTiffBlocks(source,header,store,{budget,wasmBinary,signal:controller.signal}),{code:mode==='cancel'?'CANCELLED':mode==='budget'?'MEMORY_LIMIT':'INVALID_INPUT'});assert.equal(budget.active,0);}finally{await store.dispose();source.dispose();}assert.equal(budget.total(),0);}
 assert.throws(()=>tiffStreamPlan({...header,sourceWidth:4000,sourceHeight:5500,tileWidth:4000,tileHeight:5500}),{code:'MEMORY_LIMIT'});
});
