import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {segmentedZeroVotes} from '../src/zero-stream.js';import {segmentedZeroRegions} from '../src/zero-region-stream.js';import {Budget} from '../src/cache.js';import {createRgbSurface} from '../src/rgb-surface.js';
const root=new URL('../fixtures/',import.meta.url),ref=JSON.parse(await readFile(new URL('zero-reference.json',root))),sha=a=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');
async function maskHash(store){const bytes=new Uint8Array(store.byteLength);await store.readInto(bytes);return sha(Int32Array.from(bytes));}
function checkRegions(actual,expected,name){assert.equal(actual.length,expected.length,name+' count');for(let i=0;i<actual.length;i++){const a=actual[i],e=expected[i];for(const key of ['x0','y0','x1','y1','grid'])assert.equal(a[key],e[key],name+' '+key);assert.ok(Math.abs(a.log10_nfa-e.log10_nfa)<=1e-10,name+' NFA');}}
test('global paged components, significance, native ordering and closing match the 76 native ZERO cases',async()=>{
 for(const item of ref.cases){const budget=new Budget(128*1024**2),data=new Uint8Array(await readFile(new URL(item.file,root))),image={surface:createRgbSurface({byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};let original,companion,foreign,missing;
  try{original=await segmentedZeroVotes(image,{budget});foreign=await segmentedZeroRegions(original.votes,item.width,item.height,{budget,gridToExclude:original.main_grid});const expected=item.expected[0];assert.equal(await maskHash(foreign.mask),expected.arrays.mask_f.sha256,item.name+' foreign');assert.equal(await maskHash(foreign.maskReg),expected.arrays.mask_f_reg.sha256,item.name+' foreign closing');checkRegions(foreign.regions,expected.metadata.foreign_regions,item.name+' foreign');
   const em=item.expected.find(e=>e.missing);if(em.metadata.missing_grid_analyzed){companion=await segmentedZeroVotes(image,{budget,companion:true});missing=await segmentedZeroRegions(companion.votes,item.width,item.height,{budget,gridMax:0,excludeVotes:original.votes,excludeGrid:original.main_grid});assert.equal(await maskHash(missing.mask),em.arrays.mask_m.sha256,item.name+' missing');assert.equal(await maskHash(missing.maskReg),em.arrays.mask_m_reg.sha256,item.name+' missing closing');checkRegions(missing.regions,em.metadata.missing_regions,item.name+' missing');}
  }finally{await foreign?.dispose();await missing?.dispose();await original?.dispose();await companion?.dispose();await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
 }
});
test('separate components restore x-major native order and retain edge/halo closing',async()=>{
 const {initZeroWasm}=await import('../src/zero.js'),{createSegmentedBytes}=await import('../src/segmented-bytes.js'),m=await initZeroWasm(),width=301,height=283,n=width*height,values=new Int32Array(n).fill(-1);
 for(const [x0,y0,grid]of [[0,230,4],[220,0,4],[105,100,7]])for(let y=y0;y<Math.min(height,y0+43);y++)for(let x=x0;x<x0+42;x++)values[y*width+x]=grid;
 const ptrs=[n*4,n*4,n*4,4096].map(bytes=>{const p=m._malloc(bytes);m.HEAPU8.fill(0,p,p+bytes);return p;}),budget=new Budget(64*1024**2);let store,result;
 try{new Int32Array(m.HEAPU8.buffer,ptrs[0],n).set(values);const count=m._detect_forgeries(...ptrs,width,height,-1,63),view=new DataView(m.HEAPU8.buffer),expected=[];for(let i=0;i<count;i++){const at=ptrs[3]+32*i;expected.push({x0:view.getInt32(at,true),y0:view.getInt32(at+4,true),x1:view.getInt32(at+8,true),y1:view.getInt32(at+12,true),grid:view.getInt32(at+16,true),log10_nfa:view.getFloat64(at+24,true)});}
  store=await createSegmentedBytes(n,{budget});await store.write(Uint8Array.from(values));result=await segmentedZeroRegions(store,width,height,{budget});assert.equal(count,3);checkRegions(result.regions,expected,'synthetic native');assert.equal(await maskHash(result.mask),sha(new Int32Array(m.HEAPU8.buffer,ptrs[1],n)));assert.equal(await maskHash(result.maskReg),sha(new Int32Array(m.HEAPU8.buffer,ptrs[2],n)));
 }finally{await result?.dispose();await store?.dispose();for(const p of ptrs)m._free(p);}assert.equal(budget.total(),0);
});
test('region refusal and consumer failure release all unpublished stores',async()=>{
 const {createSegmentedBytes}=await import('../src/segmented-bytes.js'),budget=new Budget(64*1024**2),store=await createSegmentedBytes(64*64,{budget});await store.write(new Uint8Array(64*64).fill(3));const baseline=budget.total();await assert.rejects(segmentedZeroRegions(store,64,64,{budget,onProgress:()=>{throw Error('consumer');}}),/consumer/);assert.equal(budget.total(),baseline);await assert.rejects(segmentedZeroRegions(store,64,64,{budget:new Budget(1024)}),{code:'MEMORY_LIMIT'});await store.dispose();assert.equal(budget.total(),0);
});
