import {exportAnalysis} from '../src/exports.js';
import {createWorkerEngine} from '../src/worker-client.js';
const read=async name=>new Uint8Array(await(await fetch('/fixtures/'+name)).arrayBuffer()),json=async name=>JSON.parse(new TextDecoder().decode(await read(name)));
const hash=async a=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a)),x=>x.toString(16).padStart(2,'0')).join('');
const assert=(v,m)=>{if(!v)throw new Error(m);};
async function check(r,e,label,report){
 for(const [k,a] of Object.entries(e.arrays))if(k==='grid_log10_nfa'){for(let i=0;i<64;i++){const error=Math.abs(r.data[k][i]-a.values[i]);report.maxSignificanceError=Math.max(report.maxSignificanceError,error);assert(error<=1e-8,label+' significance');assert((r.data[k][i]<0)===(a.values[i]<0),label+' significance decision');}}else assert(await hash(r.data[k])===a.sha256,label+' '+k);
 for(const k of ['main_grid','jpeg99_used','missing_grid_analyzed'])assert(r.data.metadata[k]===e.metadata[k],label+' '+k);
 for(const key of ['foreign_regions','missing_regions']){assert(r.data.metadata[key].length===e.metadata[key].length,label+' region count');for(let i=0;i<e.metadata[key].length;i++)for(const field of Object.keys(e.metadata[key][i])){const actual=r.data.metadata[key][i][field],expected=e.metadata[key][i][field];assert(field==='log10_nfa'?Math.abs(actual-expected)<=1e-8:actual===expected,label+' region '+field);}}
}
export async function zeroBrowserTest(){
 const ref=await json('zero-reference.json'),engine=createWorkerEngine({resourceHints:{hardwareConcurrency:4}}),report={schema:1,status:'passed',cases:0,views:0,maxSignificanceError:0,thresholdFallbacks:0,limits:['Synthetic corpus; physical Safari/mobile and WordPress UI not tested','Significance is float64 log10 NFA, not a manipulation probability']};
 try{for(const f of ref.cases){const bytes=await read(f.file);await engine.load({id:'i',bytes,pixels:{width:f.width,height:f.height,format:'rgb8',data:bytes}});for(const e of f.expected){const task={id:'z',imageId:'i',operation:'jpeg.zero',params:{missing:e.missing}},r=await engine.run(task);await check(r,e,f.name,report);report.cases++;report.thresholdFallbacks+=r.metrics.thresholdFallbacks;assert(await hash(r.pixels.data)===e.views[0],f.name+' regions');report.views++;r.data.votes.fill(99);
  for(let view=1;view<5;view++){const v=await engine.run({...task,params:{missing:e.missing,view}});assert(v.metrics.cache.analysis,'View must reuse analysis');assert(await hash(v.pixels.data)===e.views[view],f.name+' view '+view);report.views++;}}
  await engine.unload('i');
 }assert(report.thresholdFallbacks>0,'Threshold fallback was not exercised');console.log('ZERO small corpus',report.cases,report.views);
 const large=await json('zero-large-reference.json'),bytes=await read(large.file);await engine.load({id:'large',bytes});const r=await engine.run({id:'large',imageId:'large',operation:'jpeg.zero'});await check(r,large,'1 MP',report);assert(r.metrics.votePasses?.length>=1,'ZERO parallel path not exercised');assert(r.metrics.votePasses.every(x=>x.scheduling.preflightExecutions===0&&x.scheduling.taskExecutions===1),'Each scientific vote pass executes once without preflight');report.largeMetrics=r.metrics;
 let refused=false;try{await engine.exportResult(r,{format:'npz'});}catch(e){refused=e.code==='MEMORY_LIMIT';}assert(refused,'Large NPZ requires an explicit adequate byte budget');
 const options={format:'npz',maxBytes:128*1024**2},exported=await engine.exportResult(r,options),local=exportAnalysis(r,options);assert(await hash(exported.bytes)===await hash(local.bytes),'Worker NPZ differs from local serializer');assert(await hash(r.data.votes)===large.arrays.votes.sha256,'Export changed caller arrays');report.npz={bytes:exported.bytes.length,mime:exported.mime,sha256:await hash(exported.bytes),workerMatchesLocal:true};
 for(let view=0;view<5;view++){const v=await engine.run({id:'view',imageId:'large',operation:'jpeg.zero',params:{view}});assert(v.metrics.cache.analysis,'Large view cache');assert(await hash(v.pixels.data)===large.views[view],'Large ZERO view');}
 await engine.unload('large');await engine.load({id:'abort',bytes});const controller=new AbortController();let cancelled=false;try{await engine.run({id:'abort',imageId:'abort',operation:'jpeg.zero'},{signal:controller.signal,onProgress:()=>setTimeout(()=>controller.abort(),15)});}catch(e){cancelled=e.code==='CANCELLED'&&e.imagesCleared;}assert(cancelled,'ZERO cancellation');
 await engine.load({id:'recover',bytes:await read(ref.cases[0].file),pixels:{width:ref.cases[0].width,height:ref.cases[0].height,format:'rgb8',data:await read(ref.cases[0].file)}});const recovered=await engine.run({id:'recover',imageId:'recover',operation:'jpeg.zero'});assert(recovered.data.metadata.main_grid===-1,'Reload after cancellation');await engine.unload('recover');report.released=(await engine.capabilities()).memory;assert(!report.released.retainedBytes&&!report.released.cacheBytes&&!report.released.activeReservationBytes,'ZERO memory release');report.cancellation='Hard termination and explicit reload verified';return report;
 }finally{engine.dispose();}
}
