import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {segmentedZeroVotes,zeroWinningGrid} from '../src/zero-stream.js';import {Budget} from '../src/cache.js';import {createRgbSurface} from '../src/rgb-surface.js';import {createRgbRecompression} from '../src/jpeg-rgb-stream.js';
const root=new URL('../fixtures/',import.meta.url),ref=JSON.parse(await readFile(new URL('zero-reference.json',root))),sha=a=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');
async function source(item,budget){const data=new Uint8Array(await readFile(new URL(item.file,root)));return {surface:createRgbSurface({byteLength:data.length,readInto:(out,at)=>out.set(data.subarray(at,at+out.length))},{width:item.width,height:item.height,budget,ownsStore:false})};}
async function pixels(store,signed=false){const out=new Uint8Array(store.byteLength);await store.readInto(out);return signed?new Int8Array(out.buffer):out;}
test('native ZERO luminance/votes and global significance survive row halos, phases and compact storage',async()=>{
 for(const item of ref.cases){const budget=new Budget(96*1024**2),image=await source(item,budget);let original,companion;
  try{original=await segmentedZeroVotes(image,{budget});const expected=item.expected[0],lum=await pixels(original.luminance),votes=await pixels(original.votes,true);assert.equal(sha(Float64Array.from(lum)),expected.arrays.luminance.sha256,item.name+' luminance');assert.equal(sha(Int32Array.from(votes)),expected.arrays.votes.sha256,item.name+' votes');assert.equal(original.main_grid,expected.metadata.main_grid,item.name+' main');for(let i=0;i<64;i++){const value=expected.arrays.grid_log10_nfa.values[i],actual=original.grid_log10_nfa[i];assert.ok(actual===value||Math.abs(actual-value)<=1e-10,item.name+' significance');assert.equal(actual<0,value<0);}
   companion=await segmentedZeroVotes(image,{budget,companion:true});const expectedMissing=item.expected.find(e=>e.missing);if(expectedMissing.metadata.missing_grid_analyzed){const cLum=await pixels(companion.luminance),cVotes=Int32Array.from(await pixels(companion.votes,true));for(let i=0;i<votes.length;i++)if(votes[i]===original.main_grid)cVotes[i]=-1;assert.equal(sha(Float64Array.from(cLum)),expectedMissing.arrays.luminance_jpeg.sha256,item.name+' JPEG99 luminance');assert.equal(sha(cVotes),expectedMissing.arrays.votes_jpeg.sha256,item.name+' masked JPEG99 votes');}
   assert.equal(companion.metrics.jpeg99.sampling,'444');
  }finally{await original?.dispose();await companion?.dispose();await image.rgbRecompression?.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);
 }
});
test('JPEG99 global4:4:4 matches every native companion and remains distinct from4:2:0 cache entries',async()=>{
 for(const item of ref.cases){const budget=new Budget(64*1024**2),image=await source(item,budget),codec=createRgbRecompression(image,budget);try{const expected=new Uint8Array(await readFile(new URL(item.companion,root))),hash=createHash('sha256');await codec.visit(99,{sampling:'444',onBand:(_,rgb)=>hash.update(rgb)});assert.equal(hash.digest('hex'),sha(expected),item.name);assert.equal(codec.hasEncoded(99),false);assert.equal(codec.hasEncoded(99,{sampling:'444'}),true);const normal=await codec.visit(99,{onBand(){}});assert.equal(normal.recompressions,1);const repeat=await codec.visit(99,{sampling:'444',onBand(){}});assert.equal(repeat.recompressions,0);}finally{await codec.dispose();await image.surface.dispose();}assert.equal(budget.total(),0);}
});
test('global vote ties follow native x-major arrival, not numeric grid order',()=>{
 const counts=new Int32Array(64),last=new Float64Array(64);counts[0]=counts[7]=3;last[0]=40;last[7]=10;assert.equal(zeroWinningGrid(counts,last),7);counts[0]=4;assert.equal(zeroWinningGrid(counts,last),0);counts.fill(0);assert.equal(zeroWinningGrid(counts,last),-1);
});
test('ZERO staged memory refusal and cancellation remove unpublished planes and keep the source usable',async()=>{
 const item=ref.cases.find(c=>c.name==='spliced'),budget=new Budget(64*1024**2),image=await source(item,budget);
 try{for(const phase of ['zero-luminance','zero-votes']){const controller=new AbortController();await assert.rejects(segmentedZeroVotes(image,{budget,signal:controller.signal,onProgress:e=>{if(e.phase===phase)controller.abort();}}),{code:'CANCELLED'});assert.equal(budget.total(),0);}const result=await segmentedZeroVotes(image,{budget});await result.dispose();const tiny=new Budget(1024);await assert.rejects(segmentedZeroVotes(image,{budget:tiny}),{code:'MEMORY_LIMIT'});assert.equal(tiny.total(),0);}finally{await image.surface.dispose();}assert.equal(budget.total(),0);
});
