import "../../runtime-context.js?v=0.14.5";
import {requireValue,checkAbort} from './errors.js';
import {energyReferenceHeader} from './energy-pipeline.js';import {inspectJpegBlob} from './jpeg.js';
import {segmentedEnergyQualities} from './energy-qualities-stream.js';import {AdaptiveConcurrency} from './adaptive-concurrency.js';import {detectSegmentedPanels} from './auto-zones-stream.js';
import {prepareSegmentedEnergy} from './energy-prepare-stream.js';import {estimateSegmentedEnergy,segmentedEnergyDeviations} from './energy-auto-stream.js';
import {segmentSegmentedEnergy} from './energy-segment-stream.js';import {energyColor} from './energy-segment.js';import {energyProfile} from './energy-auto.js';
import {energyLogData} from './energy-log-data.js';import {referenceLogFunction} from './energy-log-reference.js';
function shared(value,cleanup){let refs=1,closed=false,cacheReleased=false;const release=async()=>{if(--refs===0){closed=true;await cleanup();}};return {value,retain(){requireValue(!closed,'Scientific resource disposed.');refs++;let done=false;return async()=>{if(!done){done=true;await release();}};},async dispose(){if(!cacheReleased){cacheReleased=true;await release();}}};}
async function closeAll(functions){const results=await Promise.allSettled(functions.map(f=>f()));const failed=results.find(r=>r.status==='rejected');if(failed)throw failed.reason;}
export function createSegmentedEnergyCache(image,budget,{maxWorkers=1,adaptive=new AdaptiveConcurrency()}={}){
 const {width,height}=image.surface.descriptor,planeCache=new Map(),preparedCache=new Map(),automaticCache=new Map();let panels,header,headerRead=false,current,currentKey,closed=false,log,logRelease;
 const initializeLog=()=>{if(!log){logRelease=budget.reserve(512*1024);try{log=referenceLogFunction({minimumBits:973078528,maximumBits:1157627904},new Uint8Array(energyLogData().buffer));}catch(e){logRelease();logRelease=null;throw e;}}};
 async function put(map,key,value,limit=3){if(map.has(key)){const old=map.get(key);map.delete(key);await old.dispose();}while(map.size>=limit){const first=map.keys().next().value,old=map.get(first);map.delete(first);await old.dispose();}map.set(key,value);}
 function get(map,key){const result=map.get(key);if(result){map.delete(key);map.set(key,result);}return result;}
 return {
  async analyze(p,{signal,onProgress}={}){
   requireValue(!closed,'Energy cache disposed.');checkAbort(signal);let block=p.block;while(Math.floor(height/block)*Math.floor(width/block)>16384)block+=8;requireValue(Math.floor(height/block)*Math.floor(width/block)>=25,'Image too small for25 complete native cells');initializeLog();const key=JSON.stringify(p),metrics={workers:1,kernel:'ela-energy-segmented',energyRecompressions:0,energyQualityPlanesComputed:0,energyPanelDetections:0,energyPreparationMs:0,energyProfileMs:0,energySegmentationMs:0,cache:{result:false,stages:{}}};
   if(current&&key===currentKey){metrics.cache.result=true;metrics.workers=0;return {analysis:current,metrics};}const old=current;current=null;currentKey=null;await old?.dispose();let segmented,preparedRelease;const planeReleases=[];
   try{
    if(!p.quality&&!headerRead){if(image.source){const signature=await image.source.read(0,Math.min(2,image.source.byteLength),{signal});let jpeg;try{jpeg=signature.bytes[0]===255&&signature.bytes[1]===216;}finally{signature.release();}if(jpeg)header=await inspectJpegBlob(image.source,{signal});}headerRead=true;}
    const quality=energyReferenceHeader(header,p.quality),q=quality.quality,levels=q<=5?[q,q+5,q+10]:q>=96?[q-10,q-5,q]:[q-5,q,q+5],planes=[];
    metrics.cache.stages['energy-panels']=!!panels;if(!panels){metrics.energyPanelDetections++;const result=await detectSegmentedPanels(image,{budget,signal,onProgress});panels=shared(result,()=>result.dispose());}
    // Pin and touch every reusable quality before inserting a missing neighbor.
    // Otherwise a downward quality shift evicts its next required plane.
    const reusable=new Map();for(const level of levels){const entry=get(planeCache,level);if(entry){reusable.set(level,entry);planeReleases.push(entry.retain());}}
    for(const level of levels)metrics.cache.stages['energy-plane/'+level]=reusable.has(level);
    const missing=levels.filter(level=>!reusable.has(level));if(missing.length){const computed=await segmentedEnergyQualities(image,missing,{budget,signal,onProgress,maxWorkers,adaptive,onPlane:async(level,result)=>{const entry=shared(result,()=>result.dispose());try{await put(planeCache,level,entry);}catch(error){await entry.dispose();throw error;}planeReleases.push(entry.retain());reusable.set(level,entry);}});Object.assign(metrics,computed);}
    for(const level of levels)planes.push(reusable.get(level).value.store);
    const prepare=async quantiles=>{const name='energy-scores/'+q+'/'+quantiles.join('/');let entry=get(preparedCache,name);metrics.cache.stages[name]=!!entry;if(!entry){const start=performance.now();const result=await prepareSegmentedEnergy(image,planes,quantiles,log,{budget,signal,onProgress,polygons:panels.value.polygons});metrics.energyPreparationMs+=performance.now()-start;entry=shared(result,()=>result.dispose());try{await put(preparedCache,name,entry);}catch(error){await entry.dispose();throw error;}}return {entry,release:entry.retain()};};
    let profile,prepared;
    if(p.profile==='sensitive'||p.profile==='conservative'){
     let auto=get(automaticCache,q);metrics.cache.stages['energy-auto/'+q]=!!auto;if(!auto){let estimate;const reference=await prepare([.1,.9]);try{const start=performance.now();estimate=await estimateSegmentedEnergy({...reference.entry.value,energy_planes:planes},log,{budget,signal,onProgress});metrics.energyProfileMs+=performance.now()-start;}finally{await reference.release();}const proposal=await prepare(estimate.quantiles);let thresholds;try{const start=performance.now();thresholds=await segmentedEnergyDeviations(proposal.entry.value,{budget,signal,onProgress});metrics.energyProfileMs+=performance.now()-start;}finally{await proposal.release();}const release=budget.reserve(8192);auto=shared({...estimate,thresholds},release);try{await put(automaticCache,q,auto);}catch(error){await auto.dispose();throw error;}}
     profile=energyProfile(auto.value,p.profile);
    }else profile=p.profile==='standard'?energyProfile(null,'standard'):{profile:'manual',quantiles:[p.histogramLow/1000,p.histogramHigh/1000],thresholds:[p.shadow/10,p.highlight/10],automatic:false};
    const acquired=await prepare(profile.quantiles);prepared=acquired.entry.value;preparedRelease=acquired.release;const start=performance.now();segmented=await segmentSegmentedEnergy({...prepared,metadata:{block}},{thresholds:profile.thresholds,minimum:p.minimum},{budget,signal,onProgress,temporarySession:image.session,getTemporarySession:image.ensureTemporarySession});metrics.energySegmentationMs=performance.now()-start;checkAbort(signal);
    const metadata={method:'ela_energy',version:1,...quality,qualities:levels,requested_block:p.block,block,image_shape:[height,width],valid_shape:[Math.floor(height/block)*block,Math.floor(width/block)*block],regions:segmented.regions,energy:{enabled:true,kind:'descriptive_energy_contrast',probability:false,reference:'per_detected_panel_trimmed_mean',quantiles:profile.quantiles,thresholds:profile.thresholds,profile:p.profile,automatic:profile.automatic===false?null:profile,panels:prepared.energy_summary,window:7,log_scale:.2,energy_floor:.25,quality_confirmation:'median',segmentation:'pixel_hysteresis_half_threshold',grouping:'reference_panel_and_energy_class',minimum_strong_pixels:block*block}},value={width,height,energy_planes:planes,energy_low_score:prepared.energy_low_score,energy_high_score:prepared.energy_high_score,energy_scope:prepared.energy_scope,energy_labels:segmented.labels,energy_summary:prepared.energy_summary,regions:segmented.regions,regionColors:segmented.regions.map(r=>({id:r.id,rgb:energyColor(r)})),metadata};
    const ownedSegmentation=segmented,releasePrepared=preparedRelease,releases=planeReleases.splice(0);segmented=null;preparedRelease=null;current=shared(value,()=>closeAll([()=>ownedSegmentation.dispose(),releasePrepared,...releases]));currentKey=key;return {analysis:current,metrics};
   }catch(error){await closeAll([()=>segmented?.dispose(),()=>preparedRelease?.(),...planeReleases]);throw error;}
  },
  async dispose(){if(closed)return;closed=true;const resources=[current,panels,...planeCache.values(),...preparedCache.values(),...automaticCache.values()].filter(Boolean);current=panels=null;planeCache.clear();preparedCache.clear();automaticCache.clear();try{await closeAll(resources.map(r=>()=>r.dispose()));}finally{log=null;logRelease?.();logRelease=null;}}
 };
}
