import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CHUNK_LIMIT,sha256,validateManifest,remoteBase,byteRange,dependencyResponse} from '../sherloq-browser/assets/dependency-core.js';
import {createChunkLoader} from '../sherloq-browser/assets/dependency-store.js';
import {writeResourceTar,importResourceTar} from '../sherloq-browser/assets/dependency-tar.js';
async function fixture(){const a=Uint8Array.of(0,1,2,3),b=Uint8Array.of(4,5,6,7),ha=await sha256(a),hb=await sha256(b),whole=new Uint8Array([...a,...b]);return {a,b,ha,hb,whole,m:{schema:'sherloq.dependencies/1',remoteBase:null,slots:['models'],chunks:{[ha]:4,[hb]:4},files:{'models/model.bin':{size:8,type:'application/octet-stream',sha256:await sha256(whole),chunks:[ha,hb]}}}};}
test('manifest rejects traversal, bad chunk boundaries and mutable remote origins',async()=>{const {m}=await fixture();assert.equal(CHUNK_LIMIT,100_000_000);assert.equal(validateManifest(m),m);assert.throws(()=>validateManifest({...m,files:{'models/../escape':m.files['models/model.bin']}}));assert.throws(()=>validateManifest({...m,chunks:Object.fromEntries(Object.keys(m.chunks).map(k=>[k,9]))}));assert.throws(()=>remoteBase('https://raw.githubusercontent.com/user/repo/main/'));assert.throws(()=>remoteBase('https://elsewhere.test/'));assert.equal(remoteBase('https://raw.githubusercontent.com/user/repo/'+'a'.repeat(40)+'/web-assets/').includes('web-assets'),true);});
test('range transport reads only needed pieces and preserves full bytes',async()=>{const {m,a,b,ha,whole}=await fixture(),f=m.files['models/model.bin'],seen=[];const load=async h=>(seen.push(h),h===ha?a:b);const read=range=>dependencyResponse(f,m,load,new Request('https://example.test/model',{headers:range?{range}:{}}));const r=read('bytes=2-5');assert.equal(r.status,206);assert.deepEqual([...new Uint8Array(await r.arrayBuffer())],[2,3,4,5]);assert.equal(seen.length,2);seen.length=0;assert.deepEqual([...new Uint8Array(await read('bytes=-2').arrayBuffer())],[6,7]);assert.equal(seen.length,1);assert.deepEqual(new Uint8Array(await read().arrayBuffer()),whole);assert.equal(read('bytes=8-').status,416);assert.equal(read('bytes=0-1,4-5').status,416);assert.equal(byteRange('bytes=-0',8),null);});
test('loader deduplicates concurrent fetches, checks integrity, and survives cache quota failure',async()=>{const {m,a,ha}=await fixture();let requests=0;const badCache={async match(){return new Response('corrupt');},async delete(){},async put(){throw Error('quota');}};const load=createChunkLoader(m,{base:'https://raw.githubusercontent.com/example/',scope:'https://site.test/app/',folder:async()=>null,cacheStorage:{async open(){return badCache;}},fetcher:async(u,o)=>{requests++;assert.equal(o.credentials,'omit');assert.equal(o.referrerPolicy,'no-referrer');return new Response(a);}});const [x,y]=await Promise.all([load(ha),load(ha)]);assert.equal(requests,1);assert.equal(x,y);assert.deepEqual(x,a);const corrupt=createChunkLoader(m,{base:'https://raw.githubusercontent.com/example/',scope:'https://site.test/',folder:async()=>null,cacheStorage:null,fetcher:async()=>new Response(Uint8Array.of(1,2,3,4))});await assert.rejects(corrupt(ha),/integrity/);});
test('standard TAR archive restores chunks exactly and rejects corruption/truncation',async()=>{const {m,a,b,ha}=await fixture(),parts=[];await writeResourceTar(m,async h=>h===ha?a:b,{async write(p){parts.push(p);}});const file=new Blob(parts),saved=new Map();await importResourceTar(file,m,async(h,p)=>saved.set(h,p));assert.deepEqual(saved.get(ha),a);assert.equal(saved.size,2);await assert.rejects(importResourceTar(file.slice(0,file.size-1),m,()=>{}),/Truncated|footer/);const bytes=new Uint8Array(await file.arrayBuffer());{let at=0;while(at<bytes.length&&bytes[at]){const size=parseInt(new TextDecoder().decode(bytes.subarray(at+124,at+136)),8);if(new TextDecoder().decode(bytes.subarray(at,at+100)).startsWith('models/model.bin')){bytes[at+512]^=255;break;}at+=512+Math.ceil(size/512)*512;}};await assert.rejects(importResourceTar(new Blob([bytes]),m,()=>{}),/integrity/);});
test('missing disconnected local copy fails explicitly without a remote origin',async()=>{const {m,ha}=await fixture();const load=createChunkLoader(m,{base:null,scope:'https://site.test/',folder:async()=>null,cacheStorage:null});await assert.rejects(load(ha),/DEPENDENCY_OFFLINE_MISSING/);});
