import test from 'node:test';import assert from 'node:assert/strict';
import {createRemoteSurface,displayViewport} from '../sherloq-browser/assets/remote-surface.js';import {TileCache} from '../sherloq-browser/assets/tiled-surface.js';
const flush=()=>new Promise(r=>setImmediate(r));
function setup(){const canvases=[];globalThis.document={createElement(){const c={width:0,height:0,getContext(){return {createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(image){c.image=image;}};}};canvases.push(c);return c;}};const tasks=[],events=[],cache=new TileCache(),display={width:12000,height:8000},surface=createRemoteSurface(display,cache,(_,{tile})=>new Promise((resolve,reject)=>tasks.push({tile,resolve,reject})),()=>events.push('changed'),e=>events.push(e.message));const finish=t=>t.resolve({pixels:{width:Math.ceil(t.tile.w/t.tile.step),height:Math.ceil(t.tile.h/t.tile.step),data:new Uint8Array(Math.ceil(t.tile.w/t.tile.step)*Math.ceil(t.tile.h/t.tile.step)*3)}});return{tasks,events,cache,surface,finish,canvases};}
const full={left:0,top:0,right:12000,bottom:8000};
test('one complete bounded frame replaces progressive tiles, redraws do not duplicate requests',async()=>{const h=setup();assert.equal(h.surface.prepare(full,.1),false);h.surface.prepare(full,.1);await flush();assert.equal(h.tasks.length,1);assert.equal(h.events.length,0);h.finish(h.tasks[0]);await flush();assert.equal(h.surface.prepare(full,.1),true);assert.deepEqual(h.events,['changed']);assert.ok(h.cache.bytes<=h.cache.limit);h.surface.close();assert.equal(h.cache.bytes,0);});
test('fast viewport changes coalesce; obsolete completion and closure never paint stale data',async()=>{const h=setup();h.surface.prepare(full,.1);await flush();const latest={left:123,top:80,right:801,bottom:700};for(let i=0;i<25;i++)h.surface.prepare({...latest,left:123+i},1);h.finish(h.tasks[0]);await flush();assert.equal(h.tasks.length,2);assert.equal(h.tasks[1].tile.x,146);assert.equal(h.events.length,0);h.surface.close();h.finish(h.tasks[1]);await flush();assert.equal(h.events.length,0);assert.equal(h.cache.bytes,0);});
test('loupe and shared image forks have independent viewports and close with their owner',async()=>{const h=setup(),child=h.surface.fork();h.surface.prepare(full,.1);child.prepare({left:200,top:200,right:300,bottom:300},2);await flush();assert.equal(h.tasks.length,2);for(const task of h.tasks)h.finish(task);await flush();assert.equal(h.surface.prepare(full,.1),true);assert.equal(child.prepare({left:210,top:210,right:290,bottom:290},2),true);h.surface.close();assert.equal(h.cache.bytes,0);assert.equal(child.prepare(full,1),false);});
test('100% geometry keeps individual pixels; odd edges stay bounded and canvas replacement is accounted once',()=>{const tile=displayViewport(1001,701,{left:900.5,top:600.5,right:1010,bottom:800},2);assert.equal(tile.step,1);assert.equal(tile.x+tile.w,1001);assert.equal(tile.y+tile.h,701);const cache=new TileCache(),first={width:20,height:30},next={width:40,height:50};cache.put('frame',first);cache.put('frame',next);assert.equal(cache.bytes,40*50*4);assert.equal(first.width,0);});
test('failed frame stops retrying unchanged geometry instead of creating a redraw loop',async()=>{const h=setup();h.surface.prepare(full,.1);await flush();h.tasks[0].reject(Error('read failed'));await flush();h.surface.prepare(full,.1);await flush();assert.equal(h.tasks.length,1);assert.deepEqual(h.events,['read failed']);h.surface.close();});
test('retained preview transfers the bounded frame and survives worker retirement without copies or reads',async()=>{
 const h=setup();h.surface.prepare(full,.1);await flush();h.finish(h.tasks[0]);await flush();const canvas=h.canvases[0],width=canvas.width,preview=h.surface.freeze();assert.equal(h.cache.bytes,0);h.surface.close();assert.equal(canvas.width,width);assert.equal(preview.previewOnly,true);assert.equal(preview.readPixels,undefined);
 const fork=preview.fork();let painted;preview.draw({save(){},beginPath(){},rect(){},clip(){},restore(){},drawImage:c=>painted=c});assert.equal(painted,canvas);assert.equal(preview.prepare(full,10),true);await flush();assert.equal(h.tasks.length,1);preview.close();assert.equal(canvas.width,width);fork.close();assert.equal(canvas.width,0);
});
