import {serializeEngineError} from '../sherloq-browser/assets/unified-engine/src/errors.js';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {resolveComputeProfile} from '../sherloq-browser/assets/resource-policy.js';
const code=(await readFile(new URL('../sherloq-browser/assets/engine-worker.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
function harness(){let options,copies=0,runs=0,loads=0;const messages=[],context=vm.createContext({serializeEngineError,AbortController,resolveComputeProfile:()=>({memoryBudgetBytes:128*1024**2}),createEngine:value=>{options=value;return{capabilities:()=>({}),loadBlob:async()=>{loads++;return{width:100,height:100,surface:{id:'im',width:100,height:100}};},imagePixels:()=>{copies++;throw Error('No full copy allowed');},run:async()=>{runs++;return{pixels:{width:100,height:100,data:new Uint8Array(30000)}};}};},self:{postMessage:value=>messages.push(value)}});new vm.Script(code).runInContext(context);return{send:async(action,uiRGBBudgetBytes,uiReserveBytes=32*1024**2)=>{await context.self.onmessage({data:{id:1,action,payload:{id:'im',imageId:'im',operation:'ela.classic'},options:{uiRGBBudgetBytes,uiReserveBytes}}});return messages.at(-1);},get options(){return options;},get copies(){return copies;},get runs(){return runs;},get loads(){return loads;}};}
test('UI and returned-result reservations are deducted from the shared budget',async()=>{const h=harness();await h.send('capabilities',100000);assert.equal(h.options.memoryBudgetBytes,96*1024**2-100000);});
test('Blob source loads without a complete outbound RGB copy; result admission uses actual consumer budget',async()=>{const h=harness();assert.ok((await h.send('load',29999)).result);assert.equal(h.loads,1);assert.equal(h.copies,0);assert.equal((await h.send('run',29999)).error.code,'RESULT_MEMORY_BUDGET');assert.equal(h.runs,0);const ready=harness();await ready.send('load',30000);assert.ok((await ready.send('run',30000)).result.display);assert.equal(ready.runs,1);});
test('insufficient total budget is an explicit error before engine creation',async()=>{const h=harness();assert.equal((await h.send('load',100000,120*1024**2)).error.code,'UI_MEMORY_BUDGET');assert.equal(h.options,undefined);});
test('real resource hints do not retain the obsolete 4 GiB RAM cap',()=>{const p=resolveComputeProfile('maximum',{deviceMemoryGiB:64,heapLimitBytes:16*1024**3,hardwareConcurrency:24});assert.ok(p.memoryBudgetBytes>4*1024**3);assert.equal(p.maxWorkers,24);});
